// src/lib/prompts/hyperrealism-text/atmosfera.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Atmósfera";
const CATEGORY = "Ambiente";

export const hyperrealismTextPromptsAtmosfera = [
  { id: "hyper-atm-ambiente-001", title: "Aire limpio", summary: "Sin haze.", area: AREA, category: CATEGORY, prompt: "aire limpio, visibilidad alta, atmósfera neutra realista" },
  { id: "hyper-atm-ambiente-002", title: "Haze suave", summary: "Profundidad.", area: AREA, category: CATEGORY, prompt: "haze suave y natural, profundidad atmosférica realista" },
  { id: "hyper-atm-ambiente-003", title: "Niebla ligera", summary: "Sutil.", area: AREA, category: CATEGORY, prompt: "niebla ligera, sin tapar el sujeto, realista" },
  { id: "hyper-atm-ambiente-004", title: "Niebla densa", summary: "Dramática controlada.", area: AREA, category: CATEGORY, prompt: "niebla densa realista, bordes suaves, sin look CGI" },
  { id: "hyper-atm-ambiente-005", title: "Neblina urbana", summary: "Ciudad real.", area: AREA, category: CATEGORY, prompt: "neblina urbana suave, faroles difusos, realismo fotográfico" },
  { id: "hyper-atm-ambiente-006", title: "Polvo en el aire", summary: "Partículas sutiles.", area: AREA, category: CATEGORY, prompt: "polvo sutil en el aire, partículas finas visibles contra luz" },
  { id: "hyper-atm-ambiente-007", title: "Partículas en contraluz", summary: "Cinemático.", area: AREA, category: CATEGORY, prompt: "partículas visibles en contraluz, dispersión natural" },
  { id: "hyper-atm-ambiente-008", title: "Humo leve", summary: "Ambiente suave.", area: AREA, category: CATEGORY, prompt: "humo leve realista, sin saturación rara, dispersión natural" },
  { id: "hyper-atm-ambiente-009", title: "Humo de cocina", summary: "Steam real.", area: AREA, category: CATEGORY, prompt: "vapor/humo de cocina realista, humedad visible, sin plástico" },
  { id: "hyper-atm-ambiente-010", title: "Vapor sutil", summary: "Calor real.", area: AREA, category: CATEGORY, prompt: "vapor sutil, condensación leve, realismo fotográfico" },

  { id: "hyper-atm-ambiente-011", title: "Lluvia fina", summary: "Gotas pequeñas.", area: AREA, category: CATEGORY, prompt: "lluvia fina realista, gotas pequeñas, ambiente húmedo" },
  { id: "hyper-atm-ambiente-012", title: "Lluvia intensa", summary: "Tormenta.", area: AREA, category: CATEGORY, prompt: "lluvia intensa realista, salpicaduras coherentes, visibilidad menor" },
  { id: "hyper-atm-ambiente-013", title: "Gotas en lente (sutil)", summary: "POV real.", area: AREA, category: CATEGORY, prompt: "gotas sutiles en el lente, sin exagerar, efecto real" },
  { id: "hyper-atm-ambiente-014", title: "Charcos reflectantes", summary: "Reflejos reales.", area: AREA, category: CATEGORY, prompt: "charcos con reflejos coherentes, distorsión natural del agua" },
  { id: "hyper-atm-ambiente-015", title: "Asfalto mojado", summary: "Brillo real.", area: AREA, category: CATEGORY, prompt: "asfalto mojado realista, specular natural, sin neón fake" },
  { id: "hyper-atm-ambiente-016", title: "Humedad alta", summary: "Aire pesado.", area: AREA, category: CATEGORY, prompt: "humedad alta, ligera bruma, piel y superficies con shine natural" },
  { id: "hyper-atm-ambiente-017", title: "Condensación en vidrio", summary: "Detalle.", area: AREA, category: CATEGORY, prompt: "condensación en vidrio, gotas y empañado realista" },
  { id: "hyper-atm-ambiente-018", title: "Vaho en frío", summary: "Respiración visible.", area: AREA, category: CATEGORY, prompt: "vaho de respiración en clima frío, realista y sutil" },
  { id: "hyper-atm-ambiente-019", title: "Nieve ligera", summary: "Copos finos.", area: AREA, category: CATEGORY, prompt: "nieve ligera, copos finos, acumulación mínima realista" },
  { id: "hyper-atm-ambiente-020", title: "Nieve intensa", summary: "Baja visibilidad.", area: AREA, category: CATEGORY, prompt: "nieve intensa y realista, visibilidad reducida, sin look 3D" },

  { id: "hyper-atm-ambiente-021", title: "Amanecer", summary: "Bruma suave.", area: AREA, category: CATEGORY, prompt: "atmósfera de amanecer, bruma suave, tonos naturales" },
  { id: "hyper-atm-ambiente-022", title: "Hora dorada", summary: "Cálido real.", area: AREA, category: CATEGORY, prompt: "hora dorada realista, luz cálida suave, sombras largas" },
  { id: "hyper-atm-ambiente-023", title: "Mediodía", summary: "Duro real.", area: AREA, category: CATEGORY, prompt: "luz de mediodía, sombras marcadas, contraste realista" },
  { id: "hyper-atm-ambiente-024", title: "Atardecer", summary: "Cielo real.", area: AREA, category: CATEGORY, prompt: "atardecer realista, cielo con gradiente natural, sin HDR" },
  { id: "hyper-atm-ambiente-025", title: "Hora azul", summary: "Azul suave.", area: AREA, category: CATEGORY, prompt: "hora azul realista, ambiente frío suave, luces cálidas puntuales" },
  { id: "hyper-atm-ambiente-026", title: "Noche (sin neón)", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "noche realista, luz ambiental baja, sin neones exagerados" },
  { id: "hyper-atm-ambiente-027", title: "Noche con faroles", summary: "Difusión.", area: AREA, category: CATEGORY, prompt: "faroles con difusión suave, bloom mínimo realista" },
  { id: "hyper-atm-ambiente-028", title: "Interior nocturno", summary: "Calidez low light.", area: AREA, category: CATEGORY, prompt: "interior nocturno, luz cálida real, sombras suaves, sin ruido artificial" },
  { id: "hyper-atm-ambiente-029", title: "Día nublado", summary: "Difuso.", area: AREA, category: CATEGORY, prompt: "día nublado, luz difusa, colores ligeramente apagados realistas" },
  { id: "hyper-atm-ambiente-030", title: "Clima tormentoso", summary: "Tensión.", area: AREA, category: CATEGORY, prompt: "cielo tormentoso realista, contraste dramático controlado" },

  { id: "hyper-atm-ambiente-031", title: "Viento leve", summary: "Movimiento sutil.", area: AREA, category: CATEGORY, prompt: "viento leve: cabello/tela con movimiento sutil y realista" },
  { id: "hyper-atm-ambiente-032", title: "Viento fuerte", summary: "Acción.", area: AREA, category: CATEGORY, prompt: "viento fuerte realista: ropa/cabello coherente, sin deformación" },
  { id: "hyper-atm-ambiente-033", title: "Arena en el aire", summary: "Desierto.", area: AREA, category: CATEGORY, prompt: "arena suspendida realista, granos finos, visibilidad reducida" },
  { id: "hyper-atm-ambiente-034", title: "Dunas con polvo", summary: "Textura.", area: AREA, category: CATEGORY, prompt: "polvo levantándose en dunas, textura realista, sin patrones repetidos" },
  { id: "hyper-atm-ambiente-035", title: "Brisa marina", summary: "Salitre.", area: AREA, category: CATEGORY, prompt: "brisa marina, ligera neblina salina, ambiente húmedo" },
  { id: "hyper-atm-ambiente-036", title: "Spray de olas", summary: "Gotas.", area: AREA, category: CATEGORY, prompt: "spray de olas realista, gotas finas en el aire, luz coherente" },
  { id: "hyper-atm-ambiente-037", title: "Hielo y escarcha", summary: "Frío real.", area: AREA, category: CATEGORY, prompt: "escarcha sutil en superficies, cristales realistas, no CGI" },
  { id: "hyper-atm-ambiente-038", title: "Llovizna + neblina", summary: "Mood.", area: AREA, category: CATEGORY, prompt: "llovizna con neblina, atmósfera suave, contraste controlado" },
  { id: "hyper-atm-ambiente-039", title: "Calor (heat haze)", summary: "Ondas.", area: AREA, category: CATEGORY, prompt: "heat haze sutil (ondas de calor), efecto realista suave" },
  { id: "hyper-atm-ambiente-040", title: "Ambiente seco", summary: "Polvo mínimo.", area: AREA, category: CATEGORY, prompt: "ambiente seco, polvo mínimo en superficies, realista" },

  { id: "hyper-atm-ambiente-041", title: "Bokeh de luces", summary: "Noche.", area: AREA, category: CATEGORY, prompt: "bokeh de luces realista en fondo, forma natural, sin patrones" },
  { id: "hyper-atm-ambiente-042", title: "Bloom mínimo", summary: "Sin glow fake.", area: AREA, category: CATEGORY, prompt: "bloom mínimo y realista, sin glow exagerado" },
  { id: "hyper-atm-ambiente-043", title: "Flare realista", summary: "Muy sutil.", area: AREA, category: CATEGORY, prompt: "lens flare realista muy sutil, sin estilo videojuego" },
  { id: "hyper-atm-ambiente-044", title: "Reflejos húmedos", summary: "Detalles.", area: AREA, category: CATEGORY, prompt: "reflejos húmedos naturales en superficies, especular coherente" },
  { id: "hyper-atm-ambiente-045", title: "Motitas en aire interior", summary: "Casa/luz.", area: AREA, category: CATEGORY, prompt: "motitas de polvo visibles en rayo de luz interior, realista" },
  { id: "hyper-atm-ambiente-046", title: "Rayos de luz", summary: "Volumétrico real.", area: AREA, category: CATEGORY, prompt: "rayos de luz volumétricos realistas, densidad suave" },
  { id: "hyper-atm-ambiente-047", title: "Volumétrico suave", summary: "Cine.", area: AREA, category: CATEGORY, prompt: "volumétrico suave, sin niebla excesiva, realismo" },
  { id: "hyper-atm-ambiente-048", title: "Atmósfera de estudio", summary: "Limpia.", area: AREA, category: CATEGORY, prompt: "atmósfera de estudio limpia, sin partículas, look comercial" },
  { id: "hyper-atm-ambiente-049", title: "Atmósfera backstage", summary: "Cálida.", area: AREA, category: CATEGORY, prompt: "backstage realista: luz práctica, aire ligeramente cargado" },
  { id: "hyper-atm-ambiente-050", title: "Atmósfera callejera", summary: "Real.", area: AREA, category: CATEGORY, prompt: "atmósfera callejera realista, ligera contaminación/haze natural" },

  { id: "hyper-atm-ambiente-051", title: "Humedad en piel", summary: "Brillo real.", area: AREA, category: CATEGORY, prompt: "brillo de humedad en piel realista, sin plástico" },
  { id: "hyper-atm-ambiente-052", title: "Rocío", summary: "Gotas pequeñas.", area: AREA, category: CATEGORY, prompt: "rocío en hojas/superficies, gotas pequeñas, macro realista" },
  { id: "hyper-atm-ambiente-053", title: "Micro gotas", summary: "Detalle.", area: AREA, category: CATEGORY, prompt: "micro gotas dispersas, tensión superficial realista" },
  { id: "hyper-atm-ambiente-054", title: "Superficie mojada", summary: "Specular.", area: AREA, category: CATEGORY, prompt: "superficie mojada realista, reflejo controlado, textura visible" },
  { id: "hyper-atm-ambiente-055", title: "Vidrio empañado", summary: "Interior frío.", area: AREA, category: CATEGORY, prompt: "vidrio empañado realista, condensación natural" },
  { id: "hyper-atm-ambiente-056", title: "Respiración visible", summary: "Clima frío.", area: AREA, category: CATEGORY, prompt: "respiración visible sutil, clima frío, realista" },
  { id: "hyper-atm-ambiente-057", title: "Ceniza en aire", summary: "Sin apocalipsis.", area: AREA, category: CATEGORY, prompt: "ceniza ligera en el aire, partículas finas, realista" },
  { id: "hyper-atm-ambiente-058", title: "Chispas leves", summary: "Taller.", area: AREA, category: CATEGORY, prompt: "chispas leves de taller, exposición realista, sin fireworks" },
  { id: "hyper-atm-ambiente-059", title: "Humo industrial", summary: "Suave.", area: AREA, category: CATEGORY, prompt: "humo industrial suave y creíble, sin densidad imposible" },
  { id: "hyper-atm-ambiente-060", title: "Vaho de comida", summary: "Apetitoso.", area: AREA, category: CATEGORY, prompt: "vaho sutil saliendo de comida, realista, no exagerado" },

  { id: "hyper-atm-ambiente-061", title: "Bokeh navideño (real)", summary: "Luces cálidas.", area: AREA, category: CATEGORY, prompt: "bokeh de luces cálidas realistas, sin formas repetidas" },
  { id: "hyper-atm-ambiente-062", title: "Festival (natural)", summary: "Luces suaves.", area: AREA, category: CATEGORY, prompt: "luces de festival realistas, exposición correcta, sin neón cuchillo" },
  { id: "hyper-atm-ambiente-063", title: "Lámpara práctica", summary: "Interior.", area: AREA, category: CATEGORY, prompt: "luz práctica (lámpara) iluminando escena, sombras coherentes" },
  { id: "hyper-atm-ambiente-064", title: "Ventana difusa", summary: "Soft daylight.", area: AREA, category: CATEGORY, prompt: "luz de ventana difusa, ambiente natural, contraste suave" },
  { id: "hyper-atm-ambiente-065", title: "Rayo de sol", summary: "Cortina.", area: AREA, category: CATEGORY, prompt: "rayo de sol entrando, polvo sutil, look realista" },
  { id: "hyper-atm-ambiente-066", title: "Sombras de persiana", summary: "Interior.", area: AREA, category: CATEGORY, prompt: "sombras de persiana realistas, patrón suave, no perfecto" },
  { id: "hyper-atm-ambiente-067", title: "Reflejo de agua", summary: "Pool.", area: AREA, category: CATEGORY, prompt: "reflejo de agua proyectado, caústicas suaves y realistas" },
  { id: "hyper-atm-ambiente-068", title: "Caústicas suaves", summary: "Agua real.", area: AREA, category: CATEGORY, prompt: "caústicas suaves (agua) realistas, sin patrón artificial" },
  { id: "hyper-atm-ambiente-069", title: "Ambiente de bosque", summary: "Húmedo.", area: AREA, category: CATEGORY, prompt: "bosque húmedo con bruma ligera, colores naturales" },
  { id: "hyper-atm-ambiente-070", title: "Montaña fría", summary: "Aire fino.", area: AREA, category: CATEGORY, prompt: "aire frío de montaña, nitidez natural, bruma mínima" },

  { id: "hyper-atm-ambiente-071", title: "Ciudad después de lluvia", summary: "Reflejos.", area: AREA, category: CATEGORY, prompt: "ciudad después de lluvia, reflejos en asfalto, realista" },
  { id: "hyper-atm-ambiente-072", title: "Carretera mojada", summary: "Noche.", area: AREA, category: CATEGORY, prompt: "carretera mojada, reflejos de faros reales, sin neón exagerado" },
  { id: "hyper-atm-ambiente-073", title: "Interior con humo leve", summary: "Cine.", area: AREA, category: CATEGORY, prompt: "interior con haze muy leve, rayos suaves, realista" },
  { id: "hyper-atm-ambiente-074", title: "Taller con polvo", summary: "Industrial.", area: AREA, category: CATEGORY, prompt: "taller con polvo en aire, luz lateral, textura real" },
  { id: "hyper-atm-ambiente-075", title: "Cocina con vapor", summary: "Food.", area: AREA, category: CATEGORY, prompt: "cocina con vapor del plato, humedad realista" },
  { id: "hyper-atm-ambiente-076", title: "Cafetería con vapor", summary: "Café.", area: AREA, category: CATEGORY, prompt: "vapor de café realista, ambiente cálido, sin exceso" },
  { id: "hyper-atm-ambiente-077", title: "Vaho en ventana", summary: "Invierno.", area: AREA, category: CATEGORY, prompt: "vaho en ventana interior, condensación natural, detalle real" },
  { id: "hyper-atm-ambiente-078", title: "Niebla en carretera", summary: "Mood.", area: AREA, category: CATEGORY, prompt: "niebla en carretera, faros difusos, profundidad realista" },
  { id: "hyper-atm-ambiente-079", title: "Lluvia con contraluz", summary: "Gotas.", area: AREA, category: CATEGORY, prompt: "lluvia con contraluz, gotas visibles, exposición realista" },
  { id: "hyper-atm-ambiente-080", title: "Nieve con contraluz", summary: "Copos.", area: AREA, category: CATEGORY, prompt: "nieve con contraluz, copos visibles, ambiente frío real" },

  { id: "hyper-atm-ambiente-081", title: "Ambiente minimal", summary: "Sin distracciones.", area: AREA, category: CATEGORY, prompt: "ambiente minimal, aire limpio, sin elementos extra" },
  { id: "hyper-atm-ambiente-082", title: "Ambiente íntimo", summary: "Cerca.", area: AREA, category: CATEGORY, prompt: "ambiente íntimo, luz suave, aire tranquilo realista" },
  { id: "hyper-atm-ambiente-083", title: "Ambiente tenso", summary: "Dramático real.", area: AREA, category: CATEGORY, prompt: "ambiente tenso, contraste moderado, atmósfera creíble" },
  { id: "hyper-atm-ambiente-084", title: "Ambiente alegre", summary: "Luminoso.", area: AREA, category: CATEGORY, prompt: "ambiente alegre, luz natural, colores limpios sin oversat" },
  { id: "hyper-atm-ambiente-085", title: "Ambiente nostálgico", summary: "Film leve.", area: AREA, category: CATEGORY, prompt: "ambiente nostálgico, tonos suaves, grano sutil (si aplica)" },
  { id: "hyper-atm-ambiente-086", title: "Ambiente de madrugada", summary: "Silencio.", area: AREA, category: CATEGORY, prompt: "madrugada realista, luz mínima, atmósfera calmada" },
  { id: "hyper-atm-ambiente-087", title: "Ambiente de tarde", summary: "Normal.", area: AREA, category: CATEGORY, prompt: "tarde natural, luz estable, atmósfera neutra realista" },
  { id: "hyper-atm-ambiente-088", title: "Ambiente de oficina", summary: "Práctico.", area: AREA, category: CATEGORY, prompt: "ambiente de oficina realista, luz mixta controlada, sin verde raro" },
  { id: "hyper-atm-ambiente-089", title: "Ambiente de gimnasio", summary: "Sudor real.", area: AREA, category: CATEGORY, prompt: "gimnasio realista, humedad/sudor sutil, aire cálido" },
  { id: "hyper-atm-ambiente-090", title: "Ambiente de calle", summary: "Ruido visual controlado.", area: AREA, category: CATEGORY, prompt: "calle realista con vida, haze leve, sin caos artificial" },

  { id: "hyper-atm-ambiente-091", title: "Sin partículas exageradas", summary: "Evita fantasía.", area: AREA, category: CATEGORY, prompt: "sin partículas exageradas, todo sutil y fotográfico" },
  { id: "hyper-atm-ambiente-092", title: "Sin humo tipo stage", summary: "No concierto.", area: AREA, category: CATEGORY, prompt: "evitar humo tipo escenario, mantener dispersión natural" },
  { id: "hyper-atm-ambiente-093", title: "Sin volumétricos falsos", summary: "Real.", area: AREA, category: CATEGORY, prompt: "evitar volumétricos falsos, densidad baja y coherente" },
  { id: "hyper-atm-ambiente-094", title: "Sin neón cyberpunk", summary: "No caricatura.", area: AREA, category: CATEGORY, prompt: "evitar neón cyberpunk exagerado, mantener luz realista" },
  { id: "hyper-atm-ambiente-095", title: "Detalle atmosférico real", summary: "Cierre.", area: AREA, category: CATEGORY, prompt: "detalle atmosférico realista, sensación de lugar auténtico" },
  { id: "hyper-atm-ambiente-096", title: "Profundidad atmosférica", summary: "Distancia.", area: AREA, category: CATEGORY, prompt: "profundidad atmosférica en distancia, tono y contraste bajan gradualmente" },
  { id: "hyper-atm-ambiente-097", title: "Perspectiva con neblina", summary: "Lejos suave.", area: AREA, category: CATEGORY, prompt: "elementos lejanos suavizados por atmósfera, realista" },
  { id: "hyper-atm-ambiente-098", title: "Ambiente húmedo urbano", summary: "Ciudad.", area: AREA, category: CATEGORY, prompt: "ambiente húmedo urbano, reflejos sutiles, aire pesado" },
  { id: "hyper-atm-ambiente-099", title: "Ambiente frío seco", summary: "Claridad.", area: AREA, category: CATEGORY, prompt: "ambiente frío seco, aire nítido, sombras limpias" },
  { id: "hyper-atm-ambiente-100", title: "Ambiente cálido húmedo", summary: "Tropical.", area: AREA, category: CATEGORY, prompt: "ambiente cálido húmedo, bruma suave, condensación sutil" },
];
