// src/lib/prompts/hyperrealism-text/atmosfera.js
// Unikalny obszar i kategoria dla CAŁEGO tego pliku:
const AREA = "Atmosfera";
const CATEGORY = "Otoczenie";

export const hyperrealismTextPromptsAtmosfera = [
  { id: "hyper-atm-ambiente-001", title: "Czyste powietrze", summary: "Bez mgiełki.", area: AREA, category: CATEGORY, prompt: "czyste powietrze, wysoka widoczność, realistyczna neutralna atmosfera" },
  { id: "hyper-atm-ambiente-002", title: "Delikatna mgiełka (haze)", summary: "Głębia.", area: AREA, category: CATEGORY, prompt: "delikatna i naturalna mgiełka (haze), realistyczna głębia atmosferyczna" },
  { id: "hyper-atm-ambiente-003", title: "Lekka mgła", summary: "Subtelna.", area: AREA, category: CATEGORY, prompt: "lekka mgła, nie zasłaniająca obiektu, realistyczna" },
  { id: "hyper-atm-ambiente-004", title: "Gęsta mgła", summary: "Kontrolowany dramatyzm.", area: AREA, category: CATEGORY, prompt: "realistyczna gęsta mgła, miękkie krawędzie, bez wyglądu CGI" },
  { id: "hyper-atm-ambiente-005", title: "Mgiełka miejska", summary: "Prawdziwe miasto.", area: AREA, category: CATEGORY, prompt: "delikatna miejska mgiełka, rozproszone latarnie, realizm fotograficzny" },
  { id: "hyper-atm-ambiente-006", title: "Kurz w powietrzu", summary: "Subtelne cząsteczki.", area: AREA, category: CATEGORY, prompt: "subtelny kurz w powietrzu, drobne cząsteczki widoczne pod światło" },
  { id: "hyper-atm-ambiente-007", title: "Cząsteczki pod światło", summary: "Filmowo.", area: AREA, category: CATEGORY, prompt: "cząsteczki widoczne pod światło, naturalne rozproszenie" },
  { id: "hyper-atm-ambiente-008", title: "Lekki dym", summary: "Delikatny klimat.", area: AREA, category: CATEGORY, prompt: "realistyczny lekki dym, bez dziwnej saturacji, naturalne rozproszenie" },
  { id: "hyper-atm-ambiente-009", title: "Dym/pary z kuchni", summary: "Prawdziwa para.", area: AREA, category: CATEGORY, prompt: "realistyczna para/dym kuchenny, widoczna wilgoć, bez plastiku" },
  { id: "hyper-atm-ambiente-010", title: "Subtelna para", summary: "Prawdziwe ciepło.", area: AREA, category: CATEGORY, prompt: "subtelna para, lekka kondensacja, realizm fotograficzny" },

  { id: "hyper-atm-ambiente-011", title: "Drobny deszcz", summary: "Małe krople.", area: AREA, category: CATEGORY, prompt: "realistyczna mżawka/drobny deszcz, małe krople, wilgotne otoczenie" },
  { id: "hyper-atm-ambiente-012", title: "Ulewny deszcz", summary: "Burza.", area: AREA, category: CATEGORY, prompt: "realistyczny ulewny deszcz, spójne rozbryzgi, mniejsza widoczność" },
  { id: "hyper-atm-ambiente-013", title: "Krople na obiektywie (subtelnie)", summary: "Prawdziwe POV.", area: AREA, category: CATEGORY, prompt: "subtelne krople na obiektywie, bez przesady, realistyczny efekt" },
  { id: "hyper-atm-ambiente-014", title: "Odbijające kałuże", summary: "Prawdziwe odbicia.", area: AREA, category: CATEGORY, prompt: "kałuże ze spójnymi odbiciami, naturalna deformacja wody" },
  { id: "hyper-atm-ambiente-015", title: "Mokry asfalt", summary: "Prawdziwy połysk.", area: AREA, category: CATEGORY, prompt: "realistyczny mokry asfalt, naturalny specular, bez sztucznego neonu" },
  { id: "hyper-atm-ambiente-016", title: "Wysoka wilgotność", summary: "Ciężkie powietrze.", area: AREA, category: CATEGORY, prompt: "wysoka wilgotność, lekka mgiełka, skóra i powierzchnie z naturalnym połyskiem" },
  { id: "hyper-atm-ambiente-017", title: "Kondensacja na szybie", summary: "Detal.", area: AREA, category: CATEGORY, prompt: "kondensacja na szybie, krople i zaparowanie realistyczne" },
  { id: "hyper-atm-ambiente-018", title: "Para oddechu na mrozie", summary: "Widoczny oddech.", area: AREA, category: CATEGORY, prompt: "para oddechu w zimnym klimacie, realistyczna i subtelna" },
  { id: "hyper-atm-ambiente-019", title: "Lekki śnieg", summary: "Drobne płatki.", area: AREA, category: CATEGORY, prompt: "lekki śnieg, drobne płatki, minimalne realistyczne osiadanie" },
  { id: "hyper-atm-ambiente-020", title: "Intensywny śnieg", summary: "Niska widoczność.", area: AREA, category: CATEGORY, prompt: "intensywny, realistyczny śnieg, ograniczona widoczność, bez wyglądu 3D" },

  { id: "hyper-atm-ambiente-021", title: "Świt", summary: "Delikatna mgiełka.", area: AREA, category: CATEGORY, prompt: "atmosfera świtu, delikatna mgiełka, naturalne tony" },
  { id: "hyper-atm-ambiente-022", title: "Złota godzina", summary: "Realistyczne ciepło.", area: AREA, category: CATEGORY, prompt: "realistyczna złota godzina, miękkie ciepłe światło, długie cienie" },
  { id: "hyper-atm-ambiente-023", title: "Południe", summary: "Twarde, realistyczne.", area: AREA, category: CATEGORY, prompt: "światło południa, wyraźne cienie, realistyczny kontrast" },
  { id: "hyper-atm-ambiente-024", title: "Zachód słońca", summary: "Prawdziwe niebo.", area: AREA, category: CATEGORY, prompt: "realistyczny zachód słońca, naturalny gradient na niebie, bez HDR" },
  { id: "hyper-atm-ambiente-025", title: "Niebieska godzina", summary: "Miękki błękit.", area: AREA, category: CATEGORY, prompt: "realistyczna niebieska godzina, delikatnie chłodne otoczenie, punktowe ciepłe światła" },
  { id: "hyper-atm-ambiente-026", title: "Noc (bez neonu)", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "realistyczna noc, niskie światło ambientowe, bez przesadzonych neonów" },
  { id: "hyper-atm-ambiente-027", title: "Noc z latarniami", summary: "Dyfuzja.", area: AREA, category: CATEGORY, prompt: "latarnie z delikatną dyfuzją, minimalny realistyczny bloom" },
  { id: "hyper-atm-ambiente-028", title: "Nocne wnętrze", summary: "Ciepło low light.", area: AREA, category: CATEGORY, prompt: "nocne wnętrze, prawdziwe ciepłe światło, miękkie cienie, bez sztucznego szumu" },
  { id: "hyper-atm-ambiente-029", title: "Pochmurny dzień", summary: "Rozproszenie.", area: AREA, category: CATEGORY, prompt: "pochmurny dzień, rozproszone światło, lekko przygaszone realistyczne kolory" },
  { id: "hyper-atm-ambiente-030", title: "Burzowa pogoda", summary: "Napięcie.", area: AREA, category: CATEGORY, prompt: "realistyczne burzowe niebo, kontrolowany dramatyczny kontrast" },

  { id: "hyper-atm-ambiente-031", title: "Lekki wiatr", summary: "Subtelny ruch.", area: AREA, category: CATEGORY, prompt: "lekki wiatr: włosy/tkanina poruszają się subtelnie i realistycznie" },
  { id: "hyper-atm-ambiente-032", title: "Silny wiatr", summary: "Akcja.", area: AREA, category: CATEGORY, prompt: "realistyczny silny wiatr: spójny ruch ubrań/włosów, bez deformacji" },
  { id: "hyper-atm-ambiente-033", title: "Piasek w powietrzu", summary: "Pustynia.", area: AREA, category: CATEGORY, prompt: "realistycznie unoszący się piasek, drobne ziarenka, obniżona widoczność" },
  { id: "hyper-atm-ambiente-034", title: "Wydmy z pyłem", summary: "Faktura.", area: AREA, category: CATEGORY, prompt: "pył unoszący się nad wydmami, realistyczna faktura, bez powtarzalnych wzorów" },
  { id: "hyper-atm-ambiente-035", title: "Morska bryza", summary: "Sól w powietrzu.", area: AREA, category: CATEGORY, prompt: "morska bryza, lekka słona mgiełka, wilgotne otoczenie" },
  { id: "hyper-atm-ambiente-036", title: "Rozbryzg fal", summary: "Krople.", area: AREA, category: CATEGORY, prompt: "realistyczny rozbryzg fal, drobne krople w powietrzu, spójne światło" },
  { id: "hyper-atm-ambiente-037", title: "Lód i szron", summary: "Prawdziwy chłód.", area: AREA, category: CATEGORY, prompt: "subtelny szron na powierzchniach, realistyczne kryształki, bez CGI" },
  { id: "hyper-atm-ambiente-038", title: "Mżawka + mgiełka", summary: "Nastrój.", area: AREA, category: CATEGORY, prompt: "mżawka z mgiełką, miękka atmosfera, kontrolowany kontrast" },
  { id: "hyper-atm-ambiente-039", title: "Upał (heat haze)", summary: "Fale.", area: AREA, category: CATEGORY, prompt: "subtelny heat haze (falowanie gorąca), miękki realistyczny efekt" },
  { id: "hyper-atm-ambiente-040", title: "Suche otoczenie", summary: "Minimalny kurz.", area: AREA, category: CATEGORY, prompt: "suche otoczenie, minimalny kurz na powierzchniach, realistyczne" },

  { id: "hyper-atm-ambiente-041", title: "Bokeh świateł", summary: "Noc.", area: AREA, category: CATEGORY, prompt: "realistyczny bokeh świateł w tle, naturalny kształt, bez wzorów" },
  { id: "hyper-atm-ambiente-042", title: "Minimalny bloom", summary: "Bez sztucznego glow.", area: AREA, category: CATEGORY, prompt: "minimalny i realistyczny bloom, bez przesadzonego glow" },
  { id: "hyper-atm-ambiente-043", title: "Realistyczny flare", summary: "Bardzo subtelny.", area: AREA, category: CATEGORY, prompt: "bardzo subtelny realistyczny lens flare, bez stylu gry wideo" },
  { id: "hyper-atm-ambiente-044", title: "Mokre refleksy", summary: "Detale.", area: AREA, category: CATEGORY, prompt: "naturalne mokre refleksy na powierzchniach, spójny specular" },
  { id: "hyper-atm-ambiente-045", title: "Pyłki w powietrzu we wnętrzu", summary: "Dom/światło.", area: AREA, category: CATEGORY, prompt: "drobinki kurzu widoczne w promieniu światła we wnętrzu, realistyczne" },
  { id: "hyper-atm-ambiente-046", title: "Promienie światła", summary: "Realistyczna wolumetria.", area: AREA, category: CATEGORY, prompt: "realistyczne wolumetryczne promienie światła, miękka gęstość" },
  { id: "hyper-atm-ambiente-047", title: "Delikatna wolumetria", summary: "Kino.", area: AREA, category: CATEGORY, prompt: "delikatna wolumetria, bez nadmiaru mgły, realizm" },
  { id: "hyper-atm-ambiente-048", title: "Atmosfera studyjna", summary: "Czysta.", area: AREA, category: CATEGORY, prompt: "czysta atmosfera studyjna, bez cząsteczek, komercyjny look" },
  { id: "hyper-atm-ambiente-049", title: "Atmosfera backstage", summary: "Ciepła.", area: AREA, category: CATEGORY, prompt: "realistyczny backstage: praktyczne światło, powietrze lekko ciężkie" },
  { id: "hyper-atm-ambiente-050", title: "Atmosfera uliczna", summary: "Prawdziwa.", area: AREA, category: CATEGORY, prompt: "realistyczna atmosfera uliczna, lekka naturalna mgiełka/zanieczyszczenie (haze)" },

  { id: "hyper-atm-ambiente-051", title: "Wilgoć na skórze", summary: "Prawdziwy połysk.", area: AREA, category: CATEGORY, prompt: "realistyczny połysk wilgoci na skórze, bez plastiku" },
  { id: "hyper-atm-ambiente-052", title: "Rosa", summary: "Małe krople.", area: AREA, category: CATEGORY, prompt: "rosa na liściach/powierzchniach, małe krople, realistyczne macro" },
  { id: "hyper-atm-ambiente-053", title: "Mikrokrople", summary: "Detal.", area: AREA, category: CATEGORY, prompt: "rozproszone mikrokrople, realistyczne napięcie powierzchniowe" },
  { id: "hyper-atm-ambiente-054", title: "Mokra powierzchnia", summary: "Specular.", area: AREA, category: CATEGORY, prompt: "realistyczna mokra powierzchnia, kontrolowane odbicie, widoczna tekstura" },
  { id: "hyper-atm-ambiente-055", title: "Zaparowana szyba", summary: "Chłodne wnętrze.", area: AREA, category: CATEGORY, prompt: "realistycznie zaparowana szyba, naturalna kondensacja" },
  { id: "hyper-atm-ambiente-056", title: "Widoczny oddech", summary: "Zimny klimat.", area: AREA, category: CATEGORY, prompt: "subtelnie widoczny oddech, zimny klimat, realistycznie" },
  { id: "hyper-atm-ambiente-057", title: "Popiół w powietrzu", summary: "Bez apokalipsy.", area: AREA, category: CATEGORY, prompt: "lekki popiół w powietrzu, drobne cząsteczki, realistycznie" },
  { id: "hyper-atm-ambiente-058", title: "Lekkie iskry", summary: "Warsztat.", area: AREA, category: CATEGORY, prompt: "lekkie iskry warsztatowe, realistyczna ekspozycja, bez fajerwerków" },
  { id: "hyper-atm-ambiente-059", title: "Dym przemysłowy", summary: "Delikatny.", area: AREA, category: CATEGORY, prompt: "delikatny i wiarygodny dym przemysłowy, bez niemożliwej gęstości" },
  { id: "hyper-atm-ambiente-060", title: "Para z jedzenia", summary: "Apetyt.", area: AREA, category: CATEGORY, prompt: "subtelna para unosząca się z jedzenia, realistyczna, bez przesady" },

  { id: "hyper-atm-ambiente-061", title: "Świąteczny bokeh (realny)", summary: "Ciepłe światła.", area: AREA, category: CATEGORY, prompt: "realistyczny bokeh ciepłych świateł, bez powtarzalnych kształtów" },
  { id: "hyper-atm-ambiente-062", title: "Festiwal (naturalnie)", summary: "Miękkie światła.", area: AREA, category: CATEGORY, prompt: "realistyczne światła festiwalowe, poprawna ekspozycja, bez ostrego neonu" },
  { id: "hyper-atm-ambiente-063", title: "Światło praktyczne (lampka)", summary: "Wnętrze.", area: AREA, category: CATEGORY, prompt: "światło praktyczne (lampka) oświetlające scenę, spójne cienie" },
  { id: "hyper-atm-ambiente-064", title: "Rozproszone światło z okna", summary: "Miękkie światło dzienne.", area: AREA, category: CATEGORY, prompt: "rozproszone światło z okna, naturalna atmosfera, miękki kontrast" },
  { id: "hyper-atm-ambiente-065", title: "Promień słońca", summary: "Zasłona.", area: AREA, category: CATEGORY, prompt: "wpadający promień słońca, subtelny kurz, realistyczny look" },
  { id: "hyper-atm-ambiente-066", title: "Cienie żaluzji", summary: "Wnętrze.", area: AREA, category: CATEGORY, prompt: "realistyczne cienie żaluzji, miękki wzór, nieidealny" },
  { id: "hyper-atm-ambiente-067", title: "Odbicie wody", summary: "Basen.", area: AREA, category: CATEGORY, prompt: "rzucane odbicie wody, miękkie realistyczne kaustyki" },
  { id: "hyper-atm-ambiente-068", title: "Miękkie kaustyki", summary: "Prawdziwa woda.", area: AREA, category: CATEGORY, prompt: "miękkie realistyczne kaustyki (woda), bez sztucznego wzoru" },
  { id: "hyper-atm-ambiente-069", title: "Leśna atmosfera", summary: "Wilgotno.", area: AREA, category: CATEGORY, prompt: "wilgotny las z lekką mgiełką, naturalne kolory" },
  { id: "hyper-atm-ambiente-070", title: "Chłodne góry", summary: "Rzadkie powietrze.", area: AREA, category: CATEGORY, prompt: "chłodne górskie powietrze, naturalna ostrość, minimalna mgiełka" },

  { id: "hyper-atm-ambiente-071", title: "Miasto po deszczu", summary: "Odbicia.", area: AREA, category: CATEGORY, prompt: "miasto po deszczu, odbicia na asfalcie, realistycznie" },
  { id: "hyper-atm-ambiente-072", title: "Mokra droga", summary: "Noc.", area: AREA, category: CATEGORY, prompt: "mokra droga, realistyczne odbicia świateł reflektorów, bez przesadzonego neonu" },
  { id: "hyper-atm-ambiente-073", title: "Wnętrze z lekkim dymem", summary: "Kino.", area: AREA, category: CATEGORY, prompt: "wnętrze z bardzo lekką mgiełką (haze), miękkie promienie, realistycznie" },
  { id: "hyper-atm-ambiente-074", title: "Warsztat z kurzem", summary: "Industrial.", area: AREA, category: CATEGORY, prompt: "warsztat z kurzem w powietrzu, światło boczne, prawdziwa tekstura" },
  { id: "hyper-atm-ambiente-075", title: "Kuchnia z parą", summary: "Food.", area: AREA, category: CATEGORY, prompt: "kuchnia z parą znad dania, realistyczna wilgoć" },
  { id: "hyper-atm-ambiente-076", title: "Kawiarnia z parą", summary: "Kawa.", area: AREA, category: CATEGORY, prompt: "realistyczna para z kawy, ciepła atmosfera, bez przesady" },
  { id: "hyper-atm-ambiente-077", title: "Para na oknie", summary: "Zima.", area: AREA, category: CATEGORY, prompt: "para na oknie od środka, naturalna kondensacja, realistyczny detal" },
  { id: "hyper-atm-ambiente-078", title: "Mgła na drodze", summary: "Mood.", area: AREA, category: CATEGORY, prompt: "mgła na drodze, rozproszone reflektory, realistyczna głębia" },
  { id: "hyper-atm-ambiente-079", title: "Deszcz pod światło", summary: "Krople.", area: AREA, category: CATEGORY, prompt: "deszcz pod światło, widoczne krople, realistyczna ekspozycja" },
  { id: "hyper-atm-ambiente-080", title: "Śnieg pod światło", summary: "Płatki.", area: AREA, category: CATEGORY, prompt: "śnieg pod światło, widoczne płatki, realistycznie chłodne otoczenie" },

  { id: "hyper-atm-ambiente-081", title: "Minimalistyczne otoczenie", summary: "Bez rozpraszaczy.", area: AREA, category: CATEGORY, prompt: "minimalistyczne otoczenie, czyste powietrze, bez dodatkowych elementów" },
  { id: "hyper-atm-ambiente-082", title: "Intymny klimat", summary: "Blisko.", area: AREA, category: CATEGORY, prompt: "intymny klimat, miękkie światło, realistycznie spokojna atmosfera" },
  { id: "hyper-atm-ambiente-083", title: "Napięty klimat", summary: "Realistyczny dramat.", area: AREA, category: CATEGORY, prompt: "napięty klimat, umiarkowany kontrast, wiarygodna atmosfera" },
  { id: "hyper-atm-ambiente-084", title: "Radosny klimat", summary: "Jasno.", area: AREA, category: CATEGORY, prompt: "radosny klimat, naturalne światło, czyste kolory bez przesycenia" },
  { id: "hyper-atm-ambiente-085", title: "Nostalgiczny klimat", summary: "Lekki film.", area: AREA, category: CATEGORY, prompt: "nostalgiczny klimat, miękkie tony, subtelne ziarno (jeśli dotyczy)" },
  { id: "hyper-atm-ambiente-086", title: "Klimat nad ranem", summary: "Cisza.", area: AREA, category: CATEGORY, prompt: "realistyczny środek nocy/nad ranem, minimalne światło, spokojna atmosfera" },
  { id: "hyper-atm-ambiente-087", title: "Klimat popołudnia", summary: "Normalnie.", area: AREA, category: CATEGORY, prompt: "naturalne popołudnie, stabilne światło, realistyczna neutralna atmosfera" },
  { id: "hyper-atm-ambiente-088", title: "Klimat biura", summary: "Praktycznie.", area: AREA, category: CATEGORY, prompt: "realistyczne biuro, kontrolowane światło mieszane, bez dziwnej zieleni" },
  { id: "hyper-atm-ambiente-089", title: "Klimat siłowni", summary: "Prawdziwy pot.", area: AREA, category: CATEGORY, prompt: "realistyczna siłownia, subtelna wilgoć/pot, ciepłe powietrze" },
  { id: "hyper-atm-ambiente-090", title: "Klimat ulicy", summary: "Kontrolowany wizualny szum.", area: AREA, category: CATEGORY, prompt: "realistyczna ulica z życiem, lekka mgiełka (haze), bez sztucznego chaosu" },

  { id: "hyper-atm-ambiente-091", title: "Bez przesadzonych cząsteczek", summary: "Unikaj fantazji.", area: AREA, category: CATEGORY, prompt: "bez przesadzonych cząsteczek, wszystko subtelne i fotograficzne" },
  { id: "hyper-atm-ambiente-092", title: "Bez dymu scenicznego", summary: "Nie koncert.", area: AREA, category: CATEGORY, prompt: "unikać dymu typu scena, zachować naturalne rozproszenie" },
  { id: "hyper-atm-ambiente-093", title: "Bez sztucznej wolumetrii", summary: "Realnie.", area: AREA, category: CATEGORY, prompt: "unikać sztucznej wolumetrii, niska i spójna gęstość" },
  { id: "hyper-atm-ambiente-094", title: "Bez cyberpunkowego neonu", summary: "Bez karykatury.", area: AREA, category: CATEGORY, prompt: "unikać przesadzonego cyberpunkowego neonu, zachować realistyczne światło" },
  { id: "hyper-atm-ambiente-095", title: "Realny detal atmosferyczny", summary: "Finisz.", area: AREA, category: CATEGORY, prompt: "realistyczny detal atmosferyczny, poczucie autentycznego miejsca" },
  { id: "hyper-atm-ambiente-096", title: "Głębia atmosferyczna", summary: "Dystans.", area: AREA, category: CATEGORY, prompt: "głębia atmosferyczna w oddali, ton i kontrast stopniowo maleją" },
  { id: "hyper-atm-ambiente-097", title: "Perspektywa z mgiełką", summary: "Miękko w oddali.", area: AREA, category: CATEGORY, prompt: "odległe elementy zmiękczone przez atmosferę, realistycznie" },
  { id: "hyper-atm-ambiente-098", title: "Wilgotny miejski klimat", summary: "Miasto.", area: AREA, category: CATEGORY, prompt: "wilgotny miejski klimat, subtelne odbicia, ciężkie powietrze" },
  { id: "hyper-atm-ambiente-099", title: "Chłodny suchy klimat", summary: "Przejrzystość.", area: AREA, category: CATEGORY, prompt: "chłodny suchy klimat, wyraziste powietrze, czyste cienie" },
  { id: "hyper-atm-ambiente-100", title: "Ciepły wilgotny klimat", summary: "Tropiki.", area: AREA, category: CATEGORY, prompt: "ciepły wilgotny klimat, miękka mgiełka, subtelna kondensacja" },
];
