// src/lib/prompts/hyperrealism-text/base.js
// Unikalny obszar i kategoria dla CAŁEGO tego pliku:
const AREA = "Baza";
const CATEGORY = "Fundamenty";

export const hyperrealismTextPromptsBase = [
  {
    id: "hyper-base-fundamentos-001",
    title: "Realna mikrostruktura",
    summary: "Dodaje mikrodetale i wiarygodne niedoskonałości.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne mikrostruktury, naturalne niedoskonałości, drobny detal bez efektu CGI",
  },
  {
    id: "hyper-base-fundamentos-002",
    title: "Skóra bez plastiku",
    summary: "Unikaj woskowego efektu.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna skóra z porami i drobnym meszkiem, bez beauty wygładzania, bez porcelanowej skóry",
  },
  {
    id: "hyper-base-fundamentos-003",
    title: "Naturalny kolor",
    summary: "Wiarygodne tony.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalny color grading, poprawne tony skóry, bez nadmiernej saturacji, bez agresywnego HDR",
  },
  {
    id: "hyper-base-fundamentos-004",
    title: "Realistyczny kontrast",
    summary: "Bez sztucznego wyglądu.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczny kontrast, miękkie cienie, kontrolowane światła, bez nadmiernego przetwarzania",
  },
  {
    id: "hyper-base-fundamentos-005",
    title: "Zrównoważona ostrość",
    summary: "Detal bez przesadnego wyostrzania.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalna ostrość, drobny detal, bez twardych krawędzi, bez oversharpeningu",
  },
  {
    id: "hyper-base-fundamentos-006",
    title: "Subtelne ziarno",
    summary: "Fotograficzne wrażenie.",
    area: AREA,
    category: CATEGORY,
    prompt: "bardzo subtelne ziarno filmowe, organiczna tekstura, bez agresywnego cyfrowego szumu",
  },
  {
    id: "hyper-base-fundamentos-007",
    title: "Subtelne niedoskonałości",
    summary: "Codzienny realizm.",
    area: AREA,
    category: CATEGORY,
    prompt: "drobne niedoskonałości, subtelny kurz, minimalne ślady, nic idealnego",
  },
  {
    id: "hyper-base-fundamentos-008",
    title: "Realna głębia",
    summary: "Naturalna separacja planów.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna głębia ostrości, naturalna separacja obiektu od tła, bez dziwnych wycięć",
  },
  {
    id: "hyper-base-fundamentos-009",
    title: "Wiarygodny bokeh",
    summary: "Naturalne rozmycie.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczny bokeh, naturalny blur, bez dziwnych plam i halo",
  },
  {
    id: "hyper-base-fundamentos-010",
    title: "Poprawne cienie",
    summary: "Cienie z realnym spadkiem.",
    area: AREA,
    category: CATEGORY,
    prompt: "cienie spójne ze światłem, miękki spadek, bez unoszących się cieni",
  },
  {
    id: "hyper-base-fundamentos-011",
    title: "Fizyczne odbicia",
    summary: "Wiarygodne refleksy.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne odbicia zależne od materiału, bez niemożliwych połysków, bez przepalonych highlightów",
  },
  {
    id: "hyper-base-fundamentos-012",
    title: "Realne materiały",
    summary: "Unikaj idealnych powierzchni.",
    area: AREA,
    category: CATEGORY,
    prompt: "materiały z wariacją, mikro-rysy, subtelne zużycie, realizm fizyczny",
  },
  {
    id: "hyper-base-fundamentos-013",
    title: "Spójna perspektywa",
    summary: "Nic krzywego/nierealnego.",
    area: AREA,
    category: CATEGORY,
    prompt: "spójna perspektywa, poprawne proporcje, bez dziwnych deformacji",
  },
  {
    id: "hyper-base-fundamentos-014",
    title: "Ludzka skala",
    summary: "Realne proporcje.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna skala, spójne rozmiary obiektów, bez przypadkowego ‘gigantyzmu’",
  },
  {
    id: "hyper-base-fundamentos-015",
    title: "Bez AI-face",
    summary: "Naturalne twarze.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalna twarz, spójne rysy, bez ‘AI face’, bez idealnej symetrii",
  },
  {
    id: "hyper-base-fundamentos-016",
    title: "Wiarygodne oczy",
    summary: "Realny refleks i fokus.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne oczy, spójny catchlight, bez fałszywego połysku, bez oczu lalki",
  },
  {
    id: "hyper-base-fundamentos-017",
    title: "Poprawne dłonie",
    summary: "Unikaj dodatkowych palców.",
    area: AREA,
    category: CATEGORY,
    prompt: "anatomiczne dłonie, 5 palców, naturalne paznokcie, bez deformacji",
  },
  {
    id: "hyper-base-fundamentos-018",
    title: "Tekstura tkaniny",
    summary: "Widoczne włókna.",
    area: AREA,
    category: CATEGORY,
    prompt: "tkanina z widocznym splotem, naturalne fałdy, realistyczne szwy",
  },
  {
    id: "hyper-base-fundamentos-019",
    title: "Realne włosy",
    summary: "Włosy z wariacją.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne włosy, pasma z wariacją, bez jednolitej bryły, bez plastiku",
  },
  {
    id: "hyper-base-fundamentos-020",
    title: "Skóra + światło",
    summary: "Subtelny subsurface.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny subsurface scattering (realny), żywe tony skóry, bez wosku",
  },
  {
    id: "hyper-base-fundamentos-021",
    title: "Spójne tło",
    summary: "Bez losowości.",
    area: AREA,
    category: CATEGORY,
    prompt: "tło spójne ze sceną, bez losowych elementów, bez artefaktów",
  },
  {
    id: "hyper-base-fundamentos-022",
    title: "Detale otoczenia",
    summary: "Autentyczny klimat.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelne detale środowiska (kurz, zużycie, ślady), codzienny realizm",
  },
  {
    id: "hyper-base-fundamentos-023",
    title: "Bez duplikacji",
    summary: "Unikaj klonów.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez duplikacji, bez powtarzających się obiektów, bez sklonowanych wzorów",
  },
  {
    id: "hyper-base-fundamentos-024",
    title: "Czyste krawędzie",
    summary: "Bez artefaktów na konturach.",
    area: AREA,
    category: CATEGORY,
    prompt: "czyste kontury, bez halo, bez drżących krawędzi, bez warping",
  },
  {
    id: "hyper-base-fundamentos-025",
    title: "Bez dziwnego tekstu",
    summary: "Unikaj zdeformowanych liter.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez tekstu, bez zdeformowanej typografii, bez uszkodzonych logotypów",
  },
  {
    id: "hyper-base-fundamentos-026",
    title: "Realizm ‘prawdziwej kamery’",
    summary: "Fotograficzny look.",
    area: AREA,
    category: CATEGORY,
    prompt: "look prawdziwej fotografii, żadnego renderu, żadnej ilustracji, czysto fotograficzny styl",
  },
  {
    id: "hyper-base-fundamentos-027",
    title: "Miękkie highlighty",
    summary: "Kontrolowane światła.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie highlighty, naturalny roll-off, bez twardego clippingu",
  },
  {
    id: "hyper-base-fundamentos-028",
    title: "Cienie z detalem",
    summary: "Bez zlanego czarnego.",
    area: AREA,
    category: CATEGORY,
    prompt: "cienie z detalem, czernie niezalane, realistyczny zakres dynamiczny",
  },
  {
    id: "hyper-base-fundamentos-029",
    title: "Jednolity kolor",
    summary: "Unikaj dziwnych dominant.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalny balans bieli, bez dziwnej dominanty zielonej/magenty",
  },
  {
    id: "hyper-base-fundamentos-030",
    title: "Bez ‘beauty skin’",
    summary: "Bez filtra z apki.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez filtra beauty, bez ekstremalnego wygładzania, zachowana realna tekstura",
  },
  {
    id: "hyper-base-fundamentos-031",
    title: "Detal na metalu",
    summary: "Wiarygodny metal.",
    area: AREA,
    category: CATEGORY,
    prompt: "metal z mikro-rysami, fizyczne odbicie, realistyczna chropowatość (roughness)",
  },
  {
    id: "hyper-base-fundamentos-032",
    title: "Detal na szkle",
    summary: "Prawdziwe szkło.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne szkło, spójna minimalna deformacja, poprawne odbicie i przezroczystość",
  },
  {
    id: "hyper-base-fundamentos-033",
    title: "Detal na plastiku",
    summary: "Plastik nie ‘zabawka’.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczny plastik (nie zabawkowy), mikro-rysy, kontrolowany połysk",
  },
  {
    id: "hyper-base-fundamentos-034",
    title: "Detal na drewnie",
    summary: "Realne słoje.",
    area: AREA,
    category: CATEGORY,
    prompt: "drewno z naturalnym usłojeniem, widoczne pory, niedoskonałości i subtelne zużycie",
  },
  {
    id: "hyper-base-fundamentos-035",
    title: "Detal na kamieniu",
    summary: "Pory i ziarno.",
    area: AREA,
    category: CATEGORY,
    prompt: "kamień z realnym ziarnem, pory, nieregularności, bez powtarzalnego wzoru",
  },
  {
    id: "hyper-base-fundamentos-036",
    title: "Detal na papierze",
    summary: "Widoczne włókna.",
    area: AREA,
    category: CATEGORY,
    prompt: "papier z widocznymi włóknami, naturalne krawędzie, realistyczna tekstura",
  },
  {
    id: "hyper-base-fundamentos-037",
    title: "Detal na skórze (leather)",
    summary: "Pory i zagniecenia.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna skóra (leather) z porami, subtelne zmarszczki, naturalny połysk",
  },
  {
    id: "hyper-base-fundamentos-038",
    title: "Detal na ceramice",
    summary: "Prawdziwe szkliwo.",
    area: AREA,
    category: CATEGORY,
    prompt: "ceramika z realnym szkliwem, mikro niedoskonałości, miękkie odbicie",
  },
  {
    id: "hyper-base-fundamentos-039",
    title: "Detal na sierści zwierzęcia",
    summary: "Realne futro/pióra.",
    area: AREA,
    category: CATEGORY,
    prompt: "sierść/pióra z naturalną wariacją, bez efektu dywanu, poprawna anatomia",
  },
  {
    id: "hyper-base-fundamentos-040",
    title: "Lekki ruch",
    summary: "Bardziej realnie.",
    area: AREA,
    category: CATEGORY,
    prompt: "lekka niedoskonałość ujęcia, naturalność, zero sztucznej sztywności",
  },
  {
    id: "hyper-base-fundamentos-041",
    title: "Zero ‘spolerowania’",
    summary: "Unikaj gładkich powierzchni.",
    area: AREA,
    category: CATEGORY,
    prompt: "unikać spolerowanych/plastikowych powierzchni, zachować organiczną realistyczną teksturę",
  },
  {
    id: "hyper-base-fundamentos-042",
    title: "Kontrolowany szum",
    summary: "Bez brzydkiego noise.",
    area: AREA,
    category: CATEGORY,
    prompt: "minimalny, organiczny szum, bez artefaktów kompresji",
  },
  {
    id: "hyper-base-fundamentos-043",
    title: "Naturalne zróżnicowanie skóry",
    summary: "Zmienność tonu.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalne zróżnicowanie tonu skóry (subtelne zaczerwienienia, cienie), nic jednolitego",
  },
  {
    id: "hyper-base-fundamentos-044",
    title: "Bez plastikowych włosów",
    summary: "Prawdziwe włosy.",
    area: AREA,
    category: CATEGORY,
    prompt: "włosy bez efektu plastiku, separacja pasm, realistyczny połysk",
  },
  {
    id: "hyper-base-fundamentos-045",
    title: "Tła bez ‘AI mush’",
    summary: "Unikaj stopionej tekstury.",
    area: AREA,
    category: CATEGORY,
    prompt: "tło ostre tam, gdzie trzeba, bez ‘mush’, bez stopionych detali",
  },
  {
    id: "hyper-base-fundamentos-046",
    title: "Detale na krawędziach",
    summary: "Nic dziwnego w sylwetkach.",
    area: AREA,
    category: CATEGORY,
    prompt: "czyste sylwetki, bez podwójnego konturu, bez fałszywego wycięcia",
  },
  {
    id: "hyper-base-fundamentos-047",
    title: "Realizm kurzu",
    summary: "Subtelny kurz.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny kurz na powierzchniach, realistyczne mikrocząsteczki, bez przesady",
  },
  {
    id: "hyper-base-fundamentos-048",
    title: "Realizm zużycia",
    summary: "Prawdziwe użytkowanie.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelne ślady zużycia, realistyczne użytkowanie, małe autentyczne rysy",
  },
  {
    id: "hyper-base-fundamentos-049",
    title: "Bez ‘shiny skin’",
    summary: "Poprawny połysk.",
    area: AREA,
    category: CATEGORY,
    prompt: "kontrolowany połysk skóry, realistyczna strefa T, bez przesadnego tłuszczu",
  },
  {
    id: "hyper-base-fundamentos-050",
    title: "Ostrość na obiekcie",
    summary: "Poprawny focus.",
    area: AREA,
    category: CATEGORY,
    prompt: "obiekt ostry, spójny fokus, bez dziwnego selektywnego rozmycia",
  },

  // 50 WIĘCEJ (krótkie, gotowe do wklejenia)
  {
    id: "hyper-base-fundamentos-051",
    title: "Unikaj render look",
    summary: "Bezpośrednie negatywy.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez CGI, bez renderu 3D, bez ilustracji, bez stylu cartoon/anime",
  },
  {
    id: "hyper-base-fundamentos-052",
    title: "Unikaj dziwnej geometrii",
    summary: "Zdrowe proporcje.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez deformacji, bez krzywych obiektów, bez niemożliwej geometrii",
  },
  {
    id: "hyper-base-fundamentos-053",
    title: "Widoczne drobne detale",
    summary: "Mikrodetal.",
    area: AREA,
    category: CATEGORY,
    prompt: "widoczny mikrodetal, ostre tekstury, bez smudge",
  },
  {
    id: "hyper-base-fundamentos-054",
    title: "Cienie osadzone",
    summary: "Nic nie lata.",
    area: AREA,
    category: CATEGORY,
    prompt: "cień kontaktowy, obiekt nie unosi się, wiarygodne podparcie",
  },
  {
    id: "hyper-base-fundamentos-055",
    title: "Bez sztucznego połysku",
    summary: "Prawdziwy blask.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez plastikowego połysku, realistyczny specular zależny od materiału",
  },
  {
    id: "hyper-base-fundamentos-056",
    title: "Tekstury bez powtórzeń",
    summary: "Unikaj tilingu.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez powtarzania tekstur, bez sklonowanych wzorów (tiling)",
  },
  {
    id: "hyper-base-fundamentos-057",
    title: "Detale krawędzi",
    summary: "Realny kontur.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalne krawędzie, drobne nieregularności, nic idealnego",
  },
  {
    id: "hyper-base-fundamentos-058",
    title: "Realistyczna chroma",
    summary: "Nic radioaktywnego.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne kolory, nic fluorescencyjnego bez powodu, umiarkowana saturacja",
  },
  {
    id: "hyper-base-fundamentos-059",
    title: "Skóra z teksturą",
    summary: "Naturalność.",
    area: AREA,
    category: CATEGORY,
    prompt: "widoczne pory, mikrozmarszczki, naturalna tekstura, bez airbrush",
  },
  {
    id: "hyper-base-fundamentos-060",
    title: "Proste linie są proste",
    summary: "Architektura.",
    area: AREA,
    category: CATEGORY,
    prompt: "spójne proste linie, bez warping, bez zepsutej perspektywy",
  },
  {
    id: "hyper-base-fundamentos-061",
    title: "Detal w cieniach",
    summary: "Realny zakres.",
    area: AREA,
    category: CATEGORY,
    prompt: "detal w cieniach, naturalny zakres dynamiczny, bez zablokowanych czerni",
  },
  {
    id: "hyper-base-fundamentos-062",
    title: "Detal w światłach",
    summary: "Roll-off.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękki roll-off w światłach, bez twardych przepaleń",
  },
  {
    id: "hyper-base-fundamentos-063",
    title: "Bez dziwnych oczu",
    summary: "Unikaj uncanny.",
    area: AREA,
    category: CATEGORY,
    prompt: "unikać rozjechanych oczu, dziwnych źrenic, fałszywego połysku, uncanny spojrzenia",
  },
  {
    id: "hyper-base-fundamentos-064",
    title: "Bez dziwnych zębów",
    summary: "Normalne usta.",
    area: AREA,
    category: CATEGORY,
    prompt: "normalne zęby, naturalne dziąsła, bez deformacji ust",
  },
  {
    id: "hyper-base-fundamentos-065",
    title: "Bez jednolitej skóry",
    summary: "Zmienność tonu.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelna zmienność tonu skóry, bez sztucznej jednolitości",
  },
  {
    id: "hyper-base-fundamentos-066",
    title: "Mikroporowatość materiałów",
    summary: "Realny materiał.",
    area: AREA,
    category: CATEGORY,
    prompt: "mikroporowatość materiałów, realistyczna chropowatość, kontrolowany specular",
  },
  {
    id: "hyper-base-fundamentos-067",
    title: "Bez halo",
    summary: "Czyste krawędzie.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez halo wokół obiektu, bez sztucznego glow",
  },
  {
    id: "hyper-base-fundamentos-068",
    title: "Bez nadwyostrzania",
    summary: "Naturalnie.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez sztucznego wyostrzenia, bez przesadnego sharpen, naturalny detal",
  },
  {
    id: "hyper-base-fundamentos-069",
    title: "Bez ekstremalnego wygładzania",
    summary: "Unikaj beauty blur.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez beauty blur, bez skóry lalki, zachowana tekstura",
  },
  {
    id: "hyper-base-fundamentos-070",
    title: "Zero artefaktów",
    summary: "Czystość.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez artefaktów, bez glitch, bez smear, bez zniekształceń",
  },
  {
    id: "hyper-base-fundamentos-071",
    title: "Realizm otoczenia",
    summary: "Prawdziwa atmosfera.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna atmosfera, mikro mgiełka jeśli pasuje, nic fantazyjnego",
  },
  {
    id: "hyper-base-fundamentos-072",
    title: "Głębia planów",
    summary: "Realne warstwy.",
    area: AREA,
    category: CATEGORY,
    prompt: "czytelny pierwszy/drugi/tylny plan, naturalna głębia",
  },
  {
    id: "hyper-base-fundamentos-073",
    title: "Tekstura powierzchni",
    summary: "Bez idealnych powierzchni.",
    area: AREA,
    category: CATEGORY,
    prompt: "powierzchnie nie są idealne, drobne nieregularności, realizm fizyczny",
  },
  {
    id: "hyper-base-fundamentos-074",
    title: "Unikaj idealnej symetrii",
    summary: "Bardziej ludzko.",
    area: AREA,
    category: CATEGORY,
    prompt: "unikać idealnej symetrii, drobne naturalne różnice",
  },
  {
    id: "hyper-base-fundamentos-075",
    title: "Realistyczne krawędzie",
    summary: "Detale na brzegach.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelne zużycie krawędzi (edge wear), minimalne przetarcia, realizm",
  },
  {
    id: "hyper-base-fundamentos-076",
    title: "Bez ‘stopionej’ tekstury",
    summary: "Unikaj mush.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez ‘stopionych’ tekstur, bez niespójnie rozmytych detali",
  },
  {
    id: "hyper-base-fundamentos-077",
    title: "Bez duplikowania akcesoriów",
    summary: "Unikaj klonów.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez zduplikowanych akcesoriów, bez powtarzalnych obiektów, bez dziwnej symetrii",
  },
  {
    id: "hyper-base-fundamentos-078",
    title: "Unikaj dodatkowych palców",
    summary: "Negatyw wprost.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez dodatkowych palców, bez zdeformowanych dłoni, poprawna anatomia",
  },
  {
    id: "hyper-base-fundamentos-079",
    title: "Unikaj dziwnej anatomii",
    summary: "Realne ciało.",
    area: AREA,
    category: CATEGORY,
    prompt: "poprawna anatomia człowieka, realistyczne proporcje, bez deformacji",
  },
  {
    id: "hyper-base-fundamentos-080",
    title: "Naturalna ogniskowa",
    summary: "Bez ekstremalnych zniekształceń.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez ekstremalnych zniekształceń, bez fish-eye, naturalna perspektywa",
  },
  {
    id: "hyper-base-fundamentos-081",
    title: "Miękki cień studyjny",
    summary: "Do produktu/portretu.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękki cień studyjny, czysty gradient, bez wycięć",
  },
  {
    id: "hyper-base-fundamentos-082",
    title: "Detal mokrej powierzchni",
    summary: "Realna wilgoć.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna wilgoć, mikrokrople, miękkie odbicia, bez plastiku",
  },
  {
    id: "hyper-base-fundamentos-083",
    title: "Kurz w promieniu światła",
    summary: "Subtelne promienie.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelne cząsteczki w powietrzu przy kontraświetle, bardzo naturalnie",
  },
  {
    id: "hyper-base-fundamentos-084",
    title: "Bez filtrów",
    summary: "Bez instagram look.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez filtrów, bez looku z apki, prawdziwa fotografia",
  },
  {
    id: "hyper-base-fundamentos-085",
    title: "Bez glow",
    summary: "Nic magicznego.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez sztucznego glow, bez przesadnego bloom",
  },
  {
    id: "hyper-base-fundamentos-086",
    title: "Detale na krawędziach ubrań",
    summary: "Szwy i włókna.",
    area: AREA,
    category: CATEGORY,
    prompt: "widoczne szwy, subtelne włókna, naturalne fałdy",
  },
  {
    id: "hyper-base-fundamentos-087",
    title: "Detale skóry na ustach",
    summary: "Prawdziwe usta.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna tekstura ust, bez idealnej pomadki, naturalny detal",
  },
  {
    id: "hyper-base-fundamentos-088",
    title: "Detale brwi",
    summary: "Pojedyncze włoski.",
    area: AREA,
    category: CATEGORY,
    prompt: "brwi z pojedynczymi włoskami, naturalna gęstość, bez jednolitej plamy",
  },
  {
    id: "hyper-base-fundamentos-089",
    title: "Detale rzęs",
    summary: "Bez pędzla.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalne rzęsy, nieidealne, bez efektu ‘malowanego’",
  },
  {
    id: "hyper-base-fundamentos-090",
    title: "Detale skóry na nosie",
    summary: "Realne pory.",
    area: AREA,
    category: CATEGORY,
    prompt: "pory na nosie i policzkach widoczne, realistyczne, bez przesady",
  },
  {
    id: "hyper-base-fundamentos-091",
    title: "Detale biżuterii",
    summary: "Realny metal/kamień.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna biżuteria, mikro-rysy, kontrolowane błyski, bez fałszywego blasku",
  },
  {
    id: "hyper-base-fundamentos-092",
    title: "Cień kontaktowy (detal)",
    summary: "Osadza obiekt.",
    area: AREA,
    category: CATEGORY,
    prompt: "widoczny cień kontaktowy, obiekt osadzony, bez unoszenia",
  },
  {
    id: "hyper-base-fundamentos-093",
    title: "Detale tekstury skóry",
    summary: "Pory i meszek.",
    area: AREA,
    category: CATEGORY,
    prompt: "pory + drobny meszek, naturalna tekstura, bez wosku, bez blur",
  },
  {
    id: "hyper-base-fundamentos-094",
    title: "Realny detal oka",
    summary: "Naturalna tęczówka.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna tęczówka, naturalny wzór, bez połysku jak z gry",
  },
  {
    id: "hyper-base-fundamentos-095",
    title: "Realne tło",
    summary: "Tło bez błędów.",
    area: AREA,
    category: CATEGORY,
    prompt: "logiczne i czyste tło, bez mutujących obiektów, bez niespójnych detali",
  },
  {
    id: "hyper-base-fundamentos-096",
    title: "Realizm bez przesady",
    summary: "Wiarygodnie.",
    area: AREA,
    category: CATEGORY,
    prompt: "wiarygodny realizm, nic ekstremalnego, nic nierealnego, naturalne foto",
  },
  {
    id: "hyper-base-fundamentos-097",
    title: "Unikaj ‘woskowej’ skóry",
    summary: "Negatyw wprost.",
    area: AREA,
    category: CATEGORY,
    prompt: "unikać woskowej skóry, unikać wygładzania, zachować realną teksturę",
  },
  {
    id: "hyper-base-fundamentos-098",
    title: "Unikaj ‘malowanego’ looku",
    summary: "Bez artystycznego stylu.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez malarskiego wyglądu, bez pociągnięć pędzla, bez ilustracji, fotograficznie",
  },
  {
    id: "hyper-base-fundamentos-099",
    title: "Unikaj surrealu",
    summary: "Bez niemożliwych elementów.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez surrealizmu, bez niemożliwych elementów, bez absurdalnej anatomii",
  },
  {
    id: "hyper-base-fundamentos-100",
    title: "Negatywy pro (kompakt)",
    summary: "Krótki blok negatywów do wklejenia.",
    area: AREA,
    category: CATEGORY,
    prompt: "negatyw: CGI, render, cartoon, anime, plastic skin, deformed hands, extra fingers, bad text, artifacts",
  },
];
