// src/lib/prompts/hyperrealism-text/base.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Base";
const CATEGORY = "Fundamentos";

export const hyperrealismTextPromptsBase = [
  {
    id: "hyper-base-fundamentos-001",
    title: "Microtextura real",
    summary: "Añade microdetalle e imperfecciones creíbles.",
    area: AREA,
    category: CATEGORY,
    prompt: "microtexturas reales, imperfecciones naturales, detalle fino sin verse CGI",
  },
  {
    id: "hyper-base-fundamentos-002",
    title: "Piel sin plástico",
    summary: "Evita look encerado.",
    area: AREA,
    category: CATEGORY,
    prompt: "piel realista con poros y vello fino, sin suavizado beauty, sin piel de porcelana",
  },
  {
    id: "hyper-base-fundamentos-003",
    title: "Color natural",
    summary: "Tonos creíbles.",
    area: AREA,
    category: CATEGORY,
    prompt: "color grading natural, tonos piel correctos, sin saturación excesiva, sin HDR agresivo",
  },
  {
    id: "hyper-base-fundamentos-004",
    title: "Contraste real",
    summary: "Sin look artificial.",
    area: AREA,
    category: CATEGORY,
    prompt: "contraste realista, sombras suaves, altas luces controladas, sin sobreprocesado",
  },
  {
    id: "hyper-base-fundamentos-005",
    title: "Nitidez equilibrada",
    summary: "Detalle sin oversharpen.",
    area: AREA,
    category: CATEGORY,
    prompt: "nitidez natural, detalle fino, sin bordes duros, sin oversharpening",
  },
  {
    id: "hyper-base-fundamentos-006",
    title: "Grano sutil",
    summary: "Sensación fotográfica.",
    area: AREA,
    category: CATEGORY,
    prompt: "grano de película muy sutil, textura orgánica, no ruido digital agresivo",
  },
  {
    id: "hyper-base-fundamentos-007",
    title: "Subtle imperfections",
    summary: "Realismo cotidiano.",
    area: AREA,
    category: CATEGORY,
    prompt: "pequeñas imperfecciones, polvo sutil, marcas mínimas, nada perfecto",
  },
  {
    id: "hyper-base-fundamentos-008",
    title: "Profundidad real",
    summary: "Separación natural de planos.",
    area: AREA,
    category: CATEGORY,
    prompt: "profundidad de campo realista, separación sujeto-fondo natural, sin recortes raros",
  },
  {
    id: "hyper-base-fundamentos-009",
    title: "Bokeh creíble",
    summary: "Desenfoque natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "bokeh realista, blur natural, sin manchas extrañas ni halos",
  },
  {
    id: "hyper-base-fundamentos-010",
    title: "Sombras correctas",
    summary: "Sombras con caída real.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombras coherentes con la luz, caída suave, sin sombras flotantes",
  },
  {
    id: "hyper-base-fundamentos-011",
    title: "Reflejos físicos",
    summary: "Reflejos creíbles.",
    area: AREA,
    category: CATEGORY,
    prompt: "reflejos realistas según material, sin brillos imposibles, sin highlights quemados",
  },
  {
    id: "hyper-base-fundamentos-012",
    title: "Materiales reales",
    summary: "Evita superficies perfectas.",
    area: AREA,
    category: CATEGORY,
    prompt: "materiales con variación, micro-rayas, desgaste sutil, realismo físico",
  },
  {
    id: "hyper-base-fundamentos-013",
    title: "Perspectiva consistente",
    summary: "Nada torcido/irreal.",
    area: AREA,
    category: CATEGORY,
    prompt: "perspectiva coherente, proporciones correctas, sin deformaciones extrañas",
  },
  {
    id: "hyper-base-fundamentos-014",
    title: "Escala humana",
    summary: "Proporciones reales.",
    area: AREA,
    category: CATEGORY,
    prompt: "escala realista, tamaño coherente de objetos, sin gigantismo accidental",
  },
  {
    id: "hyper-base-fundamentos-015",
    title: "Sin AI-face",
    summary: "Rostros naturales.",
    area: AREA,
    category: CATEGORY,
    prompt: "rostro natural, rasgos coherentes, sin ‘AI face’, sin simetría perfecta",
  },
  {
    id: "hyper-base-fundamentos-016",
    title: "Ojos creíbles",
    summary: "Reflejo y enfoque real.",
    area: AREA,
    category: CATEGORY,
    prompt: "ojos realistas, catchlight coherente, sin brillo falso, sin ojos de muñeca",
  },
  {
    id: "hyper-base-fundamentos-017",
    title: "Manos correctas",
    summary: "Evita dedos extra.",
    area: AREA,
    category: CATEGORY,
    prompt: "manos anatómicas, 5 dedos, uñas naturales, sin deformaciones",
  },
  {
    id: "hyper-base-fundamentos-018",
    title: "Textura de tela",
    summary: "Fibra visible.",
    area: AREA,
    category: CATEGORY,
    prompt: "tela con trama visible, pliegues naturales, costuras realistas",
  },
  {
    id: "hyper-base-fundamentos-019",
    title: "Pelo real",
    summary: "Cabello con variación.",
    area: AREA,
    category: CATEGORY,
    prompt: "cabello realista, mechones con variación, sin bloque sólido, sin plástico",
  },
  {
    id: "hyper-base-fundamentos-020",
    title: "Piel + luz",
    summary: "Subsurface sutil.",
    area: AREA,
    category: CATEGORY,
    prompt: "subsurface scattering sutil (real), tonos piel vivos, sin cera",
  },
  {
    id: "hyper-base-fundamentos-021",
    title: "Fondo coherente",
    summary: "Nada random.",
    area: AREA,
    category: CATEGORY,
    prompt: "fondo coherente con escena, sin elementos aleatorios, sin artefactos",
  },
  {
    id: "hyper-base-fundamentos-022",
    title: "Detalles de entorno",
    summary: "Ambiente auténtico.",
    area: AREA,
    category: CATEGORY,
    prompt: "detalles ambientales sutiles (polvo, desgaste, huellas), realismo cotidiano",
  },
  {
    id: "hyper-base-fundamentos-023",
    title: "Sin duplicaciones",
    summary: "Evita clones.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin duplicaciones, sin objetos repetidos, sin patrones clonados",
  },
  {
    id: "hyper-base-fundamentos-024",
    title: "Bordes limpios",
    summary: "Sin artefactos en contornos.",
    area: AREA,
    category: CATEGORY,
    prompt: "contornos limpios, sin halos, sin bordes temblorosos, sin warping",
  },
  {
    id: "hyper-base-fundamentos-025",
    title: "Sin texto raro",
    summary: "Evita letras deformes.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin texto, sin tipografías deformes, sin logotipos corruptos",
  },
  {
    id: "hyper-base-fundamentos-026",
    title: "Realismo “cámara real”",
    summary: "Look fotográfico.",
    area: AREA,
    category: CATEGORY,
    prompt: "look de fotografía real, nada render, nada ilustración, estilo fotográfico puro",
  },
  {
    id: "hyper-base-fundamentos-027",
    title: "Highlights suaves",
    summary: "Altas luces controladas.",
    area: AREA,
    category: CATEGORY,
    prompt: "highlights suaves, roll-off natural, sin clipping duro",
  },
  {
    id: "hyper-base-fundamentos-028",
    title: "Sombras con detalle",
    summary: "No negros empastados.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombras con detalle, negros no empastados, rango dinámico realista",
  },
  {
    id: "hyper-base-fundamentos-029",
    title: "Color uniforme",
    summary: "Evita dominantes raras.",
    area: AREA,
    category: CATEGORY,
    prompt: "balance de blancos natural, sin dominante verde/magenta extraña",
  },
  {
    id: "hyper-base-fundamentos-030",
    title: "Sin piel “beauty”",
    summary: "No filtro de app.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin filtro beauty, sin suavizado extremo, textura real preservada",
  },
  {
    id: "hyper-base-fundamentos-031",
    title: "Detalle en metal",
    summary: "Metal creíble.",
    area: AREA,
    category: CATEGORY,
    prompt: "metal con micro-rayas, reflejo físico, roughness realista",
  },
  {
    id: "hyper-base-fundamentos-032",
    title: "Detalle en vidrio",
    summary: "Vidrio real.",
    area: AREA,
    category: CATEGORY,
    prompt: "vidrio realista, distorsión mínima coherente, reflejo y transparencia correctos",
  },
  {
    id: "hyper-base-fundamentos-033",
    title: "Detalle en plástico",
    summary: "Plástico no ‘toy’.",
    area: AREA,
    category: CATEGORY,
    prompt: "plástico realista (no juguete), micro-rayas, brillo controlado",
  },
  {
    id: "hyper-base-fundamentos-034",
    title: "Detalle en madera",
    summary: "Vetas reales.",
    area: AREA,
    category: CATEGORY,
    prompt: "madera con veta natural, poros visibles, imperfecciones y desgaste sutil",
  },
  {
    id: "hyper-base-fundamentos-035",
    title: "Detalle en piedra",
    summary: "Poro y grano.",
    area: AREA,
    category: CATEGORY,
    prompt: "piedra con grano real, poros, irregularidades, sin patrón repetido",
  },
  {
    id: "hyper-base-fundamentos-036",
    title: "Detalle en papel",
    summary: "Fibra visible.",
    area: AREA,
    category: CATEGORY,
    prompt: "papel con fibra visible, bordes naturales, textura realista",
  },
  {
    id: "hyper-base-fundamentos-037",
    title: "Detalle en cuero",
    summary: "Poros y pliegues.",
    area: AREA,
    category: CATEGORY,
    prompt: "cuero realista con poro, arrugas sutiles, brillo natural",
  },
  {
    id: "hyper-base-fundamentos-038",
    title: "Detalle en cerámica",
    summary: "Esmalte real.",
    area: AREA,
    category: CATEGORY,
    prompt: "cerámica con esmalte real, micro imperfecciones, reflejo suave",
  },
  {
    id: "hyper-base-fundamentos-039",
    title: "Detalle en piel animal",
    summary: "Pelo/pluma real.",
    area: AREA,
    category: CATEGORY,
    prompt: "pelaje/plumas con variación natural, sin look de alfombra, anatomía correcta",
  },
  {
    id: "hyper-base-fundamentos-040",
    title: "Movimiento leve",
    summary: "Más real.",
    area: AREA,
    category: CATEGORY,
    prompt: "ligera imperfección de captura, naturalidad, cero rigidez artificial",
  },
  {
    id: "hyper-base-fundamentos-041",
    title: "Cero “plastificado”",
    summary: "Evita superficies lisas.",
    area: AREA,
    category: CATEGORY,
    prompt: "evitar superficies plastificadas, mantener textura orgánica y real",
  },
  {
    id: "hyper-base-fundamentos-042",
    title: "Ruido controlado",
    summary: "No noise feo.",
    area: AREA,
    category: CATEGORY,
    prompt: "ruido mínimo y orgánico, sin artefactos de compresión",
  },
  {
    id: "hyper-base-fundamentos-043",
    title: "Natural skin variation",
    summary: "Variación de tono.",
    area: AREA,
    category: CATEGORY,
    prompt: "variación natural de tono en piel (rojeces sutiles, sombras), nada uniforme",
  },
  {
    id: "hyper-base-fundamentos-044",
    title: "Sin plastic hair",
    summary: "Cabello real.",
    area: AREA,
    category: CATEGORY,
    prompt: "cabello sin efecto plástico, separación de mechones, brillo real",
  },
  {
    id: "hyper-base-fundamentos-045",
    title: "Fondos sin “AI mush”",
    summary: "Evita textura derretida.",
    area: AREA,
    category: CATEGORY,
    prompt: "fondo nítido donde debe, sin ‘mush’, sin detalles derretidos",
  },
  {
    id: "hyper-base-fundamentos-046",
    title: "Detalles en bordes",
    summary: "Nada raro en siluetas.",
    area: AREA,
    category: CATEGORY,
    prompt: "siluetas limpias, sin doble contorno, sin recorte falso",
  },
  {
    id: "hyper-base-fundamentos-047",
    title: "Realismo de polvo",
    summary: "Polvo sutil.",
    area: AREA,
    category: CATEGORY,
    prompt: "polvo sutil en superficies, micro partículas realistas, sin exceso",
  },
  {
    id: "hyper-base-fundamentos-048",
    title: "Realismo de desgaste",
    summary: "Uso real.",
    area: AREA,
    category: CATEGORY,
    prompt: "desgaste sutil, uso realista, pequeñas marcas auténticas",
  },
  {
    id: "hyper-base-fundamentos-049",
    title: "Sin “shiny skin”",
    summary: "Brillo correcto.",
    area: AREA,
    category: CATEGORY,
    prompt: "brillo de piel controlado, zonas T realistas, sin aceite exagerado",
  },
  {
    id: "hyper-base-fundamentos-050",
    title: "Nitidez en sujeto",
    summary: "Focus correcto.",
    area: AREA,
    category: CATEGORY,
    prompt: "sujeto nítido, foco consistente, sin blur selectivo raro",
  },

  // 50 MÁS (cortos, listos para pegar)
  {
    id: "hyper-base-fundamentos-051",
    title: "Evita render look",
    summary: "Negativos directos.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin CGI, sin render 3D, sin ilustración, sin estilo cartoon/anime",
  },
  {
    id: "hyper-base-fundamentos-052",
    title: "Evita geometría rara",
    summary: "Proporciones sanas.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin deformaciones, sin objetos torcidos, sin geometría imposible",
  },
  {
    id: "hyper-base-fundamentos-053",
    title: "Detalles finos visibles",
    summary: "Microdetalle.",
    area: AREA,
    category: CATEGORY,
    prompt: "microdetalle visible, texturas nítidas, sin smudge",
  },
  {
    id: "hyper-base-fundamentos-054",
    title: "Shadows grounded",
    summary: "Nada flotante.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombra de contacto, el objeto no flota, soporte creíble",
  },
  {
    id: "hyper-base-fundamentos-055",
    title: "Sin glossy fake",
    summary: "Brillo real.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin brillo plástico, specular realista según material",
  },
  {
    id: "hyper-base-fundamentos-056",
    title: "Texturas no repetidas",
    summary: "Evita tiling.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin repetición de textura, sin patrones clonados (tiling)",
  },
  {
    id: "hyper-base-fundamentos-057",
    title: "Detalles de borde",
    summary: "Contorno real.",
    area: AREA,
    category: CATEGORY,
    prompt: "bordes naturales, pequeñas irregularidades, nada perfecto",
  },
  {
    id: "hyper-base-fundamentos-058",
    title: "Croma realista",
    summary: "Nada radioactivo.",
    area: AREA,
    category: CATEGORY,
    prompt: "colores realistas, nada fluorescente sin razón, saturación moderada",
  },
  {
    id: "hyper-base-fundamentos-059",
    title: "Piel con textura",
    summary: "Naturalidad.",
    area: AREA,
    category: CATEGORY,
    prompt: "poros visibles, microarrugas, textura natural, sin airbrush",
  },
  {
    id: "hyper-base-fundamentos-060",
    title: "Líneas rectas rectas",
    summary: "Arquitectura.",
    area: AREA,
    category: CATEGORY,
    prompt: "líneas rectas coherentes, sin warping, sin perspectiva rota",
  },
  {
    id: "hyper-base-fundamentos-061",
    title: "Detalle en sombras",
    summary: "Rango real.",
    area: AREA,
    category: CATEGORY,
    prompt: "detalle en sombras, rango dinámico natural, sin negros cerrados",
  },
  {
    id: "hyper-base-fundamentos-062",
    title: "Detalle en luz",
    summary: "Roll-off.",
    area: AREA,
    category: CATEGORY,
    prompt: "roll-off suave en altas luces, sin quemados duros",
  },
  {
    id: "hyper-base-fundamentos-063",
    title: "Sin ojos raros",
    summary: "Evita uncanny.",
    area: AREA,
    category: CATEGORY,
    prompt: "evitar ojos desalineados, pupilas raras, brillo falso, mirada uncanny",
  },
  {
    id: "hyper-base-fundamentos-064",
    title: "Sin dientes extraños",
    summary: "Boca normal.",
    area: AREA,
    category: CATEGORY,
    prompt: "dientes normales, encías naturales, sin deformación en boca",
  },
  {
    id: "hyper-base-fundamentos-065",
    title: "Sin piel uniformada",
    summary: "Variación de tono.",
    area: AREA,
    category: CATEGORY,
    prompt: "variación sutil de tono en piel, sin uniformidad artificial",
  },
  {
    id: "hyper-base-fundamentos-066",
    title: "Detalles de poro material",
    summary: "Material real.",
    area: AREA,
    category: CATEGORY,
    prompt: "micro porosidad en materiales, roughness realista, especular controlado",
  },
  {
    id: "hyper-base-fundamentos-067",
    title: "Sin halos",
    summary: "Bordes limpios.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin halos alrededor del sujeto, sin glow artificial",
  },
  {
    id: "hyper-base-fundamentos-068",
    title: "Sin sobre-enfoque",
    summary: "Natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin enfoque artificial, sin sharpen excesivo, detalle natural",
  },
  {
    id: "hyper-base-fundamentos-069",
    title: "Sin suavizado extremo",
    summary: "Evita blur beauty.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin blur beauty, sin piel de muñeca, textura preservada",
  },
  {
    id: "hyper-base-fundamentos-070",
    title: "Cero artefactos",
    summary: "Limpieza.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin artefactos, sin glitch, sin smear, sin distorsión",
  },
  {
    id: "hyper-base-fundamentos-071",
    title: "Ambient realism",
    summary: "Atmósfera real.",
    area: AREA,
    category: CATEGORY,
    prompt: "atmósfera realista, micro neblina sutil si aplica, nada fantasioso",
  },
  {
    id: "hyper-base-fundamentos-072",
    title: "Profundidad de planos",
    summary: "Layering real.",
    area: AREA,
    category: CATEGORY,
    prompt: "foreground-midground-background claros, profundidad natural",
  },
  {
    id: "hyper-base-fundamentos-073",
    title: "Textura en superficies",
    summary: "No superficies perfectas.",
    area: AREA,
    category: CATEGORY,
    prompt: "superficies no perfectas, pequeñas irregularidades, realismo físico",
  },
  {
    id: "hyper-base-fundamentos-074",
    title: "Evita simetría perfecta",
    summary: "Más humano.",
    area: AREA,
    category: CATEGORY,
    prompt: "evitar simetría perfecta, pequeñas variaciones naturales",
  },
  {
    id: "hyper-base-fundamentos-075",
    title: "Edges with realism",
    summary: "Detalles de borde.",
    area: AREA,
    category: CATEGORY,
    prompt: "edge wear sutil, bordes con desgaste mínimo, realismo",
  },
  {
    id: "hyper-base-fundamentos-076",
    title: "Sin “textura derretida”",
    summary: "Evita mush.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin ‘derretido’ en texturas, sin detalles borrosos inconsistentes",
  },
  {
    id: "hyper-base-fundamentos-077",
    title: "Sin duplicar accesorios",
    summary: "Evita clones.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin accesorios duplicados, sin objetos repetidos, sin simetrías raras",
  },
  {
    id: "hyper-base-fundamentos-078",
    title: "Evita manos extra",
    summary: "Negativo directo.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin dedos extra, sin manos deformes, anatomía correcta",
  },
  {
    id: "hyper-base-fundamentos-079",
    title: "Evita anatomía extraña",
    summary: "Cuerpo real.",
    area: AREA,
    category: CATEGORY,
    prompt: "anatomía humana correcta, proporciones realistas, sin deformación",
  },
  {
    id: "hyper-base-fundamentos-080",
    title: "Lente natural",
    summary: "Sin distorsión extrema.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin distorsión extrema, sin ojo de pez, perspectiva natural",
  },
  {
    id: "hyper-base-fundamentos-081",
    title: "Sombra suave de estudio",
    summary: "Para producto/retrato.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombra suave de estudio, gradiente limpio, sin recorte",
  },
  {
    id: "hyper-base-fundamentos-082",
    title: "Detalle de superficie mojada",
    summary: "Humedad real.",
    area: AREA,
    category: CATEGORY,
    prompt: "humedad realista, micro gotas, reflejo suave, sin plástico",
  },
  {
    id: "hyper-base-fundamentos-083",
    title: "Detalle de polvo en luz",
    summary: "Rayos sutiles.",
    area: AREA,
    category: CATEGORY,
    prompt: "partículas sutiles en el aire si hay contraluz, muy natural",
  },
  {
    id: "hyper-base-fundamentos-084",
    title: "Sin filtros",
    summary: "Nada instagram.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin filtros, sin look app, foto real",
  },
  {
    id: "hyper-base-fundamentos-085",
    title: "Sin glow",
    summary: "Nada mágico.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin glow artificial, sin bloom exagerado",
  },
  {
    id: "hyper-base-fundamentos-086",
    title: "Detalles en bordes de ropa",
    summary: "Costuras y fibras.",
    area: AREA,
    category: CATEGORY,
    prompt: "costuras visibles, fibras sutiles, pliegues naturales",
  },
  {
    id: "hyper-base-fundamentos-087",
    title: "Detalles de piel en labios",
    summary: "Labios reales.",
    area: AREA,
    category: CATEGORY,
    prompt: "textura real en labios, sin pintalabios perfecto, detalle natural",
  },
  {
    id: "hyper-base-fundamentos-088",
    title: "Detalles en cejas",
    summary: "Pelos individuales.",
    area: AREA,
    category: CATEGORY,
    prompt: "cejas con pelos individuales, densidad natural, sin bloque",
  },
  {
    id: "hyper-base-fundamentos-089",
    title: "Detalles en pestañas",
    summary: "Sin pincel.",
    area: AREA,
    category: CATEGORY,
    prompt: "pestañas naturales, no perfectas, sin efecto ‘pintado’",
  },
  {
    id: "hyper-base-fundamentos-090",
    title: "Detalles de piel en nariz",
    summary: "Poros reales.",
    area: AREA,
    category: CATEGORY,
    prompt: "poros en nariz y mejillas visibles, realistas, sin exageración",
  },
  {
    id: "hyper-base-fundamentos-091",
    title: "Detalles en joyería",
    summary: "Metal/piedra real.",
    area: AREA,
    category: CATEGORY,
    prompt: "joyería realista, micro rayas, destellos controlados, sin brillos falsos",
  },
  {
    id: "hyper-base-fundamentos-092",
    title: "Detalles de sombra de contacto",
    summary: "Asienta el objeto.",
    area: AREA,
    category: CATEGORY,
    prompt: "contact shadow visible, objeto asentado, sin flotación",
  },
  {
    id: "hyper-base-fundamentos-093",
    title: "Detalles de textura en piel",
    summary: "Poros y vello fino.",
    area: AREA,
    category: CATEGORY,
    prompt: "poros + vello fino, textura natural, sin cera, sin blur",
  },
  {
    id: "hyper-base-fundamentos-094",
    title: "Detalles de ojo real",
    summary: "Iris natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "iris realista, patrón natural, sin brillo de videojuego",
  },
  {
    id: "hyper-base-fundamentos-095",
    title: "Detalles de fondo real",
    summary: "Fondo sin errores.",
    area: AREA,
    category: CATEGORY,
    prompt: "fondo lógico y limpio, sin objetos mutantes, sin detalles incoherentes",
  },
  {
    id: "hyper-base-fundamentos-096",
    title: "Realismo sin exageración",
    summary: "Creíble.",
    area: AREA,
    category: CATEGORY,
    prompt: "realismo creíble, nada extremo, nada irreal, foto natural",
  },
  {
    id: "hyper-base-fundamentos-097",
    title: "Evita piel ‘cera’",
    summary: "Negativo directo.",
    area: AREA,
    category: CATEGORY,
    prompt: "evitar piel encerada, evitar suavizado, mantener textura real",
  },
  {
    id: "hyper-base-fundamentos-098",
    title: "Evita ‘pintado’",
    summary: "Sin look artístico.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin look pintado, sin pinceladas, sin ilustración, fotográfico",
  },
  {
    id: "hyper-base-fundamentos-099",
    title: "Evita surreal",
    summary: "Sin elementos imposibles.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin surrealismo, sin elementos imposibles, sin anatomía absurda",
  },
  {
    id: "hyper-base-fundamentos-100",
    title: "Negativos pro (compacto)",
    summary: "Bloque negativo corto para pegar.",
    area: AREA,
    category: CATEGORY,
    prompt: "negativo: CGI, render, cartoon, anime, plastic skin, deformed hands, extra fingers, bad text, artifacts",
  },
];
