// src/lib/prompts/hyperrealism-text/camara.js
// Unikalny obszar i kategoria dla CAŁEGO tego pliku:
const AREA = "Kamera";
const CATEGORY = "Obiektywy";

export const hyperrealismTextPromptsCamara = [
  { id: "hyper-camara-lentes-001", title: "35mm dokumentalny", summary: "Naturalna perspektywa.", area: AREA, category: CATEGORY, prompt: "35mm, styl dokumentalny, naturalna perspektywa" },
  { id: "hyper-camara-lentes-002", title: "50mm klasyczny", summary: "Realistyczna równowaga.", area: AREA, category: CATEGORY, prompt: "50mm, klasyczny look, realne proporcje" },
  { id: "hyper-camara-lentes-003", title: "85mm portret pro", summary: "Przyjemna kompresja.", area: AREA, category: CATEGORY, prompt: "85mm, subtelna kompresja, portret editorial" },
  { id: "hyper-camara-lentes-004", title: "105mm makro", summary: "Ekstremalny detal.", area: AREA, category: CATEGORY, prompt: "makro 105mm, widoczny mikrodetal, realistyczna ostrość" },
  { id: "hyper-camara-lentes-005", title: "24mm umiarkowany szeroki kąt", summary: "Szeroko bez przesady.", area: AREA, category: CATEGORY, prompt: "24mm, umiarkowany szeroki kąt, naturalne proste linie" },
  { id: "hyper-camara-lentes-006", title: "28mm uliczny", summary: "Street real.", area: AREA, category: CATEGORY, prompt: "28mm, street photography, dynamiczny kadr" },
  { id: "hyper-camara-lentes-007", title: "70mm miękkie kino", summary: "Średnia kompresja.", area: AREA, category: CATEGORY, prompt: "70mm, średnia kompresja, filmowy look" },
  { id: "hyper-camara-lentes-008", title: "135mm tele portret", summary: "Skompresowane tło.", area: AREA, category: CATEGORY, prompt: "135mm, tele portret, realistycznie skompresowane tło" },
  { id: "hyper-camara-lentes-009", title: "200mm izolacja", summary: "Odseparowany obiekt.", area: AREA, category: CATEGORY, prompt: "200mm, teleobiektyw, odseparowany obiekt, realna kompresja" },
  { id: "hyper-camara-lentes-010", title: "Czysty standardowy obiektyw", summary: "Bez dziwnych zniekształceń.", area: AREA, category: CATEGORY, prompt: "standardowy obiektyw, naturalna perspektywa, poprawna geometria" },

  { id: "hyper-camara-lentes-011", title: "Niska dystorsja", summary: "Czyste krawędzie.", area: AREA, category: CATEGORY, prompt: "niska dystorsja, proste linie, bez krzywizn" },
  { id: "hyper-camara-lentes-012", title: "Bez rybiego oka", summary: "Nic krzywego.", area: AREA, category: CATEGORY, prompt: "bez fish-eye, bez ekstremalnych deformacji" },
  { id: "hyper-camara-lentes-013", title: "Naturalny bokeh", summary: "Wiarygodne rozmycie.", area: AREA, category: CATEGORY, prompt: "naturalny bokeh, progresywne rozmycie, bez wycięć" },
  { id: "hyper-camara-lentes-014", title: "Średnia głębia ostrości", summary: "Wyraźny obiekt, miękkie tło.", area: AREA, category: CATEGORY, prompt: "średnia głębia ostrości, ostry obiekt, miękkie tło" },
  { id: "hyper-camara-lentes-015", title: "Mała głębia ostrości", summary: "Selektywny fokus.", area: AREA, category: CATEGORY, prompt: "mała głębia ostrości, precyzyjny fokus, kremowe tło" },
  { id: "hyper-camara-lentes-016", title: "Duża głębia ostrości", summary: "Wszystko ostre.", area: AREA, category: CATEGORY, prompt: "duża głębia ostrości, ostrość od planu do planu" },
  { id: "hyper-camara-lentes-017", title: "Ostrość na oku", summary: "Realny portret.", area: AREA, category: CATEGORY, prompt: "ostrość na dominującym oku, naturalna ostrość" },
  { id: "hyper-camara-lentes-018", title: "Ostrość na produkcie", summary: "Packshot.", area: AREA, category: CATEGORY, prompt: "ostrość na krawędziach produktu, widoczna tekstura" },
  { id: "hyper-camara-lentes-019", title: "Ostrość na pierwszym planie", summary: "Realne warstwy.", area: AREA, category: CATEGORY, prompt: "ostrość na pierwszym planie, realistyczny spadek ostrości" },
  { id: "hyper-camara-lentes-020", title: "Realny mikro-kontrast", summary: "Detal bez HDR.", area: AREA, category: CATEGORY, prompt: "realistyczny mikro-kontrast, drobny detal, bez agresywnego HDR" },

  { id: "hyper-camara-lentes-021", title: "Subtelne ziarno", summary: "Tekstura foto.", area: AREA, category: CATEGORY, prompt: "subtelne ziarno fotograficzne, naturalne" },
  { id: "hyper-camara-lentes-022", title: "Bez wyostrzania na siłę", summary: "Organiczna ostrość.", area: AREA, category: CATEGORY, prompt: "bez over-sharpeningu, naturalna ostrość" },
  { id: "hyper-camara-lentes-023", title: "Organiczna ostrość", summary: "Bez halo.", area: AREA, category: CATEGORY, prompt: "organiczna ostrość, bez halo, realna tekstura" },
  { id: "hyper-camara-lentes-024", title: "Bez niespójnego rozmycia", summary: "Unikaj artefaktów.", area: AREA, category: CATEGORY, prompt: "bez niespójnego rozmycia, bez sztucznego blur" },
  { id: "hyper-camara-lentes-025", title: "Zrównoważona ekspozycja", summary: "Pełny zakres.", area: AREA, category: CATEGORY, prompt: "zrównoważona ekspozycja, detal w cieniach i światłach" },
  { id: "hyper-camara-lentes-026", title: "Minimalna winieta", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "winieta bardzo subtelna lub brak, naturalny look" },
  { id: "hyper-camara-lentes-027", title: "Miękka winieta", summary: "Wizualny fokus.", area: AREA, category: CATEGORY, prompt: "subtelna miękka winieta, nic oczywistego" },
  { id: "hyper-camara-lentes-028", title: "Spójna skala", summary: "Realny dystans.", area: AREA, category: CATEGORY, prompt: "ogniskowa spójna ze sceną, realistyczna skala" },
  { id: "hyper-camara-lentes-029", title: "Ludzka perspektywa", summary: "Jak ludzkie oko.", area: AREA, category: CATEGORY, prompt: "naturalna ludzka perspektywa, poprawne proporcje" },
  { id: "hyper-camara-lentes-030", title: "Kąt na wysokości oczu", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "kąt na wysokości oczu, naturalna kompozycja" },

  { id: "hyper-camara-lentes-031", title: "Plan średni", summary: "Zrównoważony.", area: AREA, category: CATEGORY, prompt: "plan średni, zrównoważony kadr, realne proporcje" },
  { id: "hyper-camara-lentes-032", title: "Close-up twarzy", summary: "Realny detal.", area: AREA, category: CATEGORY, prompt: "zbliżenie twarzy, realistyczny detal skóry" },
  { id: "hyper-camara-lentes-033", title: "Plan ogólny", summary: "Pełne otoczenie.", area: AREA, category: CATEGORY, prompt: "plan ogólny, spójne linie, ludzka skala" },
  { id: "hyper-camara-lentes-034", title: "Kąt 3/4", summary: "Głębia.", area: AREA, category: CATEGORY, prompt: "kąt 3/4, naturalna głębia, bez deformacji" },
  { id: "hyper-camara-lentes-035", title: "Lekki dolny kąt", summary: "Subtelnie.", area: AREA, category: CATEGORY, prompt: "lekki dolny kąt, stabilne proporcje, realistycznie" },
  { id: "hyper-camara-lentes-036", title: "Lekki górny kąt", summary: "Subtelnie.", area: AREA, category: CATEGORY, prompt: "lekki górny kąt, stabilna geometria, realistycznie" },
  { id: "hyper-camara-lentes-037", title: "Minimalna aberracja", summary: "Czyste krawędzie.", area: AREA, category: CATEGORY, prompt: "minimalna aberracja chromatyczna, czyste krawędzie" },
  { id: "hyper-camara-lentes-038", title: "Subtelna realna aberracja", summary: "Mikro realizm.", area: AREA, category: CATEGORY, prompt: "bardzo lekka aberracja chromatyczna (realistyczna)" },
  { id: "hyper-camara-lentes-039", title: "Bez mory", summary: "Tekstylia OK.", area: AREA, category: CATEGORY, prompt: "bez mory, bez dziwnych wzorów na ubraniach/tkaninach" },
  { id: "hyper-camara-lentes-040", title: "Minimalny motion blur", summary: "Tylko jeśli pasuje.", area: AREA, category: CATEGORY, prompt: "minimalny realistyczny motion blur (jeśli jest ruch)" },

  { id: "hyper-camara-lentes-041", title: "Detal w cieniach", summary: "Czernie niezalane.", area: AREA, category: CATEGORY, prompt: "detal w cieniach, czernie niezalane" },
  { id: "hyper-camara-lentes-042", title: "Detal w highlightach", summary: "Bez przepaleń.", area: AREA, category: CATEGORY, prompt: "detal w highlightach, miękki roll-off" },
  { id: "hyper-camara-lentes-043", title: "Naturalny balans bieli", summary: "Wiarygodne tony.", area: AREA, category: CATEGORY, prompt: "naturalny balans bieli, wiarygodne tony skóry" },
  { id: "hyper-camara-lentes-044", title: "Bez dodatkowej saturacji", summary: "Realny kolor.", area: AREA, category: CATEGORY, prompt: "bez nadmiernej saturacji, realistyczny kolor" },
  { id: "hyper-camara-lentes-045", title: "Czysty centralny kadr", summary: "Minimal real.", area: AREA, category: CATEGORY, prompt: "czysty centralny kadr, prosta realistyczna kompozycja" },
  { id: "hyper-camara-lentes-046", title: "Zasada trójpodziału", summary: "Klasyka.", area: AREA, category: CATEGORY, prompt: "kompozycja w zasadzie trójpodziału, naturalna równowaga" },
  { id: "hyper-camara-lentes-047", title: "Kontrolowana symetria", summary: "Porządek wizualny.", area: AREA, category: CATEGORY, prompt: "subtelna symetria, czyste linie, realizm" },
  { id: "hyper-camara-lentes-048", title: "Linie prowadzące", summary: "Prowadzą wzrok.", area: AREA, category: CATEGORY, prompt: "naturalne linie prowadzące, bez niemożliwej geometrii" },
  { id: "hyper-camara-lentes-049", title: "Kadr z oddechem", summary: "Przestrzeń.", area: AREA, category: CATEGORY, prompt: "realistyczna przestrzeń negatywna, kadr z oddechem" },
  { id: "hyper-camara-lentes-050", title: "Editorial crop", summary: "Magazyn.", area: AREA, category: CATEGORY, prompt: "editorial crop, dopracowany kadr, realistycznie" },

  { id: "hyper-camara-lentes-051", title: "Cała sylwetka 35mm", summary: "Naturalna pełna postać.", area: AREA, category: CATEGORY, prompt: "35mm, ujęcie całej sylwetki, realne proporcje" },
  { id: "hyper-camara-lentes-052", title: "Cała sylwetka 50mm", summary: "Jeszcze naturalniej.", area: AREA, category: CATEGORY, prompt: "50mm, cała sylwetka, stabilna perspektywa" },
  { id: "hyper-camara-lentes-053", title: "Portret 85mm z bokeh", summary: "Kremowe tło.", area: AREA, category: CATEGORY, prompt: "85mm, naturalny bokeh, precyzyjny fokus" },
  { id: "hyper-camara-lentes-054", title: "Miękkie tele 135mm", summary: "Ładna kompresja.", area: AREA, category: CATEGORY, prompt: "135mm, miękka kompresja, spokojne tło" },
  { id: "hyper-camara-lentes-055", title: "Realne makro", summary: "Bez plastiku.", area: AREA, category: CATEGORY, prompt: "realistyczne makro, autentyczna tekstura, bez wyglądu CGI" },
  { id: "hyper-camara-lentes-056", title: "Ulica 28mm", summary: "Miejski realizm.", area: AREA, category: CATEGORY, prompt: "28mm, ulica, subtelny ruch, realizm" },
  { id: "hyper-camara-lentes-057", title: "Wnętrze 35mm", summary: "Prawdziwy pokój.", area: AREA, category: CATEGORY, prompt: "35mm, wnętrze, proste linie, naturalny look" },
  { id: "hyper-camara-lentes-058", title: "Wnętrze 24mm umiarkowane", summary: "Szeroko bez deformacji.", area: AREA, category: CATEGORY, prompt: "24mm umiarkowane, wnętrze, bez ekstremalnej dystorsji" },
  { id: "hyper-camara-lentes-059", title: "Produkt 70mm", summary: "Premium packshot.", area: AREA, category: CATEGORY, prompt: "70mm, produkt, ostre krawędzie, widoczna tekstura" },
  { id: "hyper-camara-lentes-060", title: "Produkt 105mm", summary: "Detal.", area: AREA, category: CATEGORY, prompt: "105mm, produkt, ekstremalny detal, czysty fokus" },

  { id: "hyper-camara-lentes-061", title: "F/2.8 naturalnie", summary: "Wiarygodny bokeh.", area: AREA, category: CATEGORY, prompt: "przysłona typu f/2.8, naturalny bokeh, bez wycięć" },
  { id: "hyper-camara-lentes-062", title: "F/1.8 kontrolowane", summary: "Realna mała GO.", area: AREA, category: CATEGORY, prompt: "przysłona typu f/1.8 (kontrolowana), precyzyjny fokus" },
  { id: "hyper-camara-lentes-063", title: "F/5.6 ostro", summary: "Więcej głębi.", area: AREA, category: CATEGORY, prompt: "przysłona typu f/5.6, spójna ostrość" },
  { id: "hyper-camara-lentes-064", title: "F/8 krajobraz", summary: "Plan po planie.", area: AREA, category: CATEGORY, prompt: "przysłona typu f/8, szeroka głębia, detal" },
  { id: "hyper-camara-lentes-065", title: "Niskie ISO", summary: "Czysto.", area: AREA, category: CATEGORY, prompt: "niskie ISO, minimalny szum, realistyczny detal" },
  { id: "hyper-camara-lentes-066", title: "Dyskretny szum", summary: "Realizm.", area: AREA, category: CATEGORY, prompt: "lekki realistyczny szum, nie agresywny cyfrowo" },
  { id: "hyper-camara-lentes-067", title: "Szybka migawka", summary: "Zamraża ruch.", area: AREA, category: CATEGORY, prompt: "szybka migawka, ostrość bez poruszenia" },
  { id: "hyper-camara-lentes-068", title: "Wolna migawka kontrolowana", summary: "Realny blur.", area: AREA, category: CATEGORY, prompt: "kontrolowana wolna migawka, realistyczny motion blur" },
  { id: "hyper-camara-lentes-069", title: "Delikatna stabilizacja", summary: "Handheld.", area: AREA, category: CATEGORY, prompt: "delikatna stabilizacja, naturalny handheld" },
  { id: "hyper-camara-lentes-070", title: "Look ze statywu", summary: "Profesjonalnie statycznie.", area: AREA, category: CATEGORY, prompt: "stabilne ujęcie jak ze statywu, solidna kompozycja" },

  { id: "hyper-camara-lentes-071", title: "Kadr 4:3", summary: "Klasyka.", area: AREA, category: CATEGORY, prompt: "kadr 4:3, klasyczna estetyka fotograficzna" },
  { id: "hyper-camara-lentes-072", title: "Kadr 3:2", summary: "Standard foto.", area: AREA, category: CATEGORY, prompt: "kadr 3:2, wrażenie DSLR, realistycznie" },
  { id: "hyper-camara-lentes-073", title: "Kadr 1:1", summary: "Kwadrat.", area: AREA, category: CATEGORY, prompt: "kadr 1:1, czysta kompozycja, realistycznie" },
  { id: "hyper-camara-lentes-074", title: "Kadr 16:9", summary: "Filmowo.", area: AREA, category: CATEGORY, prompt: "kadr 16:9, naturalny filmowy look" },
  { id: "hyper-camara-lentes-075", title: "Zero rolling shutter", summary: "Bez deformacji.", area: AREA, category: CATEGORY, prompt: "bez deformacji typu rolling shutter, stabilna geometria" },
  { id: "hyper-camara-lentes-076", title: "Bez bandingu", summary: "Gładkie gradienty.", area: AREA, category: CATEGORY, prompt: "gładkie gradienty, bez bandingu, naturalny ton" },
  { id: "hyper-camara-lentes-077", title: "Bez halo", summary: "Naturalne krawędzie.", area: AREA, category: CATEGORY, prompt: "bez halo od wyostrzania, naturalne krawędzie" },
  { id: "hyper-camara-lentes-078", title: "Bez posteryzacji", summary: "Realny kolor.", area: AREA, category: CATEGORY, prompt: "bez posteryzacji, realistycznie miękkie tony" },
  { id: "hyper-camara-lentes-079", title: "Bez artefaktów AI", summary: "Czysto.", area: AREA, category: CATEGORY, prompt: "bez artefaktów, bez powtarzalnych tekstur, bez glitchy" },
  { id: "hyper-camara-lentes-080", title: "Tekstura sensora", summary: "Prawdziwe foto.", area: AREA, category: CATEGORY, prompt: "wrażenie prawdziwego sensora, drobny detal, naturalnie" },

  { id: "hyper-camara-lentes-081", title: "Brak ‘oddychania’ ostrości", summary: "Stabilny fokus.", area: AREA, category: CATEGORY, prompt: "stabilny fokus, bez dziwnych zmian GO" },
  { id: "hyper-camara-lentes-082", title: "Separacja przez GO", summary: "Obiekt wybija się.", area: AREA, category: CATEGORY, prompt: "separacja obiektu od tła przez naturalną GO" },
  { id: "hyper-camara-lentes-083", title: "Naturalna kompresja", summary: "Bez spłaszczania.", area: AREA, category: CATEGORY, prompt: "naturalna kompresja, wiarygodne proporcje" },
  { id: "hyper-camara-lentes-084", title: "Bez niemożliwej perspektywy", summary: "Realna geometria.", area: AREA, category: CATEGORY, prompt: "bez niemożliwej perspektywy, spójne linie" },
  { id: "hyper-camara-lentes-085", title: "Makro – plan detalu", summary: "Prawdziwe zbliżenie.", area: AREA, category: CATEGORY, prompt: "makro plan detalu, autentyczna tekstura, mikro-niedoskonałości" },
  { id: "hyper-camara-lentes-086", title: "Detal produktu", summary: "E-commerce.", area: AREA, category: CATEGORY, prompt: "plan detalu produktu, ostre krawędzie, kontrolowane odbicia" },
  { id: "hyper-camara-lentes-087", title: "Realne nieostre tło", summary: "Stopniowy bokeh.", area: AREA, category: CATEGORY, prompt: "stopniowo nieostre tło, bez twardych wycięć" },
  { id: "hyper-camara-lentes-088", title: "Fokus na teksturę", summary: "Widoczny materiał.", area: AREA, category: CATEGORY, prompt: "fokus na teksturę, widoczny mikrodetal, naturalnie" },
  { id: "hyper-camara-lentes-089", title: "Minimalna edycja", summary: "Bez filtrów.", area: AREA, category: CATEGORY, prompt: "minimalna edycja, realny look foto, bez agresywnych filtrów" },
  { id: "hyper-camara-lentes-090", title: "Delikatny color grading", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "delikatny color grading, kontrolowany kontrast, realistycznie" },

  { id: "hyper-camara-lentes-091", title: "Umiarkowana klarowność", summary: "Detal bez twardości.", area: AREA, category: CATEGORY, prompt: "umiarkowana klarowność, realistyczny detal, bez twardości" },
  { id: "hyper-camara-lentes-092", title: "Bez HDR", summary: "Nic przesadnego.", area: AREA, category: CATEGORY, prompt: "bez przesadnego HDR, naturalny zakres" },
  { id: "hyper-camara-lentes-093", title: "Ciągły fokus", summary: "Stabilny obiekt.", area: AREA, category: CATEGORY, prompt: "stabilny ciągły fokus, obiekt zawsze ostry" },
  { id: "hyper-camara-lentes-094", title: "Punktowy fokus", summary: "Precyzja.", area: AREA, category: CATEGORY, prompt: "punktowy fokus (single point), maksymalna precyzja" },
  { id: "hyper-camara-lentes-095", title: "Look RAW", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "wrażenie RAW, naturalny kolor, autentyczny detal" },
  { id: "hyper-camara-lentes-096", title: "Bez brzydkiej kompresji", summary: "Czysto.", area: AREA, category: CATEGORY, prompt: "bez artefaktów kompresji, czysty detal" },
  { id: "hyper-camara-lentes-097", title: "Czyste cienie", summary: "Bez zalewania.", area: AREA, category: CATEGORY, prompt: "czyste cienie, bez zlewania, kontrolowany szum" },
  { id: "hyper-camara-lentes-098", title: "Miękkie highlighty", summary: "Roll-off.", area: AREA, category: CATEGORY, prompt: "miękkie highlighty, naturalny roll-off, bez clippingu" },
  { id: "hyper-camara-lentes-099", title: "Ostrość jak z prawdziwego obiektywu", summary: "Nie cyfrowa.", area: AREA, category: CATEGORY, prompt: "ostrość jak z prawdziwego obiektywu, nie cyfrowa, bez halo" },
  { id: "hyper-camara-lentes-100", title: "Zestaw pro kamery", summary: "Finalny pakiet.", area: AREA, category: CATEGORY, prompt: "realistyczny obiektyw, naturalna GO, subtelne ziarno, organiczna ostrość" },
];
