// src/lib/prompts/hyperrealism-text/camara.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Cámara";
const CATEGORY = "Lentes";

export const hyperrealismTextPromptsCamara = [
  { id: "hyper-camara-lentes-001", title: "35mm documental", summary: "Perspectiva natural.", area: AREA, category: CATEGORY, prompt: "35mm, estilo documental, perspectiva natural" },
  { id: "hyper-camara-lentes-002", title: "50mm clásico", summary: "Equilibrio realista.", area: AREA, category: CATEGORY, prompt: "50mm, look clásico, proporciones reales" },
  { id: "hyper-camara-lentes-003", title: "85mm retrato pro", summary: "Compresión agradable.", area: AREA, category: CATEGORY, prompt: "85mm, compresión sutil, retrato editorial" },
  { id: "hyper-camara-lentes-004", title: "105mm macro", summary: "Detalle extremo.", area: AREA, category: CATEGORY, prompt: "macro 105mm, microdetalle visible, nitidez realista" },
  { id: "hyper-camara-lentes-005", title: "24mm angular moderado", summary: "Amplitud sin exagerar.", area: AREA, category: CATEGORY, prompt: "24mm, gran angular moderado, líneas rectas naturales" },
  { id: "hyper-camara-lentes-006", title: "28mm callejero", summary: "Street real.", area: AREA, category: CATEGORY, prompt: "28mm, street photography, encuadre dinámico" },
  { id: "hyper-camara-lentes-007", title: "70mm cine suave", summary: "Compresión media.", area: AREA, category: CATEGORY, prompt: "70mm, compresión media, look cinematográfico" },
  { id: "hyper-camara-lentes-008", title: "135mm tele retrato", summary: "Fondo comprimido.", area: AREA, category: CATEGORY, prompt: "135mm, tele retrato, fondo comprimido realista" },
  { id: "hyper-camara-lentes-009", title: "200mm aislamiento", summary: "Sujeto separado.", area: AREA, category: CATEGORY, prompt: "200mm, teleobjetivo, sujeto aislado, compresión real" },
  { id: "hyper-camara-lentes-010", title: "Lente estándar limpio", summary: "Sin distorsión rara.", area: AREA, category: CATEGORY, prompt: "lente estándar, perspectiva natural, geometría correcta" },

  { id: "hyper-camara-lentes-011", title: "Baja distorsión", summary: "Edges limpios.", area: AREA, category: CATEGORY, prompt: "baja distorsión, líneas rectas, sin curvatura" },
  { id: "hyper-camara-lentes-012", title: "Sin ojo de pez", summary: "Nada curvo.", area: AREA, category: CATEGORY, prompt: "sin fish-eye, sin deformación extrema" },
  { id: "hyper-camara-lentes-013", title: "Bokeh natural", summary: "Desenfoque creíble.", area: AREA, category: CATEGORY, prompt: "bokeh natural, desenfoque progresivo, sin recortes" },
  { id: "hyper-camara-lentes-014", title: "DOF media", summary: "Sujeto claro, fondo suave.", area: AREA, category: CATEGORY, prompt: "profundidad de campo media, sujeto nítido, fondo suave" },
  { id: "hyper-camara-lentes-015", title: "DOF baja", summary: "Enfoque selectivo.", area: AREA, category: CATEGORY, prompt: "profundidad de campo baja, enfoque preciso, fondo cremoso" },
  { id: "hyper-camara-lentes-016", title: "DOF alta", summary: "Todo nítido.", area: AREA, category: CATEGORY, prompt: "profundidad de campo alta, nitidez de plano a plano" },
  { id: "hyper-camara-lentes-017", title: "Enfoque al ojo", summary: "Retrato real.", area: AREA, category: CATEGORY, prompt: "enfoque al ojo dominante, nitidez natural" },
  { id: "hyper-camara-lentes-018", title: "Enfoque al producto", summary: "Packshot.", area: AREA, category: CATEGORY, prompt: "enfoque en bordes del producto, textura visible" },
  { id: "hyper-camara-lentes-019", title: "Enfoque primer plano", summary: "Capas reales.", area: AREA, category: CATEGORY, prompt: "enfoque en primer plano, caída de enfoque real" },
  { id: "hyper-camara-lentes-020", title: "Microcontraste real", summary: "Detalle sin HDR.", area: AREA, category: CATEGORY, prompt: "microcontraste realista, detalle fino, sin HDR agresivo" },

  { id: "hyper-camara-lentes-021", title: "Grano sutil", summary: "Textura foto.", area: AREA, category: CATEGORY, prompt: "grano fotográfico sutil, natural" },
  { id: "hyper-camara-lentes-022", title: "Sin sobreenfoque", summary: "Nitidez orgánica.", area: AREA, category: CATEGORY, prompt: "sin over-sharpening, nitidez natural" },
  { id: "hyper-camara-lentes-023", title: "Nitidez orgánica", summary: "Sin halos.", area: AREA, category: CATEGORY, prompt: "nitidez orgánica, sin halos, textura real" },
  { id: "hyper-camara-lentes-024", title: "Sin blur inconsistente", summary: "Evita artefactos.", area: AREA, category: CATEGORY, prompt: "sin desenfoque inconsistente, sin blur artificial" },
  { id: "hyper-camara-lentes-025", title: "Exposición equilibrada", summary: "Rango completo.", area: AREA, category: CATEGORY, prompt: "exposición equilibrada, detalle en sombras y luces" },
  { id: "hyper-camara-lentes-026", title: "Viñeta mínima", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "viñeta muy sutil o nula, look natural" },
  { id: "hyper-camara-lentes-027", title: "Viñeta suave", summary: "Enfoque visual.", area: AREA, category: CATEGORY, prompt: "viñeta suave sutil, nada obvio" },
  { id: "hyper-camara-lentes-028", title: "Escala coherente", summary: "Distancia real.", area: AREA, category: CATEGORY, prompt: "distancia focal coherente con escena, escala realista" },
  { id: "hyper-camara-lentes-029", title: "Perspectiva humana", summary: "Ojo humano.", area: AREA, category: CATEGORY, prompt: "perspectiva humana natural, proporciones correctas" },
  { id: "hyper-camara-lentes-030", title: "Ángulo eye-level", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "ángulo a la altura de los ojos, composición natural" },

  { id: "hyper-camara-lentes-031", title: "Plano medio", summary: "Equilibrado.", area: AREA, category: CATEGORY, prompt: "plano medio, encuadre equilibrado, proporción real" },
  { id: "hyper-camara-lentes-032", title: "Close-up facial", summary: "Detalle real.", area: AREA, category: CATEGORY, prompt: "primer plano facial, detalle de piel realista" },
  { id: "hyper-camara-lentes-033", title: "Plano general", summary: "Entorno completo.", area: AREA, category: CATEGORY, prompt: "plano general, líneas coherentes, escala humana" },
  { id: "hyper-camara-lentes-034", title: "Ángulo 3/4", summary: "Profundidad.", area: AREA, category: CATEGORY, prompt: "ángulo 3/4, profundidad natural, sin deformación" },
  { id: "hyper-camara-lentes-035", title: "Leve contrapicado", summary: "Sutil.", area: AREA, category: CATEGORY, prompt: "leve contrapicado, proporciones estables, realista" },
  { id: "hyper-camara-lentes-036", title: "Leve picado", summary: "Sutil.", area: AREA, category: CATEGORY, prompt: "leve picado, geometría estable, realista" },
  { id: "hyper-camara-lentes-037", title: "Aberración mínima", summary: "Edges limpios.", area: AREA, category: CATEGORY, prompt: "aberración cromática mínima, bordes limpios" },
  { id: "hyper-camara-lentes-038", title: "Aberración sutil real", summary: "Realismo micro.", area: AREA, category: CATEGORY, prompt: "aberración cromática muy leve (realista)" },
  { id: "hyper-camara-lentes-039", title: "Sin moiré", summary: "Textiles OK.", area: AREA, category: CATEGORY, prompt: "sin moiré, sin patrones raros en ropa/tela" },
  { id: "hyper-camara-lentes-040", title: "Motion blur mínimo", summary: "Solo si aplica.", area: AREA, category: CATEGORY, prompt: "motion blur mínimo realista (si hay movimiento)" },

  { id: "hyper-camara-lentes-041", title: "Detalle en sombras", summary: "Negros no empastados.", area: AREA, category: CATEGORY, prompt: "detalle en sombras, negros no empastados" },
  { id: "hyper-camara-lentes-042", title: "Detalle en highlights", summary: "No quemar.", area: AREA, category: CATEGORY, prompt: "detalle en highlights, roll-off suave" },
  { id: "hyper-camara-lentes-043", title: "Balance de blancos natural", summary: "Tonos creíbles.", area: AREA, category: CATEGORY, prompt: "balance de blancos natural, tonos piel creíbles" },
  { id: "hyper-camara-lentes-044", title: "Sin saturación extra", summary: "Color real.", area: AREA, category: CATEGORY, prompt: "sin saturación excesiva, color realista" },
  { id: "hyper-camara-lentes-045", title: "Encuadre centrado limpio", summary: "Minimal real.", area: AREA, category: CATEGORY, prompt: "encuadre centrado limpio, composición simple realista" },
  { id: "hyper-camara-lentes-046", title: "Regla de tercios", summary: "Clásico.", area: AREA, category: CATEGORY, prompt: "composición regla de tercios, equilibrio natural" },
  { id: "hyper-camara-lentes-047", title: "Simetría controlada", summary: "Orden visual.", area: AREA, category: CATEGORY, prompt: "simetría sutil, líneas limpias, realismo" },
  { id: "hyper-camara-lentes-048", title: "Leading lines", summary: "Guía de mirada.", area: AREA, category: CATEGORY, prompt: "leading lines naturales, sin geometría imposible" },
  { id: "hyper-camara-lentes-049", title: "Encuadre con aire", summary: "Respira.", area: AREA, category: CATEGORY, prompt: "espacio negativo realista, encuadre con aire" },
  { id: "hyper-camara-lentes-050", title: "Recorte editorial", summary: "Magazine.", area: AREA, category: CATEGORY, prompt: "recorte editorial, encuadre pulido, realista" },

  { id: "hyper-camara-lentes-051", title: "Full-body 35mm", summary: "Cuerpo entero natural.", area: AREA, category: CATEGORY, prompt: "35mm, plano cuerpo entero, proporciones reales" },
  { id: "hyper-camara-lentes-052", title: "Full-body 50mm", summary: "Más natural.", area: AREA, category: CATEGORY, prompt: "50mm, cuerpo entero, perspectiva estable" },
  { id: "hyper-camara-lentes-053", title: "Retrato 85mm con bokeh", summary: "Fondo cremoso.", area: AREA, category: CATEGORY, prompt: "85mm, bokeh natural, enfoque preciso" },
  { id: "hyper-camara-lentes-054", title: "Tele suave 135mm", summary: "Compresión bonita.", area: AREA, category: CATEGORY, prompt: "135mm, compresión suave, fondo calmado" },
  { id: "hyper-camara-lentes-055", title: "Macro real", summary: "Nada plástico.", area: AREA, category: CATEGORY, prompt: "macro realista, textura auténtica, sin look CGI" },
  { id: "hyper-camara-lentes-056", title: "Calle 28mm", summary: "Realismo urbano.", area: AREA, category: CATEGORY, prompt: "28mm, calle, movimiento sutil, realismo" },
  { id: "hyper-camara-lentes-057", title: "Interior 35mm", summary: "Habitación real.", area: AREA, category: CATEGORY, prompt: "35mm, interior, líneas rectas, look natural" },
  { id: "hyper-camara-lentes-058", title: "Interior 24mm moderado", summary: "Amplio sin deformar.", area: AREA, category: CATEGORY, prompt: "24mm moderado, interior, sin distorsión extrema" },
  { id: "hyper-camara-lentes-059", title: "Producto 70mm", summary: "Packshot premium.", area: AREA, category: CATEGORY, prompt: "70mm, producto, bordes nítidos, textura visible" },
  { id: "hyper-camara-lentes-060", title: "Producto 105mm", summary: "Detalle.", area: AREA, category: CATEGORY, prompt: "105mm, producto, detalle extremo, enfoque limpio" },

  { id: "hyper-camara-lentes-061", title: "F/2.8 natural", summary: "Bokeh creíble.", area: AREA, category: CATEGORY, prompt: "apertura tipo f/2.8, bokeh natural, sin recortes" },
  { id: "hyper-camara-lentes-062", title: "F/1.8 controlado", summary: "DOF baja real.", area: AREA, category: CATEGORY, prompt: "apertura tipo f/1.8 (controlada), enfoque preciso" },
  { id: "hyper-camara-lentes-063", title: "F/5.6 nítido", summary: "Más profundidad.", area: AREA, category: CATEGORY, prompt: "apertura tipo f/5.6, nitidez consistente" },
  { id: "hyper-camara-lentes-064", title: "F/8 paisaje", summary: "Plano a plano.", area: AREA, category: CATEGORY, prompt: "apertura tipo f/8, profundidad amplia, detalle" },
  { id: "hyper-camara-lentes-065", title: "ISO bajo", summary: "Limpio.", area: AREA, category: CATEGORY, prompt: "ISO bajo, ruido mínimo, detalle realista" },
  { id: "hyper-camara-lentes-066", title: "Ruido discreto", summary: "Realismo.", area: AREA, category: CATEGORY, prompt: "ruido leve realista, no digital agresivo" },
  { id: "hyper-camara-lentes-067", title: "Shutter rápido", summary: "Congela.", area: AREA, category: CATEGORY, prompt: "obturación rápida, nitidez sin trepidación" },
  { id: "hyper-camara-lentes-068", title: "Shutter lento controlado", summary: "Blur real.", area: AREA, category: CATEGORY, prompt: "obturación lenta controlada, motion blur realista" },
  { id: "hyper-camara-lentes-069", title: "Estabilización suave", summary: "Handheld.", area: AREA, category: CATEGORY, prompt: "estabilización suave, handheld natural" },
  { id: "hyper-camara-lentes-070", title: "Tripié look", summary: "Estático pro.", area: AREA, category: CATEGORY, prompt: "toma estable tipo tripié, composición sólida" },

  { id: "hyper-camara-lentes-071", title: "Recorte 4:3", summary: "Clásico.", area: AREA, category: CATEGORY, prompt: "encuadre 4:3, estética fotográfica clásica" },
  { id: "hyper-camara-lentes-072", title: "Recorte 3:2", summary: "Foto estándar.", area: AREA, category: CATEGORY, prompt: "encuadre 3:2, sensación DSLR, realista" },
  { id: "hyper-camara-lentes-073", title: "Recorte 1:1", summary: "Cuadrado.", area: AREA, category: CATEGORY, prompt: "encuadre 1:1, composición limpia, realista" },
  { id: "hyper-camara-lentes-074", title: "Recorte 16:9", summary: "Cinemático.", area: AREA, category: CATEGORY, prompt: "encuadre 16:9, look cinematográfico natural" },
  { id: "hyper-camara-lentes-075", title: "Rolling shutter cero", summary: "Sin deformar.", area: AREA, category: CATEGORY, prompt: "sin deformaciones tipo rolling shutter, geometría estable" },
  { id: "hyper-camara-lentes-076", title: "Sin banding", summary: "Gradientes suaves.", area: AREA, category: CATEGORY, prompt: "gradientes suaves, sin banding, tono natural" },
  { id: "hyper-camara-lentes-077", title: "Sin halos", summary: "Edges naturales.", area: AREA, category: CATEGORY, prompt: "sin halos de enfoque, bordes naturales" },
  { id: "hyper-camara-lentes-078", title: "Sin posterización", summary: "Color real.", area: AREA, category: CATEGORY, prompt: "sin posterización, tonos suaves realistas" },
  { id: "hyper-camara-lentes-079", title: "Sin artefactos AI", summary: "Limpio.", area: AREA, category: CATEGORY, prompt: "sin artefactos, sin texturas repetidas, sin glitches" },
  { id: "hyper-camara-lentes-080", title: "Textura de sensor", summary: "Foto real.", area: AREA, category: CATEGORY, prompt: "sensación de sensor real, detalle fino, natural" },

  { id: "hyper-camara-lentes-081", title: "Respiración de enfoque nula", summary: "Enfoque estable.", area: AREA, category: CATEGORY, prompt: "enfoque estable, sin cambios raros de DOF" },
  { id: "hyper-camara-lentes-082", title: "Separación por DOF", summary: "Sujeto destaca.", area: AREA, category: CATEGORY, prompt: "separación sujeto-fondo por DOF natural" },
  { id: "hyper-camara-lentes-083", title: "Compresión natural", summary: "Sin aplastar.", area: AREA, category: CATEGORY, prompt: "compresión natural, proporciones creíbles" },
  { id: "hyper-camara-lentes-084", title: "Sin perspectiva imposible", summary: "Geometría real.", area: AREA, category: CATEGORY, prompt: "sin perspectiva imposible, líneas coherentes" },
  { id: "hyper-camara-lentes-085", title: "Plano detalle macro", summary: "Close real.", area: AREA, category: CATEGORY, prompt: "plano detalle macro, textura auténtica, microimperfecciones" },
  { id: "hyper-camara-lentes-086", title: "Plano detalle producto", summary: "E-commerce.", area: AREA, category: CATEGORY, prompt: "plano detalle producto, bordes nítidos, reflejos controlados" },
  { id: "hyper-camara-lentes-087", title: "Fondo fuera de foco real", summary: "Bokeh gradual.", area: AREA, category: CATEGORY, prompt: "fondo fuera de foco gradual, sin recortes duros" },
  { id: "hyper-camara-lentes-088", title: "Foco en textura", summary: "Material visible.", area: AREA, category: CATEGORY, prompt: "foco en textura, microdetalle visible, natural" },
  { id: "hyper-camara-lentes-089", title: "Edición mínima", summary: "Sin filtros.", area: AREA, category: CATEGORY, prompt: "edición mínima, look foto real, sin filtros agresivos" },
  { id: "hyper-camara-lentes-090", title: "Color grading suave", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "color grading suave, contraste controlado, realista" },

  { id: "hyper-camara-lentes-091", title: "Claridad moderada", summary: "Detalle sin dureza.", area: AREA, category: CATEGORY, prompt: "claridad moderada, detalle realista, sin dureza" },
  { id: "hyper-camara-lentes-092", title: "Sin HDR", summary: "Nada exagerado.", area: AREA, category: CATEGORY, prompt: "sin HDR exagerado, rango natural" },
  { id: "hyper-camara-lentes-093", title: "Enfoque continuo", summary: "Sujeto estable.", area: AREA, category: CATEGORY, prompt: "enfoque continuo estable, sujeto siempre nítido" },
  { id: "hyper-camara-lentes-094", title: "Enfoque puntual", summary: "Precisión.", area: AREA, category: CATEGORY, prompt: "enfoque puntual (single point), máxima precisión" },
  { id: "hyper-camara-lentes-095", title: "Look RAW", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "sensación RAW, color natural, detalle auténtico" },
  { id: "hyper-camara-lentes-096", title: "Sin compresión fea", summary: "Limpio.", area: AREA, category: CATEGORY, prompt: "sin artefactos de compresión, detalle limpio" },
  { id: "hyper-camara-lentes-097", title: "Sombras limpias", summary: "No empastar.", area: AREA, category: CATEGORY, prompt: "sombras limpias, sin empaste, ruido controlado" },
  { id: "hyper-camara-lentes-098", title: "Highlights suaves", summary: "Roll-off.", area: AREA, category: CATEGORY, prompt: "highlights suaves, roll-off natural, sin clipping" },
  { id: "hyper-camara-lentes-099", title: "Nitidez tipo lente real", summary: "No digital.", area: AREA, category: CATEGORY, prompt: "nitidez tipo lente real, no digital, sin halos" },
  { id: "hyper-camara-lentes-100", title: "Combo cámara pro", summary: "Pack final.", area: AREA, category: CATEGORY, prompt: "lente realista, DOF natural, grano sutil, nitidez orgánica" },
];
