// src/lib/prompts/hyperrealism-text/color.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Color";
const CATEGORY = "Balance";

export const hyperrealismTextPromptsColor = [
  { id: "hyper-col-balance-001", title: "Balance neutral", summary: "Color real sin dominantes.", area: AREA, category: CATEGORY, prompt: "balance de blancos neutral, colores naturales, sin dominantes" },
  { id: "hyper-col-balance-002", title: "WB cálido suave", summary: "Calidez realista.", area: AREA, category: CATEGORY, prompt: "temperatura cálida suave, piel creíble, sin amarilleo excesivo" },
  { id: "hyper-col-balance-003", title: "WB frío suave", summary: "Frescura realista.", area: AREA, category: CATEGORY, prompt: "temperatura fría suave, blancos limpios, sin azul artificial" },
  { id: "hyper-col-balance-004", title: "Tonos piel naturales", summary: "Prioridad piel.", area: AREA, category: CATEGORY, prompt: "tonos de piel naturales y creíbles, sin magenta/verde raro" },
  { id: "hyper-col-balance-005", title: "Saturación contenida", summary: "Sin look HDR.", area: AREA, category: CATEGORY, prompt: "saturación contenida, contraste realista, sin HDR exagerado" },
  { id: "hyper-col-balance-006", title: "Contraste suave", summary: "Editorial.", area: AREA, category: CATEGORY, prompt: "contraste suave, sombras abiertas, roll-off natural en luces" },
  { id: "hyper-col-balance-007", title: "Contraste medio", summary: "Foto estándar.", area: AREA, category: CATEGORY, prompt: "contraste medio realista, puntos negros controlados, sin crush" },
  { id: "hyper-col-balance-008", title: "Altas luces protegidas", summary: "Sin quemados.", area: AREA, category: CATEGORY, prompt: "altas luces protegidas, blancos con detalle, sin clipping" },
  { id: "hyper-col-balance-009", title: "Sombras limpias", summary: "Sin barro.", area: AREA, category: CATEGORY, prompt: "sombras limpias, sin ‘barro’ cromático, detalle conservado" },
  { id: "hyper-col-balance-010", title: "Negros naturales", summary: "Sin negro puro.", area: AREA, category: CATEGORY, prompt: "negros naturales (no negro puro), detalle sutil en sombras" },

  { id: "hyper-col-balance-011", title: "Grading cinematográfico sutil", summary: "Sin exagerar.", area: AREA, category: CATEGORY, prompt: "color grading cinematográfico sutil, sin teal-orange exagerado" },
  { id: "hyper-col-balance-012", title: "Teal-orange MUY leve", summary: "Solo un toque.", area: AREA, category: CATEGORY, prompt: "teal-orange muy leve, piel natural, sombras apenas frías" },
  { id: "hyper-col-balance-013", title: "Look editorial magazine", summary: "Premium.", area: AREA, category: CATEGORY, prompt: "look editorial de revista, colores naturales, separación suave" },
  { id: "hyper-col-balance-014", title: "Look documental", summary: "Real crudo.", area: AREA, category: CATEGORY, prompt: "look documental, colores honestos, contraste moderado" },
  { id: "hyper-col-balance-015", title: "Look e-commerce limpio", summary: "Producto fiel.", area: AREA, category: CATEGORY, prompt: "color fiel de producto, blancos neutros, sin dominantes" },
  { id: "hyper-col-balance-016", title: "Look food natural", summary: "Apetitoso real.", area: AREA, category: CATEGORY, prompt: "color natural en comida, balance cálido leve, sin saturación falsa" },
  { id: "hyper-col-balance-017", title: "Look urbano real", summary: "Calle realista.", area: AREA, category: CATEGORY, prompt: "colores urbanos realistas, concreto y metal naturales, sin neón" },
  { id: "hyper-col-balance-018", title: "Verdes naturales", summary: "Evita radioactivo.", area: AREA, category: CATEGORY, prompt: "verdes naturales, sin verde radioactivo, variación orgánica" },
  { id: "hyper-col-balance-019", title: "Azules naturales", summary: "Sin cian raro.", area: AREA, category: CATEGORY, prompt: "azules naturales, sin cian artificial, cielo con gradiente real" },
  { id: "hyper-col-balance-020", title: "Rojos controlados", summary: "Sin clipping.", area: AREA, category: CATEGORY, prompt: "rojos controlados, sin clipping, detalle en rojos intensos" },

  { id: "hyper-col-balance-021", title: "Evitar banding", summary: "Degradados limpios.", area: AREA, category: CATEGORY, prompt: "degradados suaves sin banding, transiciones limpias" },
  { id: "hyper-col-balance-022", title: "Evitar saturación selectiva rara", summary: "Consistencia.", area: AREA, category: CATEGORY, prompt: "saturación consistente, sin colores ‘saltando’ artificialmente" },
  { id: "hyper-col-balance-023", title: "Evitar oversharpen y halos", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "sin halos por enfoque, nitidez natural, bordes limpios" },
  { id: "hyper-col-balance-024", title: "Blancos limpios", summary: "Sin amarillo/verde.", area: AREA, category: CATEGORY, prompt: "blancos limpios, sin dominante verde/amarilla, detalles conservados" },
  { id: "hyper-col-balance-025", title: "Grises neutros", summary: "Referencia.", area: AREA, category: CATEGORY, prompt: "grises neutros, sin dominantes, contraste realista" },
  { id: "hyper-col-balance-026", title: "Tonos piel (oscura) correctos", summary: "Sin ceniza.", area: AREA, category: CATEGORY, prompt: "piel oscura realista, sin ‘ceniza’, subtonos creíbles" },
  { id: "hyper-col-balance-027", title: "Tonos piel (clara) correctos", summary: "Sin rosa artificial.", area: AREA, category: CATEGORY, prompt: "piel clara realista, sin rosa artificial, textura natural" },
  { id: "hyper-col-balance-028", title: "Subtonos equilibrados", summary: "Sin verde/magenta.", area: AREA, category: CATEGORY, prompt: "subtonos equilibrados, evitar dominante verde o magenta en piel" },
  { id: "hyper-col-balance-029", title: "Sombras frías naturales", summary: "No cian.", area: AREA, category: CATEGORY, prompt: "sombras ligeramente frías naturales, sin cian/teal agresivo" },
  { id: "hyper-col-balance-030", title: "Luces cálidas naturales", summary: "No naranja.", area: AREA, category: CATEGORY, prompt: "luces ligeramente cálidas naturales, sin naranja exagerado" },

  { id: "hyper-col-balance-031", title: "Paleta tierra", summary: "Orgánica.", area: AREA, category: CATEGORY, prompt: "paleta tierra natural (beige, marrón, oliva), baja saturación" },
  { id: "hyper-col-balance-032", title: "Paleta fría neutra", summary: "Tech limpio.", area: AREA, category: CATEGORY, prompt: "paleta fría neutra (grises, azules suaves), blancos limpios" },
  { id: "hyper-col-balance-033", title: "Paleta cálida neutra", summary: "Acogedor.", area: AREA, category: CATEGORY, prompt: "paleta cálida neutra (cremas, ámbar suave), piel natural" },
  { id: "hyper-col-balance-034", title: "Paleta monocromática", summary: "Elegante.", area: AREA, category: CATEGORY, prompt: "paleta monocromática sutil, variación tonal realista" },
  { id: "hyper-col-balance-035", title: "Complementario suave", summary: "Acento.", area: AREA, category: CATEGORY, prompt: "colores complementarios suaves, acento controlado, sin neón" },
  { id: "hyper-col-balance-036", title: "Acento único", summary: "Foco claro.", area: AREA, category: CATEGORY, prompt: "un solo color acento, resto neutro, sensación premium" },
  { id: "hyper-col-balance-037", title: "Baja saturación pro", summary: "Cine/arte.", area: AREA, category: CATEGORY, prompt: "baja saturación, tonos naturales, contraste suave" },
  { id: "hyper-col-balance-038", title: "Saturación media real", summary: "Foto estándar.", area: AREA, category: CATEGORY, prompt: "saturación media realista, sin oversat, buen balance" },
  { id: "hyper-col-balance-039", title: "Microcontraste sutil", summary: "Detalle sin HDR.", area: AREA, category: CATEGORY, prompt: "microcontraste sutil, detalle real, sin efecto HDR" },
  { id: "hyper-col-balance-040", title: "Curva suave", summary: "Roll-off.", area: AREA, category: CATEGORY, prompt: "curva tonal suave, roll-off natural, sombras con detalle" },

  { id: "hyper-col-balance-041", title: "Evitar look ‘AI’", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "evitar look 'AI': colores raros, piel plástica, contrastes artificiales" },
  { id: "hyper-col-balance-042", title: "Sin claridades excesivas", summary: "Textura real.", area: AREA, category: CATEGORY, prompt: "sin claridad excesiva, textura realista, piel natural" },
  { id: "hyper-col-balance-043", title: "Sin vibrance agresivo", summary: "Control.", area: AREA, category: CATEGORY, prompt: "sin vibrance agresivo, saturación natural, tonos piel correctos" },
  { id: "hyper-col-balance-044", title: "Tonos pastel reales", summary: "Suaves.", area: AREA, category: CATEGORY, prompt: "tonos pastel reales, sin sensación de ilustración" },
  { id: "hyper-col-balance-045", title: "Neutralidad de papel", summary: "E-commerce/estudio.", area: AREA, category: CATEGORY, prompt: "neutralidad tipo estudio/papel, blancos consistentes" },
  { id: "hyper-col-balance-046", title: "Control de dominante verde", summary: "Piel.", area: AREA, category: CATEGORY, prompt: "corregir dominante verde, piel natural, blancos limpios" },
  { id: "hyper-col-balance-047", title: "Control de dominante magenta", summary: "Piel.", area: AREA, category: CATEGORY, prompt: "corregir dominante magenta, piel natural, sombras limpias" },
  { id: "hyper-col-balance-048", title: "Control de dominante amarilla", summary: "No sepia.", area: AREA, category: CATEGORY, prompt: "evitar dominante amarilla, calidez realista, sin sepia" },
  { id: "hyper-col-balance-049", title: "Control de dominante azul", summary: "No hielo.", area: AREA, category: CATEGORY, prompt: "evitar dominante azul, blancos neutros, piel creíble" },
  { id: "hyper-col-balance-050", title: "Color fidelity", summary: "Fiel a realidad.", area: AREA, category: CATEGORY, prompt: "fidelidad de color, tonos consistentes con la realidad" },

  { id: "hyper-col-balance-051", title: "Skin tone roll-off", summary: "Luces en piel.", area: AREA, category: CATEGORY, prompt: "roll-off natural en altas luces de piel, sin quemados" },
  { id: "hyper-col-balance-052", title: "Rosa natural en mejillas", summary: "Sutil.", area: AREA, category: CATEGORY, prompt: "rubor natural sutil, sin maquillaje excesivo" },
  { id: "hyper-col-balance-053", title: "Labios naturales", summary: "Sin neon.", area: AREA, category: CATEGORY, prompt: "color de labios natural, sin saturación falsa" },
  { id: "hyper-col-balance-054", title: "Dientes naturales", summary: "Sin blanco brillante.", area: AREA, category: CATEGORY, prompt: "dientes de color natural, no blanco fluorescente" },
  { id: "hyper-col-balance-055", title: "Ojos naturales", summary: "Sin iris neón.", area: AREA, category: CATEGORY, prompt: "iris con color natural, sin neón, reflejos coherentes" },
  { id: "hyper-col-balance-056", title: "Cabello real", summary: "Sin negros empastados.", area: AREA, category: CATEGORY, prompt: "cabello con detalle tonal, sin negros empastados" },
  { id: "hyper-col-balance-057", title: "Metal real", summary: "Reflejos correctos.", area: AREA, category: CATEGORY, prompt: "metales con color real, sin reflejos imposibles" },
  { id: "hyper-col-balance-058", title: "Madera real", summary: "No naranja.", area: AREA, category: CATEGORY, prompt: "madera con tonos naturales, sin naranja saturado" },
  { id: "hyper-col-balance-059", title: "Concreto real", summary: "Gris correcto.", area: AREA, category: CATEGORY, prompt: "concreto con grises reales, variación natural, sin verde" },
  { id: "hyper-col-balance-060", title: "Verde follaje real", summary: "Variedad.", area: AREA, category: CATEGORY, prompt: "follaje con variedad de verdes, sin tono uniforme" },

  { id: "hyper-col-balance-061", title: "Cielo real", summary: "Gradiente natural.", area: AREA, category: CATEGORY, prompt: "cielo con gradiente natural, sin banding, color real" },
  { id: "hyper-col-balance-062", title: "Hora dorada real", summary: "Calidez real.", area: AREA, category: CATEGORY, prompt: "hora dorada realista, calidez natural, sombras suaves" },
  { id: "hyper-col-balance-063", title: "Hora azul real", summary: "Azul suave.", area: AREA, category: CATEGORY, prompt: "hora azul realista, azules suaves, luces cálidas puntuales" },
  { id: "hyper-col-balance-064", title: "Nublado real", summary: "Difuso.", area: AREA, category: CATEGORY, prompt: "luz nublada, colores ligeramente apagados, realista" },
  { id: "hyper-col-balance-065", title: "Interior tungsteno real", summary: "Cálido interior.", area: AREA, category: CATEGORY, prompt: "interior con luz tungsteno realista, sin amarillo extremo" },
  { id: "hyper-col-balance-066", title: "LED real", summary: "Sin verde raro.", area: AREA, category: CATEGORY, prompt: "iluminación LED realista, sin dominante verde, blancos limpios" },
  { id: "hyper-col-balance-067", title: "Neón real (controlado)", summary: "Sin cyber exagerado.", area: AREA, category: CATEGORY, prompt: "neón real controlado, exposición correcta, sin saturación absurda" },
  { id: "hyper-col-balance-068", title: "Backlight real", summary: "Contorno.", area: AREA, category: CATEGORY, prompt: "contraluz realista, detalles conservados, flare mínimo" },
  { id: "hyper-col-balance-069", title: "Sombras suaves", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "sombras suaves naturales, sin negros aplastados" },
  { id: "hyper-col-balance-070", title: "Sombras marcadas", summary: "Sol fuerte.", area: AREA, category: CATEGORY, prompt: "sombras marcadas realistas, detalle conservado, sin crush" },

  { id: "hyper-col-balance-071", title: "Producto blanco correcto", summary: "Sin gris.", area: AREA, category: CATEGORY, prompt: "producto blanco con detalle, blanco verdadero, sin gris sucio" },
  { id: "hyper-col-balance-072", title: "Producto negro con detalle", summary: "No empastado.", area: AREA, category: CATEGORY, prompt: "producto negro con detalle, reflejos sutiles, sin empastar" },
  { id: "hyper-col-balance-073", title: "Color de marca fiel", summary: "Exactitud.", area: AREA, category: CATEGORY, prompt: "color fiel a referencia de marca, sin desviación de tono" },
  { id: "hyper-col-balance-074", title: "Fondo neutro", summary: "Gris suave.", area: AREA, category: CATEGORY, prompt: "fondo neutro (gris suave), sujeto con color real" },
  { id: "hyper-col-balance-075", title: "Fondo cálido neutro", summary: "Beige.", area: AREA, category: CATEGORY, prompt: "fondo cálido neutro (beige/crema), piel natural" },
  { id: "hyper-col-balance-076", title: "Fondo frío neutro", summary: "Azul gris.", area: AREA, category: CATEGORY, prompt: "fondo frío neutro (azul/gris), blancos limpios" },
  { id: "hyper-col-balance-077", title: "Acento rojo real", summary: "No neón.", area: AREA, category: CATEGORY, prompt: "acento rojo realista, sin saturación neón, detalle preservado" },
  { id: "hyper-col-balance-078", title: "Acento verde real", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "acento verde realista, sin radioactivo, variación tonal" },
  { id: "hyper-col-balance-079", title: "Acento azul real", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "acento azul realista, sin cian excesivo" },
  { id: "hyper-col-balance-080", title: "Acento dorado real", summary: "Metal.", area: AREA, category: CATEGORY, prompt: "acento dorado realista, reflejos correctos, sin amarillo plano" },

  { id: "hyper-col-balance-081", title: "Color uniforme NO", summary: "Varía.", area: AREA, category: CATEGORY, prompt: "variación natural de color, evitar uniformidad artificial" },
  { id: "hyper-col-balance-082", title: "Evitar piel ‘porcelana’", summary: "Textura.", area: AREA, category: CATEGORY, prompt: "evitar piel porcelana, mantener variación y textura real" },
  { id: "hyper-col-balance-083", title: "Evitar piel ‘plástica’", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "evitar piel plástica, especular natural, microtextura" },
  { id: "hyper-col-balance-084", title: "Evitar cielo falso", summary: "Real.", area: AREA, category: CATEGORY, prompt: "evitar cielos falsos, mantener gradiente y color realistas" },
  { id: "hyper-col-balance-085", title: "Evitar sombras verdosas", summary: "Limpias.", area: AREA, category: CATEGORY, prompt: "evitar sombras verdosas, neutralizar dominante" },
  { id: "hyper-col-balance-086", title: "Evitar highlights cian", summary: "Control.", area: AREA, category: CATEGORY, prompt: "evitar altas luces cian, blancos naturales" },
  { id: "hyper-col-balance-087", title: "Evitar posterización", summary: "Suave.", area: AREA, category: CATEGORY, prompt: "transiciones tonales suaves, sin posterización" },
  { id: "hyper-col-balance-088", title: "Evitar oversat en food", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "evitar oversat en comida, tonos realistas, apetitoso creíble" },
  { id: "hyper-col-balance-089", title: "Evitar naranja en piel", summary: "Piel.", area: AREA, category: CATEGORY, prompt: "evitar piel naranja, subtonos equilibrados" },
  { id: "hyper-col-balance-090", title: "Evitar magenta en piel", summary: "Piel.", area: AREA, category: CATEGORY, prompt: "evitar dominante magenta en piel, mantener naturalidad" },

  { id: "hyper-col-balance-091", title: "Balance por luz principal", summary: "Consistente.", area: AREA, category: CATEGORY, prompt: "balance de blancos acorde a luz principal, consistencia global" },
  { id: "hyper-col-balance-092", title: "Color con referencia gris", summary: "Neutro.", area: AREA, category: CATEGORY, prompt: "neutralidad tipo carta gris, blancos y grises coherentes" },
  { id: "hyper-col-balance-093", title: "Skin separation", summary: "Piel separada.", area: AREA, category: CATEGORY, prompt: "separación tonal de piel vs fondo, natural, sin recortes" },
  { id: "hyper-col-balance-094", title: "Color de sombras real", summary: "Ambiente.", area: AREA, category: CATEGORY, prompt: "color de sombra coherente con ambiente, no negro puro" },
  { id: "hyper-col-balance-095", title: "Color de reflejos real", summary: "Entorno.", area: AREA, category: CATEGORY, prompt: "reflejos toman color del entorno, física coherente" },
  { id: "hyper-col-balance-096", title: "Dominantes mínimas", summary: "Pro.", area: AREA, category: CATEGORY, prompt: "dominantes mínimas y controladas, realismo" },
  { id: "hyper-col-balance-097", title: "Natural film feel", summary: "Leve película.", area: AREA, category: CATEGORY, prompt: "sensación leve de película, tonos naturales, sin filtros agresivos" },
  { id: "hyper-col-balance-098", title: "Color limpio + detalle", summary: "Equilibrio.", area: AREA, category: CATEGORY, prompt: "color limpio con detalle, sin denoise excesivo" },
  { id: "hyper-col-balance-099", title: "Textura con color real", summary: "Material creíble.", area: AREA, category: CATEGORY, prompt: "texturas con color realista, sin tintes artificiales" },
  { id: "hyper-col-balance-100", title: "Resultado fotográfico", summary: "Cierra look.", area: AREA, category: CATEGORY, prompt: "resultado fotográfico realista, sin estilo ilustración, color natural" },
];
