// src/lib/prompts/hyperrealism-text/color.js
// Unikalny obszar i kategoria dla CAŁEGO tego pliku:
const AREA = "Kolor";
const CATEGORY = "Balans";

export const hyperrealismTextPromptsColor = [
  { id: "hyper-col-balance-001", title: "Balans neutralny", summary: "Realny kolor bez dominant.", area: AREA, category: CATEGORY, prompt: "neutralny balans bieli, naturalne kolory, bez dominant" },
  { id: "hyper-col-balance-002", title: "WB lekko ciepły", summary: "Realistyczne ciepło.", area: AREA, category: CATEGORY, prompt: "delikatnie ciepła temperatura, wiarygodna skóra, bez nadmiernego zażółcenia" },
  { id: "hyper-col-balance-003", title: "WB lekko chłodny", summary: "Realistyczna świeżość.", area: AREA, category: CATEGORY, prompt: "delikatnie chłodna temperatura, czyste biele, bez sztucznego błękitu" },
  { id: "hyper-col-balance-004", title: "Naturalne tony skóry", summary: "Priorytet: skóra.", area: AREA, category: CATEGORY, prompt: "naturalne i wiarygodne tony skóry, bez dziwnej magenty/zieleni" },
  { id: "hyper-col-balance-005", title: "Powściągliwa saturacja", summary: "Bez looku HDR.", area: AREA, category: CATEGORY, prompt: "powściągliwa saturacja, realistyczny kontrast, bez przesadnego HDR" },
  { id: "hyper-col-balance-006", title: "Miękki kontrast", summary: "Editorial.", area: AREA, category: CATEGORY, prompt: "miękki kontrast, otwarte cienie, naturalny roll-off w światłach" },
  { id: "hyper-col-balance-007", title: "Średni kontrast", summary: "Standardowe foto.", area: AREA, category: CATEGORY, prompt: "realistyczny średni kontrast, kontrolowane czernie, bez crush" },
  { id: "hyper-col-balance-008", title: "Chronione światła", summary: "Bez przepaleń.", area: AREA, category: CATEGORY, prompt: "chronione światła, biele z detalem, bez clippingu" },
  { id: "hyper-col-balance-009", title: "Czyste cienie", summary: "Bez chromatycznego ‘błota’.", area: AREA, category: CATEGORY, prompt: "czyste cienie, bez chromatycznego ‘błota’, zachowany detal" },
  { id: "hyper-col-balance-010", title: "Naturalne czernie", summary: "Bez czystej czerni.", area: AREA, category: CATEGORY, prompt: "naturalne czernie (nie idealnie czarne), subtelny detal w cieniach" },

  { id: "hyper-col-balance-011", title: "Subtelny grading filmowy", summary: "Bez przesady.", area: AREA, category: CATEGORY, prompt: "subtelny filmowy color grading, bez przesadnego teal-orange" },
  { id: "hyper-col-balance-012", title: "Teal-orange BARDZO delikatnie", summary: "Tylko dotyk.", area: AREA, category: CATEGORY, prompt: "teal-orange bardzo delikatnie, naturalna skóra, cienie ledwo chłodne" },
  { id: "hyper-col-balance-013", title: "Editorial / magazyn", summary: "Premium.", area: AREA, category: CATEGORY, prompt: "editorial magazynowy look, naturalne kolory, miękka separacja" },
  { id: "hyper-col-balance-014", title: "Look dokumentalny", summary: "Surowy realizm.", area: AREA, category: CATEGORY, prompt: "look dokumentalny, uczciwe kolory, umiarkowany kontrast" },
  { id: "hyper-col-balance-015", title: "Czysty look e-commerce", summary: "Wierny produkt.", area: AREA, category: CATEGORY, prompt: "wierny kolor produktu, neutralne biele, bez dominant" },
  { id: "hyper-col-balance-016", title: "Naturalny look food", summary: "Apetyt real.", area: AREA, category: CATEGORY, prompt: "naturalny kolor jedzenia, lekko ciepły balans, bez fałszywej saturacji" },
  { id: "hyper-col-balance-017", title: "Realny look miejski", summary: "Ulica realistyczna.", area: AREA, category: CATEGORY, prompt: "realistyczne miejskie kolory, naturalny beton i metal, bez neonów" },
  { id: "hyper-col-balance-018", title: "Naturalne zielenie", summary: "Bez radioaktywnego.", area: AREA, category: CATEGORY, prompt: "naturalne zielenie, bez radioaktywnej zieleni, organiczna zmienność" },
  { id: "hyper-col-balance-019", title: "Naturalne błękity", summary: "Bez dziwnego cyjanu.", area: AREA, category: CATEGORY, prompt: "naturalne błękity, bez sztucznego cyjanu, niebo z realnym gradientem" },
  { id: "hyper-col-balance-020", title: "Kontrolowane czerwienie", summary: "Bez clippingu.", area: AREA, category: CATEGORY, prompt: "kontrolowane czerwienie, bez clippingu, detal w intensywnych czerwieniach" },

  { id: "hyper-col-balance-021", title: "Unikać bandingu", summary: "Czyste przejścia.", area: AREA, category: CATEGORY, prompt: "gładkie gradienty bez bandingu, czyste przejścia" },
  { id: "hyper-col-balance-022", title: "Unikać dziwnej selektywnej saturacji", summary: "Spójność.", area: AREA, category: CATEGORY, prompt: "spójna saturacja, bez sztucznie ‘wyskakujących’ kolorów" },
  { id: "hyper-col-balance-023", title: "Unikać oversharpen i halo", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "bez halo od wyostrzania, naturalna ostrość, czyste krawędzie" },
  { id: "hyper-col-balance-024", title: "Czyste biele", summary: "Bez żółci/zieleni.", area: AREA, category: CATEGORY, prompt: "czyste biele, bez zielonej/żółtej dominanty, zachowane detale" },
  { id: "hyper-col-balance-025", title: "Neutralne szarości", summary: "Punkt odniesienia.", area: AREA, category: CATEGORY, prompt: "neutralne szarości, bez dominant, realistyczny kontrast" },
  { id: "hyper-col-balance-026", title: "Poprawne tony skóry (ciemnej)", summary: "Bez ‘popiołu’.", area: AREA, category: CATEGORY, prompt: "realistyczna ciemna skóra, bez ‘popiołu’, wiarygodne podtony" },
  { id: "hyper-col-balance-027", title: "Poprawne tony skóry (jasnej)", summary: "Bez sztucznego różu.", area: AREA, category: CATEGORY, prompt: "realistyczna jasna skóra, bez sztucznego różu, naturalna tekstura" },
  { id: "hyper-col-balance-028", title: "Zbalansowane podtony", summary: "Bez zieleni/magenty.", area: AREA, category: CATEGORY, prompt: "zbalansowane podtony, unikać zielonej lub magentowej dominanty w skórze" },
  { id: "hyper-col-balance-029", title: "Naturalnie chłodne cienie", summary: "Nie cyjan.", area: AREA, category: CATEGORY, prompt: "lekko chłodne, naturalne cienie, bez agresywnego cyjanu/teal" },
  { id: "hyper-col-balance-030", title: "Naturalnie ciepłe światła", summary: "Nie pomarańcz.", area: AREA, category: CATEGORY, prompt: "lekko ciepłe, naturalne światła, bez przesadnego pomarańczu" },

  { id: "hyper-col-balance-031", title: "Paleta ziemi", summary: "Organiczna.", area: AREA, category: CATEGORY, prompt: "naturalna paleta ziemi (beż, brąz, oliwka), niska saturacja" },
  { id: "hyper-col-balance-032", title: "Chłodna neutralna paleta", summary: "Czysty tech.", area: AREA, category: CATEGORY, prompt: "chłodna neutralna paleta (szarości, miękkie błękity), czyste biele" },
  { id: "hyper-col-balance-033", title: "Ciepła neutralna paleta", summary: "Przytulnie.", area: AREA, category: CATEGORY, prompt: "ciepła neutralna paleta (kremy, miękki bursztyn), naturalna skóra" },
  { id: "hyper-col-balance-034", title: "Paleta monochromatyczna", summary: "Elegancko.", area: AREA, category: CATEGORY, prompt: "subtelna paleta monochromatyczna, realistyczna zmienność tonalna" },
  { id: "hyper-col-balance-035", title: "Delikatne barwy dopełniające", summary: "Akcent.", area: AREA, category: CATEGORY, prompt: "delikatne kolory dopełniające, kontrolowany akcent, bez neonów" },
  { id: "hyper-col-balance-036", title: "Jeden akcent", summary: "Jasny fokus.", area: AREA, category: CATEGORY, prompt: "jeden kolor akcentowy, reszta neutralna, premium vibe" },
  { id: "hyper-col-balance-037", title: "Pro niska saturacja", summary: "Kino/sztuka.", area: AREA, category: CATEGORY, prompt: "niska saturacja, naturalne tony, miękki kontrast" },
  { id: "hyper-col-balance-038", title: "Realna średnia saturacja", summary: "Standardowe foto.", area: AREA, category: CATEGORY, prompt: "realistyczna średnia saturacja, bez oversat, dobry balans" },
  { id: "hyper-col-balance-039", title: "Subtelny mikro-kontrast", summary: "Detal bez HDR.", area: AREA, category: CATEGORY, prompt: "subtelny mikro-kontrast, realny detal, bez efektu HDR" },
  { id: "hyper-col-balance-040", title: "Miękka krzywa tonalna", summary: "Roll-off.", area: AREA, category: CATEGORY, prompt: "miękka krzywa tonalna, naturalny roll-off, cienie z detalem" },

  { id: "hyper-col-balance-041", title: "Unikać looku ‘AI’", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "unikać looku 'AI': dziwne kolory, plastikowa skóra, sztuczne kontrasty" },
  { id: "hyper-col-balance-042", title: "Bez nadmiernej klarowności", summary: "Realna tekstura.", area: AREA, category: CATEGORY, prompt: "bez nadmiernej klarowności, realistyczna tekstura, naturalna skóra" },
  { id: "hyper-col-balance-043", title: "Bez agresywnego vibrance", summary: "Kontrola.", area: AREA, category: CATEGORY, prompt: "bez agresywnego vibrance, naturalna saturacja, poprawne tony skóry" },
  { id: "hyper-col-balance-044", title: "Realne pastele", summary: "Miękko.", area: AREA, category: CATEGORY, prompt: "realne pastelowe tony, bez wrażenia ilustracji" },
  { id: "hyper-col-balance-045", title: "Neutralność jak papier", summary: "E-commerce/studio.", area: AREA, category: CATEGORY, prompt: "neutralność jak w studio/papierze, spójne biele" },
  { id: "hyper-col-balance-046", title: "Kontrola zielonej dominanty", summary: "Skóra.", area: AREA, category: CATEGORY, prompt: "korygować zieloną dominantę, naturalna skóra, czyste biele" },
  { id: "hyper-col-balance-047", title: "Kontrola magentowej dominanty", summary: "Skóra.", area: AREA, category: CATEGORY, prompt: "korygować magentową dominantę, naturalna skóra, czyste cienie" },
  { id: "hyper-col-balance-048", title: "Kontrola żółtej dominanty", summary: "Bez sepii.", area: AREA, category: CATEGORY, prompt: "unikać żółtej dominanty, realistyczne ciepło, bez sepii" },
  { id: "hyper-col-balance-049", title: "Kontrola niebieskiej dominanty", summary: "Bez lodu.", area: AREA, category: CATEGORY, prompt: "unikać niebieskiej dominanty, neutralne biele, wiarygodna skóra" },
  { id: "hyper-col-balance-050", title: "Wierność koloru", summary: "Wierne rzeczywistości.", area: AREA, category: CATEGORY, prompt: "wierność koloru, tony spójne z rzeczywistością" },

  { id: "hyper-col-balance-051", title: "Roll-off tonów skóry", summary: "Światła na skórze.", area: AREA, category: CATEGORY, prompt: "naturalny roll-off w światłach na skórze, bez przepaleń" },
  { id: "hyper-col-balance-052", title: "Naturalny róż na policzkach", summary: "Subtelnie.", area: AREA, category: CATEGORY, prompt: "subtelny naturalny rumieniec, bez nadmiernego makijażu" },
  { id: "hyper-col-balance-053", title: "Naturalne usta", summary: "Bez neonów.", area: AREA, category: CATEGORY, prompt: "naturalny kolor ust, bez fałszywej saturacji" },
  { id: "hyper-col-balance-054", title: "Naturalne zęby", summary: "Bez świecącej bieli.", area: AREA, category: CATEGORY, prompt: "zęby w naturalnym kolorze, nie fluorescencyjnie białe" },
  { id: "hyper-col-balance-055", title: "Naturalne oczy", summary: "Bez neonowej tęczówki.", area: AREA, category: CATEGORY, prompt: "tęczówka o naturalnym kolorze, bez neonów, spójne refleksy" },
  { id: "hyper-col-balance-056", title: "Realne włosy", summary: "Bez zalanych czerni.", area: AREA, category: CATEGORY, prompt: "włosy z detalem tonalnym, bez zalanych czerni" },
  { id: "hyper-col-balance-057", title: "Realny metal", summary: "Poprawne odbicia.", area: AREA, category: CATEGORY, prompt: "metale o realnym kolorze, bez niemożliwych odbić" },
  { id: "hyper-col-balance-058", title: "Realne drewno", summary: "Bez pomarańczu.", area: AREA, category: CATEGORY, prompt: "drewno w naturalnych tonach, bez nasyconego pomarańczu" },
  { id: "hyper-col-balance-059", title: "Realny beton", summary: "Poprawna szarość.", area: AREA, category: CATEGORY, prompt: "beton z realnymi szarościami, naturalna zmienność, bez zieleni" },
  { id: "hyper-col-balance-060", title: "Realna zieleń liści", summary: "Różnorodność.", area: AREA, category: CATEGORY, prompt: "liście z różnorodnymi zieleniami, bez jednolitego tonu" },

  { id: "hyper-col-balance-061", title: "Realne niebo", summary: "Naturalny gradient.", area: AREA, category: CATEGORY, prompt: "niebo z naturalnym gradientem, bez bandingu, realny kolor" },
  { id: "hyper-col-balance-062", title: "Realna złota godzina", summary: "Prawdziwe ciepło.", area: AREA, category: CATEGORY, prompt: "realistyczna złota godzina, naturalne ciepło, miękkie cienie" },
  { id: "hyper-col-balance-063", title: "Realna niebieska godzina", summary: "Miękki błękit.", area: AREA, category: CATEGORY, prompt: "realistyczna niebieska godzina, miękkie błękity, punktowe ciepłe światła" },
  { id: "hyper-col-balance-064", title: "Realne zachmurzenie", summary: "Rozproszenie.", area: AREA, category: CATEGORY, prompt: "światło pochmurne, lekko stonowane kolory, realistycznie" },
  { id: "hyper-col-balance-065", title: "Realne wnętrze tungsten", summary: "Ciepło w środku.", area: AREA, category: CATEGORY, prompt: "wnętrze z realistycznym światłem tungsten, bez skrajnej żółci" },
  { id: "hyper-col-balance-066", title: "Realne LED", summary: "Bez dziwnej zieleni.", area: AREA, category: CATEGORY, prompt: "realistyczne oświetlenie LED, bez zielonej dominanty, czyste biele" },
  { id: "hyper-col-balance-067", title: "Realny neon (kontrolowany)", summary: "Bez cyber przesady.", area: AREA, category: CATEGORY, prompt: "kontrolowany realny neon, poprawna ekspozycja, bez absurdalnej saturacji" },
  { id: "hyper-col-balance-068", title: "Realny kontr-światło", summary: "Kontur.", area: AREA, category: CATEGORY, prompt: "realistyczny kontr-światło, zachowane detale, minimalny flare" },
  { id: "hyper-col-balance-069", title: "Miękkie cienie", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "naturalne miękkie cienie, bez zgniecionych czerni" },
  { id: "hyper-col-balance-070", title: "Wyraźne cienie", summary: "Mocne słońce.", area: AREA, category: CATEGORY, prompt: "realistycznie wyraźne cienie, zachowany detal, bez crush" },

  { id: "hyper-col-balance-071", title: "Poprawna biel produktu", summary: "Bez szarości.", area: AREA, category: CATEGORY, prompt: "biały produkt z detalem, prawdziwa biel, bez brudnej szarości" },
  { id: "hyper-col-balance-072", title: "Czarny produkt z detalem", summary: "Nie zalany.", area: AREA, category: CATEGORY, prompt: "czarny produkt z detalem, subtelne refleksy, bez zalewania" },
  { id: "hyper-col-balance-073", title: "Wierny kolor marki", summary: "Dokładność.", area: AREA, category: CATEGORY, prompt: "kolor zgodny z referencją marki, bez odchyłek tonu" },
  { id: "hyper-col-balance-074", title: "Tło neutralne", summary: "Miękka szarość.", area: AREA, category: CATEGORY, prompt: "neutralne tło (miękka szarość), obiekt z realnym kolorem" },
  { id: "hyper-col-balance-075", title: "Tło ciepło-neutralne", summary: "Beż.", area: AREA, category: CATEGORY, prompt: "ciepło-neutralne tło (beż/krem), naturalna skóra" },
  { id: "hyper-col-balance-076", title: "Tło chłodno-neutralne", summary: "Błękitnoszare.", area: AREA, category: CATEGORY, prompt: "chłodno-neutralne tło (błękit/szarość), czyste biele" },
  { id: "hyper-col-balance-077", title: "Realny czerwony akcent", summary: "Bez neonów.", area: AREA, category: CATEGORY, prompt: "realistyczny czerwony akcent, bez neonowej saturacji, zachowany detal" },
  { id: "hyper-col-balance-078", title: "Realny zielony akcent", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "realistyczny zielony akcent, bez radioaktywnego, zmienność tonalna" },
  { id: "hyper-col-balance-079", title: "Realny niebieski akcent", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "realistyczny niebieski akcent, bez nadmiernego cyjanu" },
  { id: "hyper-col-balance-080", title: "Realny złoty akcent", summary: "Metal.", area: AREA, category: CATEGORY, prompt: "realistyczny złoty akcent, poprawne refleksy, bez płaskiej żółci" },

  { id: "hyper-col-balance-081", title: "Jednolity kolor? NIE", summary: "Zmienność.", area: AREA, category: CATEGORY, prompt: "naturalna zmienność koloru, unikać sztucznej jednorodności" },
  { id: "hyper-col-balance-082", title: "Unikać skóry ‘porcelanowej’", summary: "Tekstura.", area: AREA, category: CATEGORY, prompt: "unikać porcelanowej skóry, zachować zmienność i realną teksturę" },
  { id: "hyper-col-balance-083", title: "Unikać skóry ‘plastikowej’", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "unikać plastikowej skóry, naturalny specular, mikro-tekstura" },
  { id: "hyper-col-balance-084", title: "Unikać fałszywego nieba", summary: "Real.", area: AREA, category: CATEGORY, prompt: "unikać sztucznego nieba, zachować realistyczny gradient i kolor" },
  { id: "hyper-col-balance-085", title: "Unikać zielonkawych cieni", summary: "Czyste.", area: AREA, category: CATEGORY, prompt: "unikać zielonkawych cieni, neutralizować dominantę" },
  { id: "hyper-col-balance-086", title: "Unikać cyjanowych highlightów", summary: "Kontrola.", area: AREA, category: CATEGORY, prompt: "unikać cyjanowych świateł, naturalne biele" },
  { id: "hyper-col-balance-087", title: "Unikać posteryzacji", summary: "Gładko.", area: AREA, category: CATEGORY, prompt: "gładkie przejścia tonalne, bez posteryzacji" },
  { id: "hyper-col-balance-088", title: "Unikać oversat w food", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "unikać oversat w jedzeniu, realistyczne tony, wiarygodnie apetyczne" },
  { id: "hyper-col-balance-089", title: "Unikać pomarańczowej skóry", summary: "Skóra.", area: AREA, category: CATEGORY, prompt: "unikać pomarańczowej skóry, zbalansowane podtony" },
  { id: "hyper-col-balance-090", title: "Unikać magenty w skórze", summary: "Skóra.", area: AREA, category: CATEGORY, prompt: "unikać magentowej dominanty w skórze, zachować naturalność" },

  { id: "hyper-col-balance-091", title: "Balans do światła głównego", summary: "Spójnie.", area: AREA, category: CATEGORY, prompt: "balans bieli zgodny ze światłem głównym, globalna spójność" },
  { id: "hyper-col-balance-092", title: "Kolor z referencją szarości", summary: "Neutralnie.", area: AREA, category: CATEGORY, prompt: "neutralność jak z karty szarości, spójne biele i szarości" },
  { id: "hyper-col-balance-093", title: "Separacja skóry", summary: "Skóra od tła.", area: AREA, category: CATEGORY, prompt: "naturalna separacja tonalna skóry vs tło, bez wycięć" },
  { id: "hyper-col-balance-094", title: "Realny kolor cieni", summary: "Atmosfera.", area: AREA, category: CATEGORY, prompt: "kolor cieni spójny z otoczeniem, nie czysta czerń" },
  { id: "hyper-col-balance-095", title: "Realny kolor odbić", summary: "Otoczenie.", area: AREA, category: CATEGORY, prompt: "odbi cia przejmują kolor otoczenia, spójna fizyka" },
  { id: "hyper-col-balance-096", title: "Minimalne dominanty", summary: "Pro.", area: AREA, category: CATEGORY, prompt: "dominanty minimalne i kontrolowane, realizm" },
  { id: "hyper-col-balance-097", title: "Naturalny film feel", summary: "Lekko filmowo.", area: AREA, category: CATEGORY, prompt: "lekka filmowa wrażliwość, naturalne tony, bez agresywnych filtrów" },
  { id: "hyper-col-balance-098", title: "Czysty kolor + detal", summary: "Balans.", area: AREA, category: CATEGORY, prompt: "czysty kolor z detalem, bez nadmiernego denoise" },
  { id: "hyper-col-balance-099", title: "Tekstura z realnym kolorem", summary: "Wiarygodny materiał.", area: AREA, category: CATEGORY, prompt: "tekstury z realistycznym kolorem, bez sztucznych tintów" },
  { id: "hyper-col-balance-100", title: "Efekt fotograficzny", summary: "Finalny look.", area: AREA, category: CATEGORY, prompt: "realistyczny efekt fotograficzny, bez stylu ilustracji, naturalny kolor" },
];
