// src/lib/prompts/hyperrealism-text/composicion.js
// Unikalny obszar i kategoria dla CAŁEGO tego pliku:
const AREA = "Kompozycja";
const CATEGORY = "Kadrowanie";

export const hyperrealismTextPromptsComposicion = [
  { id: "hyper-comp-encadre-001", title: "Zasada trójpodziału", summary: "Klasyczny, zbalansowany.", area: AREA, category: CATEGORY, prompt: "kompozycja wg zasady trójpodziału, naturalna równowaga" },
  { id: "hyper-comp-encadre-002", title: "Centrowanie editorial", summary: "Czysty minimal.", area: AREA, category: CATEGORY, prompt: "obiekt w centrum, czyste kadrowanie editorial, subtelna symetria" },
  { id: "hyper-comp-encadre-003", title: "Idealna symetria", summary: "Porządek wizualny.", area: AREA, category: CATEGORY, prompt: "idealna symetria, proste linie, stabilna kompozycja" },
  { id: "hyper-comp-encadre-004", title: "Kontrolowana asymetria", summary: "Bardziej dynamicznie.", area: AREA, category: CATEGORY, prompt: "kontrolowana asymetria, wyraźny punkt skupienia, balans wizualny" },
  { id: "hyper-comp-encadre-005", title: "Linie prowadzące", summary: "Prowadzi wzrok.", area: AREA, category: CATEGORY, prompt: "naturalne linie prowadzące (leading lines) w stronę obiektu" },
  { id: "hyper-comp-encadre-006", title: "Trójkąt wizualny", summary: "Pro struktura.", area: AREA, category: CATEGORY, prompt: "kompozycja w trójkąt wizualny, czytelny odbiór" },
  { id: "hyper-comp-encadre-007", title: "Warstwy: 3 plany", summary: "Realna głębia.", area: AREA, category: CATEGORY, prompt: "warstwy foreground/midground/background, naturalna głębia" },
  { id: "hyper-comp-encadre-008", title: "Naturalna rama", summary: "Frame within frame.", area: AREA, category: CATEGORY, prompt: "naturalna rama (drzwi/okno/gałęzie) na pierwszym planie" },
  { id: "hyper-comp-encadre-009", title: "Negatywna przestrzeń", summary: "Oddycha.", area: AREA, category: CATEGORY, prompt: "użycie negatywnej przestrzeni, obiekt wyróżniony, minimal" },
  { id: "hyper-comp-encadre-010", title: "Kompozycja diagonalna", summary: "Akcja.", area: AREA, category: CATEGORY, prompt: "subtelna kompozycja diagonalna, dynamika bez przesady" },

  { id: "hyper-comp-encadre-011", title: "Eye-level", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "kąt eye-level (na wysokości oczu), perspektywa ludzka" },
  { id: "hyper-comp-encadre-012", title: "Lekki niski kąt", summary: "Obecność.", area: AREA, category: CATEGORY, prompt: "lekki niski kąt (kontrapikado), realistyczne proporcje, bez deformacji" },
  { id: "hyper-comp-encadre-013", title: "Lekki wysoki kąt", summary: "Kontrola.", area: AREA, category: CATEGORY, prompt: "lekki wysoki kąt (pikado), stabilna geometria, realistycznie" },
  { id: "hyper-comp-encadre-014", title: "Ujęcie detalu", summary: "Tekstura rządzi.", area: AREA, category: CATEGORY, prompt: "ujęcie detalu, fokus na teksturę, ciasny kadr" },
  { id: "hyper-comp-encadre-015", title: "Close-up", summary: "Intymność.", area: AREA, category: CATEGORY, prompt: "close-up, twarz lub obiekt zajmuje większość kadru" },
  { id: "hyper-comp-encadre-016", title: "Plan średni", summary: "Uniwersalny.", area: AREA, category: CATEGORY, prompt: "plan średni, widoczna mowa ciała, stabilna kompozycja" },
  { id: "hyper-comp-encadre-017", title: "Plan amerykański", summary: "Kino.", area: AREA, category: CATEGORY, prompt: "plan amerykański, estetyka filmowa, czytelny odbiór" },
  { id: "hyper-comp-encadre-018", title: "Plan ogólny", summary: "Kontekst.", area: AREA, category: CATEGORY, prompt: "plan ogólny, mały obiekt, otoczenie opowiada historię" },
  { id: "hyper-comp-encadre-019", title: "Klasyczne 3/4", summary: "Głębia.", area: AREA, category: CATEGORY, prompt: "kąt 3/4, naturalna głębia, stabilna perspektywa" },
  { id: "hyper-comp-encadre-020", title: "Profil", summary: "Czysto.", area: AREA, category: CATEGORY, prompt: "wyraźny profil, czyste linie, proste tło" },

  { id: "hyper-comp-encadre-021", title: "Prosty horyzont", summary: "Unikaj krzywizny.", area: AREA, category: CATEGORY, prompt: "idealnie prosty horyzont, stabilna architektura" },
  { id: "hyper-comp-encadre-022", title: "Architektura: perspektywa 1-punktowa", summary: "Czysta perspektywa.", area: AREA, category: CATEGORY, prompt: "perspektywa jednopunktowa, kontrolowane linie zbiegu" },
  { id: "hyper-comp-encadre-023", title: "Architektura: perspektywa 2-punktowa", summary: "Miejski realizm.", area: AREA, category: CATEGORY, prompt: "perspektywa dwupunktowa, poprawne piony" },
  { id: "hyper-comp-encadre-024", title: "Proste piony", summary: "Bez ‘opadania’.", area: AREA, category: CATEGORY, prompt: "piony proste, bez widocznej dystorsji obiektywu" },
  { id: "hyper-comp-encadre-025", title: "Czyste linie", summary: "Porządek.", area: AREA, category: CATEGORY, prompt: "czyste linie, spójna geometria, bez wizualnego chaosu" },
  { id: "hyper-comp-encadre-026", title: "Fokus na obiekcie", summary: "Priorytet.", area: AREA, category: CATEGORY, prompt: "jeden punkt skupienia, nic nie konkuruje z obiektem" },
  { id: "hyper-comp-encadre-027", title: "Dwa punkty skupienia", summary: "Relacja.", area: AREA, category: CATEGORY, prompt: "dwa wyraźne punkty skupienia, mocna hierarchia wizualna" },
  { id: "hyper-comp-encadre-028", title: "Rytm wizualny", summary: "Realne wzory.", area: AREA, category: CATEGORY, prompt: "rytm wizualny przez subtelne powtórzenia, bez sztucznego wzoru" },
  { id: "hyper-comp-encadre-029", title: "Głębia przez skalę", summary: "Realne rozmiary.", area: AREA, category: CATEGORY, prompt: "głębia przez skalę (bliskie elementy większe, dalekie mniejsze)" },
  { id: "hyper-comp-encadre-030", title: "Warstwowanie z pierwszym planem", summary: "Immersja.", area: AREA, category: CATEGORY, prompt: "element na pierwszym planie lekko poza ostrością, realna immersja" },

  { id: "hyper-comp-encadre-031", title: "Ciasny kadr", summary: "Uderzenie.", area: AREA, category: CATEGORY, prompt: "ciasny kadr, bez zbędnego powietrza, mocny efekt" },
  { id: "hyper-comp-encadre-032", title: "Kadr z przestrzenią", summary: "Elegancko.", area: AREA, category: CATEGORY, prompt: "kadr z przestrzenią dookoła, wrażenie premium" },
  { id: "hyper-comp-encadre-033", title: "Poprawny headroom", summary: "Proporcje.", area: AREA, category: CATEGORY, prompt: "poprawny headroom (naturalna przestrzeń u góry), bez dziwnych cięć" },
  { id: "hyper-comp-encadre-034", title: "Bez niezręcznych cięć", summary: "Ciało ok.", area: AREA, category: CATEGORY, prompt: "unikać cięcia w stawach (kostki, nadgarstki), czyste kadrowanie" },
  { id: "hyper-comp-encadre-035", title: "Ujęcie przy ziemi", summary: "Tekstura.", area: AREA, category: CATEGORY, prompt: "kamera nisko przy ziemi, widoczna tekstura podłoża, realistycznie" },
  { id: "hyper-comp-encadre-036", title: "Ujęcie z wysokości stołu", summary: "Produkt.", area: AREA, category: CATEGORY, prompt: "kamera na wysokości stołu, produkt jako bohater, bez deformacji" },
  { id: "hyper-comp-encadre-037", title: "Ujęcie zza ramienia", summary: "Historia.", area: AREA, category: CATEGORY, prompt: "kąt over-the-shoulder, realistyczna narracja" },
  { id: "hyper-comp-encadre-038", title: "Ujęcie POV", summary: "Immersyjne.", area: AREA, category: CATEGORY, prompt: "punkt widzenia POV, dłonie/obiekt na pierwszym planie, realistycznie" },
  { id: "hyper-comp-encadre-039", title: "Ujęcie w lustrze", summary: "Wiarygodne odbicie.", area: AREA, category: CATEGORY, prompt: "użycie lustra ze spójnym odbiciem, bez dziwnych duplikacji" },
  { id: "hyper-comp-encadre-040", title: "Ujęcie z odbiciem", summary: "Woda/szkło.", area: AREA, category: CATEGORY, prompt: "spójne odbicia (szkło/woda), poprawna perspektywa fizyczna" },

  { id: "hyper-comp-encadre-041", title: "Szeroki filmowy kadr", summary: "Look filmowy.", area: AREA, category: CATEGORY, prompt: "szeroki kadr filmowy, spokojna kompozycja" },
  { id: "hyper-comp-encadre-042", title: "Filmowy close", summary: "Miękki dramat.", area: AREA, category: CATEGORY, prompt: "filmowy close-up, wiarygodna emocja, kontrolowany kadr" },
  { id: "hyper-comp-encadre-043", title: "Środek ciężkości", summary: "Waga wizualna.", area: AREA, category: CATEGORY, prompt: "zbalansowany wizualny środek ciężkości, stabilne odczucie" },
  { id: "hyper-comp-encadre-044", title: "Napięcie na krawędziach", summary: "Uwaga.", area: AREA, category: CATEGORY, prompt: "unikać styczności (obiekty dotykają krawędzi), wyraźna separacja" },
  { id: "hyper-comp-encadre-045", title: "Separacja od tła", summary: "Obiekt wyróżniony.", area: AREA, category: CATEGORY, prompt: "separacja obiektu od tła przez kontrast i głębię, naturalnie" },
  { id: "hyper-comp-encadre-046", title: "Czyste tło", summary: "Bez szumu.", area: AREA, category: CATEGORY, prompt: "czyste i spójne tło, bez rozpraszających elementów" },
  { id: "hyper-comp-encadre-047", title: "Tło kontekstowe", summary: "Historia.", area: AREA, category: CATEGORY, prompt: "realistyczne tło kontekstowe wzmacnia historię" },
  { id: "hyper-comp-encadre-048", title: "Miękkie elementy diagonalne", summary: "Dynamika.", area: AREA, category: CATEGORY, prompt: "subtelne elementy diagonalne, ruch bez przesady" },
  { id: "hyper-comp-encadre-049", title: "Czytelna sylwetka", summary: "Odczyt.", area: AREA, category: CATEGORY, prompt: "czytelna sylwetka obiektu, odseparowana od tła" },
  { id: "hyper-comp-encadre-050", title: "Kontrast skali", summary: "Realny impakt.", area: AREA, category: CATEGORY, prompt: "kontrast skali (duży obiekt vs mały), realistycznie" },

  { id: "hyper-comp-encadre-051", title: "Kompozycja w S", summary: "Organiczny przepływ.", area: AREA, category: CATEGORY, prompt: "kompozycja w krzywej S, organiczny przepływ wzroku" },
  { id: "hyper-comp-encadre-052", title: "Kompozycja w C", summary: "Otula obiekt.", area: AREA, category: CATEGORY, prompt: "kształt C w elementach, delikatnie otacza obiekt" },
  { id: "hyper-comp-encadre-053", title: "Złota proporcja (subtelnie)", summary: "Pro.", area: AREA, category: CATEGORY, prompt: "subtelne użycie złotej proporcji, czytelna hierarchia" },
  { id: "hyper-comp-encadre-054", title: "Nisko osadzony środek", summary: "Ciężar na dole.", area: AREA, category: CATEGORY, prompt: "waga wizualna lekko niżej, stabilność" },
  { id: "hyper-comp-encadre-055", title: "Wysoko osadzony środek", summary: "Lekkość.", area: AREA, category: CATEGORY, prompt: "waga wizualna lekko wyżej, wrażenie lekkości" },
  { id: "hyper-comp-encadre-056", title: "Dominanta i akcent", summary: "2 kolory.", area: AREA, category: CATEGORY, prompt: "dominanta + akcent (kolor/forma), prosta hierarchia" },
  { id: "hyper-comp-encadre-057", title: "Seria obiektów", summary: "Realne powtórzenie.", area: AREA, category: CATEGORY, prompt: "realistyczne powtórzenie obiektów, minimalna naturalna zmienność" },
  { id: "hyper-comp-encadre-058", title: "Tekstura jako bohater", summary: "Macro feel.", area: AREA, category: CATEGORY, prompt: "tekstura jako główny temat, kadr pod mikrodetal" },
  { id: "hyper-comp-encadre-059", title: "Historia na pierwszym planie", summary: "Rekwizyty.", area: AREA, category: CATEGORY, prompt: "rekwizyty na pierwszym planie opowiadają historię, realistycznie" },
  { id: "hyper-comp-encadre-060", title: "Historia w tle", summary: "Kontekst.", area: AREA, category: CATEGORY, prompt: "detal w tle dodaje kontekstu, nie rozprasza" },

  { id: "hyper-comp-encadre-061", title: "Trójkąt światła", summary: "Pro percepcja.", area: AREA, category: CATEGORY, prompt: "kompozycja podkreśla trójkąt światła/cienia, naturalnie" },
  { id: "hyper-comp-encadre-062", title: "Światło jako prowadzenie", summary: "Przebieg.", area: AREA, category: CATEGORY, prompt: "strefy światła prowadzą wzrok do obiektu" },
  { id: "hyper-comp-encadre-063", title: "Cienie jako rama", summary: "Kadruje.", area: AREA, category: CATEGORY, prompt: "subtelne cienie kadrują obiekt bez zasłaniania" },
  { id: "hyper-comp-encadre-064", title: "Fokus przez kontrast", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "punkt skupienia przez miękki kontrast, bez HDR" },
  { id: "hyper-comp-encadre-065", title: "Fokus przez kolor", summary: "Akcent.", area: AREA, category: CATEGORY, prompt: "punkt skupienia przez realistyczny akcent koloru" },
  { id: "hyper-comp-encadre-066", title: "Fokus przez ostrość", summary: "Hierarchia.", area: AREA, category: CATEGORY, prompt: "hierarchia przez ostrość: obiekt ostrzejszy, tło miękkie" },
  { id: "hyper-comp-encadre-067", title: "Bokeh jako separacja", summary: "DOF.", area: AREA, category: CATEGORY, prompt: "stopniowy, realistyczny bokeh do separacji planów" },
  { id: "hyper-comp-encadre-068", title: "Stopniowy spadek ostrości", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "progresywny spadek ostrości, nie sztuczny" },
  { id: "hyper-comp-encadre-069", title: "Środek poza środkiem", summary: "Dynamicznie.", area: AREA, category: CATEGORY, prompt: "obiekt poza centrum, zbalansowany kontr-ciężarem wizualnym" },
  { id: "hyper-comp-encadre-070", title: "Minimalizm pro", summary: "Mało elementów.", area: AREA, category: CATEGORY, prompt: "minimalizm: mało elementów, czysta kompozycja, realistycznie" },

  { id: "hyper-comp-encadre-071", title: "Top-down (z góry)", summary: "Realny plan z góry.", area: AREA, category: CATEGORY, prompt: "ujęcie z góry (top-down) idealnie wyrównane" },
  { id: "hyper-comp-encadre-072", title: "45° nad stołem", summary: "Food / produkt.", area: AREA, category: CATEGORY, prompt: "kąt 45° nad stołem, look editorial, realistycznie" },
  { id: "hyper-comp-encadre-073", title: "Ujęcie boczne", summary: "Profil obiektu.", area: AREA, category: CATEGORY, prompt: "ujęcie boczne, czysty profil, proste linie" },
  { id: "hyper-comp-encadre-074", title: "Częściowe makro", summary: "Fragment.", area: AREA, category: CATEGORY, prompt: "częściowe makro, kadr fragmentu z teksturą" },
  { id: "hyper-comp-encadre-075", title: "Zasada horyzontu", summary: "1/3 u góry.", area: AREA, category: CATEGORY, prompt: "horyzont w górnej lub dolnej jednej trzeciej, realistyczny krajobraz" },
  { id: "hyper-comp-encadre-076", title: "Rozmyte tło", summary: "Portret.", area: AREA, category: CATEGORY, prompt: "rozmyte tło z realistycznym bokeh, bez dziwnych wycięć" },
  { id: "hyper-comp-encadre-077", title: "Mocny foreground", summary: "Warstwy.", area: AREA, category: CATEGORY, prompt: "mocny pierwszy plan, narracyjny środkowy plan, miękkie tło" },
  { id: "hyper-comp-encadre-078", title: "Separacja światłem", summary: "Kontur.", area: AREA, category: CATEGORY, prompt: "separacja przez delikatny rim light (jeśli dotyczy), naturalny kontur" },
  { id: "hyper-comp-encadre-079", title: "Kadr z łukiem", summary: "Architektura.", area: AREA, category: CATEGORY, prompt: "łuki/struktury kadrują obiekt, poprawna perspektywa" },
  { id: "hyper-comp-encadre-080", title: "Złamany wzór", summary: "Jeden inny detal.", area: AREA, category: CATEGORY, prompt: "powtarzalny wzór z jednym wyróżniającym elementem jako fokus" },

  { id: "hyper-comp-encadre-081", title: "Czytelna historia", summary: "Jedna idea.", area: AREA, category: CATEGORY, prompt: "jedna dominująca idea wizualna, czytelna historia" },
  { id: "hyper-comp-encadre-082", title: "Hierarchia 3 poziomy", summary: "Porządek.", area: AREA, category: CATEGORY, prompt: "hierarchia wizualna: główny/drugi/trzeci plan, czytelna" },
  { id: "hyper-comp-encadre-083", title: "Bez clutteru", summary: "Unikaj bałaganu.", area: AREA, category: CATEGORY, prompt: "bez clutteru, minimalne i spójne elementy" },
  { id: "hyper-comp-encadre-084", title: "Czysty punkt zainteresowania", summary: "Nic nie rozprasza.", area: AREA, category: CATEGORY, prompt: "czysty punkt zainteresowania, bez konkurujących obiektów" },
  { id: "hyper-comp-encadre-085", title: "Skala ludzka", summary: "Real.", area: AREA, category: CATEGORY, prompt: "poprawna ludzka skala w obiektach/otoczeniu" },
  { id: "hyper-comp-encadre-086", title: "Proporcje anatomiczne", summary: "Realne ciało.", area: AREA, category: CATEGORY, prompt: "poprawne proporcje anatomiczne, bez deformacji" },
  { id: "hyper-comp-encadre-087", title: "Naturalne pozowanie", summary: "Bez sztywności.", area: AREA, category: CATEGORY, prompt: "naturalna poza (bez sztywności), wiarygodna postawa" },
  { id: "hyper-comp-encadre-088", title: "Realistyczne gesty", summary: "Wiarygodne dłonie.", area: AREA, category: CATEGORY, prompt: "realistyczne gesty dłoni/twarzy, bez dodatkowych palców" },
  { id: "hyper-comp-encadre-089", title: "Interakcja z obiektem", summary: "Realna historia.", area: AREA, category: CATEGORY, prompt: "wiarygodna interakcja obiekt–przedmiot, naturalny kontakt" },
  { id: "hyper-comp-encadre-090", title: "Zamrożona akcja", summary: "Moment.", area: AREA, category: CATEGORY, prompt: "uchwycenie momentu (akcji) z czytelną kompozycją" },

  { id: "hyper-comp-encadre-091", title: "Fokus na oczach", summary: "Top portret.", area: AREA, category: CATEGORY, prompt: "fokus na oczach, kompozycja oparta o spojrzenie" },
  { id: "hyper-comp-encadre-092", title: "Spojrzenie w przestrzeń", summary: "Kierunek.", area: AREA, category: CATEGORY, prompt: "obiekt patrzy w negatywną przestrzeń, czytelny kierunek" },
  { id: "hyper-comp-encadre-093", title: "Spojrzenie w kamerę", summary: "Połączenie.", area: AREA, category: CATEGORY, prompt: "spojrzenie w kamerę, bezpośredni kontakt, czysty kadr" },
  { id: "hyper-comp-encadre-094", title: "Produkt 3/4", summary: "Pro e-commerce.", area: AREA, category: CATEGORY, prompt: "produkt pod kątem 3/4, realistyczny cień, czyste tło" },
  { id: "hyper-comp-encadre-095", title: "Produkt w centrum", summary: "Packshot.", area: AREA, category: CATEGORY, prompt: "produkt w centrum, lekka symetria, kompozycja e-commerce" },
  { id: "hyper-comp-encadre-096", title: "Food 45°", summary: "Standard food.", area: AREA, category: CATEGORY, prompt: "kompozycja food pod 45°, minimalne propsy, look editorial" },
  { id: "hyper-comp-encadre-097", title: "Food z góry", summary: "Top view.", area: AREA, category: CATEGORY, prompt: "food z góry, idealne wyrównanie, czysty porządek" },
  { id: "hyper-comp-encadre-098", title: "Miejskie z głębią", summary: "Realna ulica.", area: AREA, category: CATEGORY, prompt: "ulica z wyraźną głębią, obiekt w trzeciej części, linie prowadzące" },
  { id: "hyper-comp-encadre-099", title: "Wnętrze z liniami", summary: "Architektura.", area: AREA, category: CATEGORY, prompt: "wnętrze z prostymi liniami, stabilna kompozycja, poprawne piony" },
  { id: "hyper-comp-encadre-100", title: "Minimal studio", summary: "Premium.", area: AREA, category: CATEGORY, prompt: "minimalne studio, czyste tło, realistyczna kompozycja premium" },
];
