// src/lib/prompts/hyperrealism-text/composicion.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Composición";
const CATEGORY = "Encadre";

export const hyperrealismTextPromptsComposicion = [
  { id: "hyper-comp-encadre-001", title: "Regla de tercios", summary: "Clásico balanceado.", area: AREA, category: CATEGORY, prompt: "composición con regla de tercios, equilibrio natural" },
  { id: "hyper-comp-encadre-002", title: "Centrado editorial", summary: "Minimal limpio.", area: AREA, category: CATEGORY, prompt: "sujeto centrado, encuadre editorial limpio, simetría sutil" },
  { id: "hyper-comp-encadre-003", title: "Simetría perfecta", summary: "Orden visual.", area: AREA, category: CATEGORY, prompt: "simetría perfecta, líneas rectas, composición estable" },
  { id: "hyper-comp-encadre-004", title: "Asimetría controlada", summary: "Más dinámico.", area: AREA, category: CATEGORY, prompt: "asimetría controlada, punto focal claro, balance visual" },
  { id: "hyper-comp-encadre-005", title: "Leading lines", summary: "Guía la mirada.", area: AREA, category: CATEGORY, prompt: "líneas guía naturales (leading lines) hacia el sujeto" },
  { id: "hyper-comp-encadre-006", title: "Triángulo visual", summary: "Estructura pro.", area: AREA, category: CATEGORY, prompt: "composición en triángulo visual, lectura clara" },
  { id: "hyper-comp-encadre-007", title: "Capas 3 planos", summary: "Profundidad real.", area: AREA, category: CATEGORY, prompt: "capas de foreground/midground/background, profundidad natural" },
  { id: "hyper-comp-encadre-008", title: "Marco natural", summary: "Frame within frame.", area: AREA, category: CATEGORY, prompt: "marco natural (puerta/ventana/ramas) en primer plano" },
  { id: "hyper-comp-encadre-009", title: "Espacio negativo", summary: "Respira.", area: AREA, category: CATEGORY, prompt: "uso de espacio negativo, sujeto destacado, minimal" },
  { id: "hyper-comp-encadre-010", title: "Composición diagonal", summary: "Acción.", area: AREA, category: CATEGORY, prompt: "composición diagonal sutil, dinamismo sin exagerar" },

  { id: "hyper-comp-encadre-011", title: "Eye-level", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "ángulo eye-level (altura de ojos), perspectiva humana" },
  { id: "hyper-comp-encadre-012", title: "Contrapicado leve", summary: "Presencia.", area: AREA, category: CATEGORY, prompt: "leve contrapicado, proporciones realistas, sin deformación" },
  { id: "hyper-comp-encadre-013", title: "Picado leve", summary: "Control.", area: AREA, category: CATEGORY, prompt: "leve picado, geometría estable, realista" },
  { id: "hyper-comp-encadre-014", title: "Plano detalle", summary: "Textura manda.", area: AREA, category: CATEGORY, prompt: "plano detalle, foco en textura, encuadre apretado" },
  { id: "hyper-comp-encadre-015", title: "Close-up", summary: "Intimidad.", area: AREA, category: CATEGORY, prompt: "close-up, rostro o objeto ocupa la mayor parte del encuadre" },
  { id: "hyper-comp-encadre-016", title: "Plano medio", summary: "Versátil.", area: AREA, category: CATEGORY, prompt: "plano medio, lenguaje corporal visible, composición estable" },
  { id: "hyper-comp-encadre-017", title: "Plano americano", summary: "Cine.", area: AREA, category: CATEGORY, prompt: "plano americano, estética cinematográfica, lectura clara" },
  { id: "hyper-comp-encadre-018", title: "Plano general", summary: "Contexto.", area: AREA, category: CATEGORY, prompt: "plano general, sujeto pequeño, entorno cuenta historia" },
  { id: "hyper-comp-encadre-019", title: "3/4 clásico", summary: "Profundidad.", area: AREA, category: CATEGORY, prompt: "ángulo 3/4, profundidad natural, perspectiva estable" },
  { id: "hyper-comp-encadre-020", title: "Perfil", summary: "Limpio.", area: AREA, category: CATEGORY, prompt: "perfil marcado, líneas limpias, fondo simple" },

  { id: "hyper-comp-encadre-021", title: "Horizon recto", summary: "Evita torcido.", area: AREA, category: CATEGORY, prompt: "horizonte perfectamente recto, arquitectura estable" },
  { id: "hyper-comp-encadre-022", title: "Arquitectura 1 punto", summary: "Perspectiva limpia.", area: AREA, category: CATEGORY, prompt: "perspectiva de 1 punto, líneas convergentes controladas" },
  { id: "hyper-comp-encadre-023", title: "Arquitectura 2 puntos", summary: "Real urbano.", area: AREA, category: CATEGORY, prompt: "perspectiva de 2 puntos, verticales correctas" },
  { id: "hyper-comp-encadre-024", title: "Verticales rectas", summary: "Sin caída.", area: AREA, category: CATEGORY, prompt: "verticales rectas, sin distorsión de lente evidente" },
  { id: "hyper-comp-encadre-025", title: "Líneas limpias", summary: "Orden.", area: AREA, category: CATEGORY, prompt: "líneas limpias, geometría coherente, sin caos visual" },
  { id: "hyper-comp-encadre-026", title: "Foco en sujeto", summary: "Prioridad.", area: AREA, category: CATEGORY, prompt: "punto focal único, nada compite con el sujeto" },
  { id: "hyper-comp-encadre-027", title: "Dos puntos focales", summary: "Relación.", area: AREA, category: CATEGORY, prompt: "dos puntos focales claros, jerarquía visual marcada" },
  { id: "hyper-comp-encadre-028", title: "Ritmo visual", summary: "Patrones reales.", area: AREA, category: CATEGORY, prompt: "ritmo visual con repetición sutil, sin patrón artificial" },
  { id: "hyper-comp-encadre-029", title: "Profundidad por escala", summary: "Tamaños reales.", area: AREA, category: CATEGORY, prompt: "profundidad por escala (elementos cercanos grandes, lejanos pequeños)" },
  { id: "hyper-comp-encadre-030", title: "Layering con primer plano", summary: "Inmersión.", area: AREA, category: CATEGORY, prompt: "elemento en primer plano ligeramente desenfocado, inmersión real" },

  { id: "hyper-comp-encadre-031", title: "Encuadre apretado", summary: "Impacto.", area: AREA, category: CATEGORY, prompt: "encuadre apretado, sin aire extra, impacto visual" },
  { id: "hyper-comp-encadre-032", title: "Encuadre con aire", summary: "Elegante.", area: AREA, category: CATEGORY, prompt: "encuadre con aire alrededor, sensación premium" },
  { id: "hyper-comp-encadre-033", title: "Headroom correcto", summary: "Proporción.", area: AREA, category: CATEGORY, prompt: "headroom correcto (espacio superior natural), sin cortes raros" },
  { id: "hyper-comp-encadre-034", title: "Sin cortes incómodos", summary: "Cuerpo bien.", area: AREA, category: CATEGORY, prompt: "evitar cortar articulaciones (tobillos, muñecas), recorte limpio" },
  { id: "hyper-comp-encadre-035", title: "Plano a ras de suelo", summary: "Textura.", area: AREA, category: CATEGORY, prompt: "cámara a ras de suelo, textura del suelo visible, realista" },
  { id: "hyper-comp-encadre-036", title: "Plano desde mesa", summary: "Producto.", area: AREA, category: CATEGORY, prompt: "cámara a altura de mesa, producto protagonista, sin deformación" },
  { id: "hyper-comp-encadre-037", title: "Plano desde hombro", summary: "Story.", area: AREA, category: CATEGORY, prompt: "ángulo over-the-shoulder, narrativa realista" },
  { id: "hyper-comp-encadre-038", title: "Plano POV", summary: "Inmersivo.", area: AREA, category: CATEGORY, prompt: "punto de vista POV, manos/objeto en primer plano, realista" },
  { id: "hyper-comp-encadre-039", title: "Plano espejo", summary: "Reflejo creíble.", area: AREA, category: CATEGORY, prompt: "uso de espejo con reflejo coherente, sin duplicaciones raras" },
  { id: "hyper-comp-encadre-040", title: "Plano con reflejo", summary: "Agua/vidrio.", area: AREA, category: CATEGORY, prompt: "reflejos coherentes (vidrio/agua), perspectiva física correcta" },

  { id: "hyper-comp-encadre-041", title: "Cinemático ancho", summary: "Look película.", area: AREA, category: CATEGORY, prompt: "encuadre cinematográfico ancho, composición calmada" },
  { id: "hyper-comp-encadre-042", title: "Cinemático close", summary: "Drama suave.", area: AREA, category: CATEGORY, prompt: "close-up cinematográfico, emoción creíble, encuadre controlado" },
  { id: "hyper-comp-encadre-043", title: "Centro de masa", summary: "Peso visual.", area: AREA, category: CATEGORY, prompt: "centro de masa visual equilibrado, sensación estable" },
  { id: "hyper-comp-encadre-044", title: "Tensión en bordes", summary: "Cuidado.", area: AREA, category: CATEGORY, prompt: "evitar tangencias (objetos tocando bordes), separación clara" },
  { id: "hyper-comp-encadre-045", title: "Separación fondo", summary: "Sujeto destacado.", area: AREA, category: CATEGORY, prompt: "separación sujeto-fondo por contraste y profundidad, natural" },
  { id: "hyper-comp-encadre-046", title: "Fondo limpio", summary: "Sin ruido.", area: AREA, category: CATEGORY, prompt: "fondo limpio y coherente, sin elementos distractores" },
  { id: "hyper-comp-encadre-047", title: "Fondo contextual", summary: "Story.", area: AREA, category: CATEGORY, prompt: "fondo contextual realista que refuerza la historia" },
  { id: "hyper-comp-encadre-048", title: "Elementos diagonales suaves", summary: "Dinamismo.", area: AREA, category: CATEGORY, prompt: "elementos diagonales sutiles, movimiento sin exagerar" },
  { id: "hyper-comp-encadre-049", title: "Silueta clara", summary: "Lectura.", area: AREA, category: CATEGORY, prompt: "silueta del sujeto clara y separada del fondo" },
  { id: "hyper-comp-encadre-050", title: "Contraste de escala", summary: "Impacto real.", area: AREA, category: CATEGORY, prompt: "contraste de escala (objeto grande vs pequeño), realista" },

  { id: "hyper-comp-encadre-051", title: "Composición en S", summary: "Flujo orgánico.", area: AREA, category: CATEGORY, prompt: "composición en curva S, flujo visual orgánico" },
  { id: "hyper-comp-encadre-052", title: "Composición en C", summary: "Abraza sujeto.", area: AREA, category: CATEGORY, prompt: "forma C en elementos, encierra al sujeto suavemente" },
  { id: "hyper-comp-encadre-053", title: "Golden ratio (sutil)", summary: "Pro.", area: AREA, category: CATEGORY, prompt: "uso sutil de proporción áurea, jerarquía clara" },
  { id: "hyper-comp-encadre-054", title: "Centro visual bajo", summary: "Peso abajo.", area: AREA, category: CATEGORY, prompt: "peso visual ligeramente abajo, estabilidad" },
  { id: "hyper-comp-encadre-055", title: "Centro visual alto", summary: "Ligereza.", area: AREA, category: CATEGORY, prompt: "peso visual ligeramente arriba, sensación ligera" },
  { id: "hyper-comp-encadre-056", title: "Dominante y acento", summary: "2 colores.", area: AREA, category: CATEGORY, prompt: "dominante + acento (color/forma), jerarquía simple" },
  { id: "hyper-comp-encadre-057", title: "Series de objetos", summary: "Repetición real.", area: AREA, category: CATEGORY, prompt: "repetición de objetos realista, variación mínima natural" },
  { id: "hyper-comp-encadre-058", title: "Textura protagonista", summary: "Macro feel.", area: AREA, category: CATEGORY, prompt: "textura protagonista, encuadre para microdetalle" },
  { id: "hyper-comp-encadre-059", title: "Story en primer plano", summary: "Props.", area: AREA, category: CATEGORY, prompt: "props en primer plano que cuentan historia, realista" },
  { id: "hyper-comp-encadre-060", title: "Story en fondo", summary: "Contexto.", area: AREA, category: CATEGORY, prompt: "detalle en fondo que aporta contexto, no distrae" },

  { id: "hyper-comp-encadre-061", title: "Triángulo de luz", summary: "Percepción pro.", area: AREA, category: CATEGORY, prompt: "composición que enfatiza triángulo de luz/sombra, natural" },
  { id: "hyper-comp-encadre-062", title: "Luz como guía", summary: "Recorrido.", area: AREA, category: CATEGORY, prompt: "zonas de luz guían la mirada hacia el sujeto" },
  { id: "hyper-comp-encadre-063", title: "Sombras como marco", summary: "Enmarca.", area: AREA, category: CATEGORY, prompt: "sombras sutiles enmarcan el sujeto sin taparlo" },
  { id: "hyper-comp-encadre-064", title: "Foco por contraste", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "punto focal por contraste suave, sin HDR" },
  { id: "hyper-comp-encadre-065", title: "Foco por color", summary: "Acento.", area: AREA, category: CATEGORY, prompt: "punto focal por acento de color realista" },
  { id: "hyper-comp-encadre-066", title: "Foco por nitidez", summary: "Jerarquía.", area: AREA, category: CATEGORY, prompt: "jerarquía por nitidez: sujeto más nítido, fondo suave" },
  { id: "hyper-comp-encadre-067", title: "Bokeh como separación", summary: "DOF.", area: AREA, category: CATEGORY, prompt: "bokeh gradual y realista para separar planos" },
  { id: "hyper-comp-encadre-068", title: "Caída de enfoque", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "caída de enfoque progresiva, no artificial" },
  { id: "hyper-comp-encadre-069", title: "Centro fuera del centro", summary: "Dinámico.", area: AREA, category: CATEGORY, prompt: "sujeto fuera del centro, balanceado por contrapeso visual" },
  { id: "hyper-comp-encadre-070", title: "Minimalismo pro", summary: "Pocos elementos.", area: AREA, category: CATEGORY, prompt: "minimalismo: pocos elementos, composición limpia, realista" },

  { id: "hyper-comp-encadre-071", title: "Top-down (cenital)", summary: "Plano cenital real.", area: AREA, category: CATEGORY, prompt: "plano cenital (top-down) perfectamente alineado" },
  { id: "hyper-comp-encadre-072", title: "45° de mesa", summary: "Food / producto.", area: AREA, category: CATEGORY, prompt: "ángulo 45° sobre mesa, look editorial, realista" },
  { id: "hyper-comp-encadre-073", title: "Plano lateral", summary: "Perfil objeto.", area: AREA, category: CATEGORY, prompt: "plano lateral, perfil limpio, líneas rectas" },
  { id: "hyper-comp-encadre-074", title: "Macro parcial", summary: "Sección.", area: AREA, category: CATEGORY, prompt: "macro parcial, encuadre de una sección con textura" },
  { id: "hyper-comp-encadre-075", title: "Regla del horizonte", summary: "1/3 arriba.", area: AREA, category: CATEGORY, prompt: "horizonte en tercio superior o inferior, paisaje realista" },
  { id: "hyper-comp-encadre-076", title: "Fondo desenfocado", summary: "Retrato.", area: AREA, category: CATEGORY, prompt: "fondo desenfocado con bokeh realista, sin recortes raros" },
  { id: "hyper-comp-encadre-077", title: "Foreground fuerte", summary: "Capas.", area: AREA, category: CATEGORY, prompt: "primer plano fuerte, medio plano narrativo, fondo suave" },
  { id: "hyper-comp-encadre-078", title: "Separación por luz", summary: "Contorno.", area: AREA, category: CATEGORY, prompt: "separación por rim light suave (si aplica), contorno natural" },
  { id: "hyper-comp-encadre-079", title: "Encuadre con arco", summary: "Arquitectura.", area: AREA, category: CATEGORY, prompt: "arcos/estructuras enmarcan sujeto, perspectiva correcta" },
  { id: "hyper-comp-encadre-080", title: "Patrón roto", summary: "Un detalle distinto.", area: AREA, category: CATEGORY, prompt: "patrón repetido con un elemento distinto como foco" },

  { id: "hyper-comp-encadre-081", title: "Claridad de historia", summary: "1 idea.", area: AREA, category: CATEGORY, prompt: "una sola idea visual dominante, historia clara" },
  { id: "hyper-comp-encadre-082", title: "Jerarquía 3 niveles", summary: "Orden.", area: AREA, category: CATEGORY, prompt: "jerarquía visual: primario/secundario/terciario, clara" },
  { id: "hyper-comp-encadre-083", title: "Sin clutter", summary: "Evita desorden.", area: AREA, category: CATEGORY, prompt: "sin clutter, elementos mínimos y coherentes" },
  { id: "hyper-comp-encadre-084", title: "Centro de interés limpio", summary: "Nada distrae.", area: AREA, category: CATEGORY, prompt: "centro de interés limpio, sin objetos compitiendo" },
  { id: "hyper-comp-encadre-085", title: "Escala humana", summary: "Real.", area: AREA, category: CATEGORY, prompt: "escala humana correcta en objetos/entorno" },
  { id: "hyper-comp-encadre-086", title: "Proporciones anatómicas", summary: "Cuerpo real.", area: AREA, category: CATEGORY, prompt: "proporciones anatómicas correctas, sin deformaciones" },
  { id: "hyper-comp-encadre-087", title: "Posing natural", summary: "Sin rigidez.", area: AREA, category: CATEGORY, prompt: "pose natural (sin rigidez), postura creíble" },
  { id: "hyper-comp-encadre-088", title: "Gestos realistas", summary: "Manos plausibles.", area: AREA, category: CATEGORY, prompt: "gestos realistas en manos/cara, sin dedos extra" },
  { id: "hyper-comp-encadre-089", title: "Interacción con objeto", summary: "Story real.", area: AREA, category: CATEGORY, prompt: "interacción sujeto-objeto creíble, contacto natural" },
  { id: "hyper-comp-encadre-090", title: "Acción congelada", summary: "Momento.", area: AREA, category: CATEGORY, prompt: "captura de un momento (acción) con composición clara" },

  { id: "hyper-comp-encadre-091", title: "Enfoque en ojos", summary: "Retrato top.", area: AREA, category: CATEGORY, prompt: "enfoque en ojos, composición centrada en mirada" },
  { id: "hyper-comp-encadre-092", title: "Mirada hacia espacio", summary: "Dirección.", area: AREA, category: CATEGORY, prompt: "sujeto mirando hacia espacio negativo, dirección clara" },
  { id: "hyper-comp-encadre-093", title: "Mirada a cámara", summary: "Conexión.", area: AREA, category: CATEGORY, prompt: "mirada a cámara, conexión directa, encuadre limpio" },
  { id: "hyper-comp-encadre-094", title: "Producto 3/4", summary: "E-commerce pro.", area: AREA, category: CATEGORY, prompt: "producto en ángulo 3/4, sombra realista, fondo limpio" },
  { id: "hyper-comp-encadre-095", title: "Producto centrado", summary: "Packshot.", area: AREA, category: CATEGORY, prompt: "producto centrado, simetría ligera, composición e-commerce" },
  { id: "hyper-comp-encadre-096", title: "Food 45°", summary: "Estándar food.", area: AREA, category: CATEGORY, prompt: "composición food en 45°, props mínimos, look editorial" },
  { id: "hyper-comp-encadre-097", title: "Food cenital", summary: "Top view.", area: AREA, category: CATEGORY, prompt: "food cenital, alineación perfecta, orden limpio" },
  { id: "hyper-comp-encadre-098", title: "Urbano con profundidad", summary: "Calle real.", area: AREA, category: CATEGORY, prompt: "calle con profundidad marcada, sujeto en tercio, líneas guía" },
  { id: "hyper-comp-encadre-099", title: "Interior con líneas", summary: "Arquitectura.", area: AREA, category: CATEGORY, prompt: "interior con líneas rectas, composición estable, verticales correctas" },
  { id: "hyper-comp-encadre-100", title: "Estudio minimal", summary: "Premium.", area: AREA, category: CATEGORY, prompt: "estudio minimal, fondo limpio, composición premium realista" },
];
