// src/lib/prompts/hyperrealism-text/luz.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Luz";
const CATEGORY = "Natural";

export const hyperrealismTextPromptsLuz = [
  {
    id: "hyper-luz-natural-001",
    title: "Luz natural suave",
    summary: "Iluminación difusa realista.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz natural difusa, sombras suaves, realismo fotográfico",
  },
  {
    id: "hyper-luz-natural-002",
    title: "Ventana lateral",
    summary: "Look clásico de ventana.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz de ventana lateral, sombras suaves direccionales, caída natural",
  },
  {
    id: "hyper-luz-natural-003",
    title: "Golden hour",
    summary: "Cálida y cinematográfica.",
    area: AREA,
    category: CATEGORY,
    prompt: "golden hour natural, tonos cálidos, sombras largas suaves",
  },
  {
    id: "hyper-luz-natural-004",
    title: "Blue hour",
    summary: "Fría y elegante.",
    area: AREA,
    category: CATEGORY,
    prompt: "blue hour natural, tonos fríos suaves, contraste controlado",
  },
  {
    id: "hyper-luz-natural-005",
    title: "Día nublado",
    summary: "Difusión perfecta.",
    area: AREA,
    category: CATEGORY,
    prompt: "cielo nublado, luz ultra difusa, cero sombras duras",
  },
  {
    id: "hyper-luz-natural-006",
    title: "Sol suave de mañana",
    summary: "Limpio y real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz de mañana, cálida suave, contraste natural",
  },
  {
    id: "hyper-luz-natural-007",
    title: "Sol de tarde",
    summary: "Luz cálida realista.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz de tarde, calidez moderada, sombras naturales",
  },
  {
    id: "hyper-luz-natural-008",
    title: "Contraluz suave",
    summary: "Rim light natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "contraluz natural suave, rim light sutil, sin bloom exagerado",
  },
  {
    id: "hyper-luz-natural-009",
    title: "Rim light natural",
    summary: "Separación de fondo.",
    area: AREA,
    category: CATEGORY,
    prompt: "rim light natural sutil, separación sujeto-fondo realista",
  },
  {
    id: "hyper-luz-natural-010",
    title: "Sombras con detalle",
    summary: "Evita negros cerrados.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombras con detalle, negros no empastados, rango natural",
  },

  {
    id: "hyper-luz-natural-011",
    title: "Highlights controlados",
    summary: "Sin quemar.",
    area: AREA,
    category: CATEGORY,
    prompt: "altas luces controladas, roll-off natural, sin clipping duro",
  },
  {
    id: "hyper-luz-natural-012",
    title: "Rebote natural",
    summary: "Fill realista.",
    area: AREA,
    category: CATEGORY,
    prompt: "rebote de luz natural, fill suave, sombras limpias",
  },
  {
    id: "hyper-luz-natural-013",
    title: "Sombra de contacto",
    summary: "Asienta el sujeto.",
    area: AREA,
    category: CATEGORY,
    prompt: "contact shadow realista, el sujeto no flota",
  },
  {
    id: "hyper-luz-natural-014",
    title: "Luz frontal suave",
    summary: "Más flat, pero real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz frontal natural suave, contraste moderado, piel realista",
  },
  {
    id: "hyper-luz-natural-015",
    title: "Luz diagonal",
    summary: "Dimensión real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz diagonal natural, modelado suave, volumen realista",
  },
  {
    id: "hyper-luz-natural-016",
    title: "Sombras definidas suaves",
    summary: "Borde suave.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombras definidas pero suaves, edge soft, realismo",
  },
  {
    id: "hyper-luz-natural-017",
    title: "Bajo sol sin dureza",
    summary: "Sol filtrado.",
    area: AREA,
    category: CATEGORY,
    prompt: "sol filtrado por nubes/árboles, luz moteada natural, sin drama excesivo",
  },
  {
    id: "hyper-luz-natural-018",
    title: "Luz moteada",
    summary: "Patrón de hojas real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz moteada por hojas, sombras orgánicas, patrón natural",
  },
  {
    id: "hyper-luz-natural-019",
    title: "Ambiente interior con ventana",
    summary: "Realismo indoor.",
    area: AREA,
    category: CATEGORY,
    prompt: "interior con luz de ventana, ambiente suave, sombras coherentes",
  },
  {
    id: "hyper-luz-natural-020",
    title: "Luz de atardecer interior",
    summary: "Cálida en interior.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz cálida de atardecer entrando por ventana, sombras largas suaves",
  },

  {
    id: "hyper-luz-natural-021",
    title: "Difusión natural alta",
    summary: "Soft light.",
    area: AREA,
    category: CATEGORY,
    prompt: "difusión natural alta, luz muy suave, textura visible",
  },
  {
    id: "hyper-luz-natural-022",
    title: "Contraste bajo real",
    summary: "Look limpio.",
    area: AREA,
    category: CATEGORY,
    prompt: "contraste bajo realista, tránsito suave de sombras",
  },
  {
    id: "hyper-luz-natural-023",
    title: "Contraste medio real",
    summary: "Equilibrado.",
    area: AREA,
    category: CATEGORY,
    prompt: "contraste medio realista, profundidad natural",
  },
  {
    id: "hyper-luz-natural-024",
    title: "Contraste alto controlado",
    summary: "Drama real.",
    area: AREA,
    category: CATEGORY,
    prompt: "contraste alto controlado, sin perder detalle, realismo",
  },
  {
    id: "hyper-luz-natural-025",
    title: "Luz dura pero real",
    summary: "Sol directo creíble.",
    area: AREA,
    category: CATEGORY,
    prompt: "sol directo, sombras marcadas reales, sin look CGI",
  },
  {
    id: "hyper-luz-natural-026",
    title: "Sombra dura con detalle",
    summary: "No empastes.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombras duras con detalle, negros no cerrados",
  },
  {
    id: "hyper-luz-natural-027",
    title: "Brillo en piel real",
    summary: "Especular natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "brillo de piel natural, zonas T realistas, sin aceite exagerado",
  },
  {
    id: "hyper-luz-natural-028",
    title: "Reflejo ambiental",
    summary: "Light wrap natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "light wrap natural por rebote, sin halo artificial",
  },
  {
    id: "hyper-luz-natural-029",
    title: "Luz ambiental suave",
    summary: "Sin puntos raros.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz ambiental suave, sin hotspots, sin highlights falsos",
  },
  {
    id: "hyper-luz-natural-030",
    title: "Clima brumoso leve",
    summary: "Haze real.",
    area: AREA,
    category: CATEGORY,
    prompt: "bruma leve natural (haze), profundidad atmosférica sutil",
  },

  {
    id: "hyper-luz-natural-031",
    title: "Niebla suave",
    summary: "Atmósfera real.",
    area: AREA,
    category: CATEGORY,
    prompt: "niebla suave realista, contraste reducido natural",
  },
  {
    id: "hyper-luz-natural-032",
    title: "Haces de luz sutiles",
    summary: "Solo si aplica.",
    area: AREA,
    category: CATEGORY,
    prompt: "haces de luz muy sutiles en polvo, sin exageración",
  },
  {
    id: "hyper-luz-natural-033",
    title: "Sombras coherentes",
    summary: "Dirección clara.",
    area: AREA,
    category: CATEGORY,
    prompt: "dirección de luz clara, sombras coherentes y consistentes",
  },
  {
    id: "hyper-luz-natural-034",
    title: "Sin bloom",
    summary: "Evita glow.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin bloom exagerado, sin glow artificial",
  },
  {
    id: "hyper-luz-natural-035",
    title: "Roll-off suave",
    summary: "Transición real.",
    area: AREA,
    category: CATEGORY,
    prompt: "roll-off suave en highlights, transición realista",
  },
  {
    id: "hyper-luz-natural-036",
    title: "Sombras suaves extendidas",
    summary: "Difusión grande.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombras largas y suaves, difusión grande natural",
  },
  {
    id: "hyper-luz-natural-037",
    title: "Luz rebotada en pared",
    summary: "Indoor natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz rebotada en pared clara, fill natural suave",
  },
  {
    id: "hyper-luz-natural-038",
    title: "Luz rebotada en suelo",
    summary: "Warm bounce.",
    area: AREA,
    category: CATEGORY,
    prompt: "rebote cálido desde el suelo, sombras más suaves, real",
  },
  {
    id: "hyper-luz-natural-039",
    title: "Reflector natural",
    summary: "Como cartulina blanca.",
    area: AREA,
    category: CATEGORY,
    prompt: "relleno tipo reflector blanco natural, sombras limpias",
  },
  {
    id: "hyper-luz-natural-040",
    title: "Negativo de luz",
    summary: "Más contraste real.",
    area: AREA,
    category: CATEGORY,
    prompt: "negative fill sutil (menos luz rebotada), contraste natural",
  },

  {
    id: "hyper-luz-natural-041",
    title: "Luz lateral dramática",
    summary: "Sin parecer render.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz lateral marcada, sombras con detalle, realismo fotográfico",
  },
  {
    id: "hyper-luz-natural-042",
    title: "Luz cenital suave",
    summary: "Top light real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz cenital suave, sombras naturales bajo ojos/nariz, sin exagerar",
  },
  {
    id: "hyper-luz-natural-043",
    title: "Luz cenital dura",
    summary: "Mediodía real.",
    area: AREA,
    category: CATEGORY,
    prompt: "sol cenital de mediodía, sombras duras reales, textura visible",
  },
  {
    id: "hyper-luz-natural-044",
    title: "Luz de calle nocturna",
    summary: "Sodio/LED real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz de farola nocturna realista, color natural, sin neón exagerado",
  },
  {
    id: "hyper-luz-natural-045",
    title: "Neón realista sutil",
    summary: "Sin cyberpunk.",
    area: AREA,
    category: CATEGORY,
    prompt: "neón sutil realista, reflejos mínimos, sin look cyberpunk caricaturesco",
  },
  {
    id: "hyper-luz-natural-046",
    title: "Pantalla como luz",
    summary: "Glow real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz de pantalla suave en rostro, caída natural, sin halo artificial",
  },
  {
    id: "hyper-luz-natural-047",
    title: "Sombra proyectada real",
    summary: "Patrón real.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombras proyectadas coherentes (ventana/persiana), patrón realista",
  },
  {
    id: "hyper-luz-natural-048",
    title: "Persiana suave",
    summary: "Rayas realistas.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz de persiana suave, rayas naturales, sin exageración",
  },
  {
    id: "hyper-luz-natural-049",
    title: "Cortina difusora",
    summary: "Soft window.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz filtrada por cortina, suavidad natural, sombras limpias",
  },
  {
    id: "hyper-luz-natural-050",
    title: "Rebote cálido",
    summary: "Piel más viva.",
    area: AREA,
    category: CATEGORY,
    prompt: "rebote cálido sutil en sombras, tono piel realista",
  },

  {
    id: "hyper-luz-natural-051",
    title: "Rebote frío",
    summary: "Sombras frías reales.",
    area: AREA,
    category: CATEGORY,
    prompt: "rebote frío sutil en sombras, ambiente realista",
  },
  {
    id: "hyper-luz-natural-052",
    title: "Luz ambiental de sombra",
    summary: "Outdoor shade.",
    area: AREA,
    category: CATEGORY,
    prompt: "en sombra exterior, luz suave, color natural, contraste bajo",
  },
  {
    id: "hyper-luz-natural-053",
    title: "Luz reflejada en pared roja",
    summary: "Color spill real.",
    area: AREA,
    category: CATEGORY,
    prompt: "color spill sutil desde pared de color, natural y moderado",
  },
  {
    id: "hyper-luz-natural-054",
    title: "Transición suave",
    summary: "Entre luz y sombra.",
    area: AREA,
    category: CATEGORY,
    prompt: "transición suave luz-sombra, gradiente realista",
  },
  {
    id: "hyper-luz-natural-055",
    title: "Nada de “studio glow”",
    summary: "Evita artificial.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin glow de estudio falso, iluminación natural creíble",
  },
  {
    id: "hyper-luz-natural-056",
    title: "Sin flare falso",
    summary: "Lens flare realista.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin lens flare falso, si hay flare que sea mínimo y real",
  },
  {
    id: "hyper-luz-natural-057",
    title: "Flare mínimo",
    summary: "Solo si aplica.",
    area: AREA,
    category: CATEGORY,
    prompt: "lens flare muy sutil y realista (opcional), sin exagerar",
  },
  {
    id: "hyper-luz-natural-058",
    title: "Backlight cálido",
    summary: "Rim cálido.",
    area: AREA,
    category: CATEGORY,
    prompt: "backlight cálido, rim light suave, contraste natural",
  },
  {
    id: "hyper-luz-natural-059",
    title: "Backlight frío",
    summary: "Rim frío.",
    area: AREA,
    category: CATEGORY,
    prompt: "backlight frío sutil, rim light leve, realismo",
  },
  {
    id: "hyper-luz-natural-060",
    title: "Silhouette controlada",
    summary: "Silueta real.",
    area: AREA,
    category: CATEGORY,
    prompt: "silueta realista, contorno limpio, sin glow artificial",
  },

  {
    id: "hyper-luz-natural-061",
    title: "Luz natural de estudio (tipo ventana)",
    summary: "Look pro sin artificial.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz tipo ventana grande, suave, natural, sombras elegantes",
  },
  {
    id: "hyper-luz-natural-062",
    title: "Luz rebotada suave",
    summary: "Fill natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "fill natural rebotado, sombras suaves, volumen real",
  },
  {
    id: "hyper-luz-natural-063",
    title: "Cielo limpio",
    summary: "Color real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz de cielo claro, sombras suaves, color natural",
  },
  {
    id: "hyper-luz-natural-064",
    title: "Cielo nublado brillante",
    summary: "Soft + bright.",
    area: AREA,
    category: CATEGORY,
    prompt: "nublado brillante, difusión fuerte, highlights suaves",
  },
  {
    id: "hyper-luz-natural-065",
    title: "Atmósfera húmeda",
    summary: "Aire con humedad.",
    area: AREA,
    category: CATEGORY,
    prompt: "aire húmedo sutil, brillo realista, contraste moderado",
  },
  {
    id: "hyper-luz-natural-066",
    title: "Luz de lluvia",
    summary: "Reflejos reales.",
    area: AREA,
    category: CATEGORY,
    prompt: "ambiente lluvioso, reflejos en superficies mojadas, luz realista",
  },
  {
    id: "hyper-luz-natural-067",
    title: "Noche con iluminación real",
    summary: "No sci-fi.",
    area: AREA,
    category: CATEGORY,
    prompt: "iluminación nocturna realista, ruido mínimo, sin colores imposibles",
  },
  {
    id: "hyper-luz-natural-068",
    title: "Atardecer con sombras largas",
    summary: "Look cálido.",
    area: AREA,
    category: CATEGORY,
    prompt: "atardecer natural, sombras largas, tonos cálidos moderados",
  },
  {
    id: "hyper-luz-natural-069",
    title: "Mediodía real",
    summary: "Duro pero real.",
    area: AREA,
    category: CATEGORY,
    prompt: "sol de mediodía real, sombras duras, detalle preservado",
  },
  {
    id: "hyper-luz-natural-070",
    title: "Sombra de árbol",
    summary: "Moteado real.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombra de árbol, luz moteada sutil, patrón orgánico real",
  },

  {
    id: "hyper-luz-natural-071",
    title: "Interior cálido real",
    summary: "Luz ambiente hogar.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz interior cálida realista, sombras suaves, sin tungsteno exagerado",
  },
  {
    id: "hyper-luz-natural-072",
    title: "Interior frío real",
    summary: "LED suave.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz interior fría realista (LED), balance correcto, sin dominante rara",
  },
  {
    id: "hyper-luz-natural-073",
    title: "Mixto luz día + interior",
    summary: "Balance creíble.",
    area: AREA,
    category: CATEGORY,
    prompt: "mezcla de luz día e interior, balance realista, sin dominantes fuertes",
  },
  {
    id: "hyper-luz-natural-074",
    title: "Shadow gradient",
    summary: "Caída suave.",
    area: AREA,
    category: CATEGORY,
    prompt: "gradiente suave en sombras, caída natural, nada plano",
  },
  {
    id: "hyper-luz-natural-075",
    title: "Reflejo en ojos real",
    summary: "Catchlight natural.",
    area: AREA,
    category: CATEGORY,
    prompt: "catchlight natural en ojos, tamaño coherente, sin brillo falso",
  },
  {
    id: "hyper-luz-natural-076",
    title: "Sin hotspots",
    summary: "Nada quemado.",
    area: AREA,
    category: CATEGORY,
    prompt: "sin hotspots, sin quemados, exposición equilibrada",
  },
  {
    id: "hyper-luz-natural-077",
    title: "Exposición real",
    summary: "No sobreexponer.",
    area: AREA,
    category: CATEGORY,
    prompt: "exposición realista, detalle en luces y sombras, sin clipping",
  },
  {
    id: "hyper-luz-natural-078",
    title: "Light wrap mínimo",
    summary: "Sin halo.",
    area: AREA,
    category: CATEGORY,
    prompt: "light wrap mínimo real, sin halo alrededor del sujeto",
  },
  {
    id: "hyper-luz-natural-079",
    title: "Sombra suave bajo barbilla",
    summary: "Modelado real.",
    area: AREA,
    category: CATEGORY,
    prompt: "sombra suave bajo barbilla, volumen natural, sin exagerar",
  },
  {
    id: "hyper-luz-natural-080",
    title: "Modelado de rostro real",
    summary: "3D real (foto).",
    area: AREA,
    category: CATEGORY,
    prompt: "modelado natural de rostro, sombras sutiles, profundidad realista",
  },

  {
    id: "hyper-luz-natural-081",
    title: "Luz lateral en producto",
    summary: "Textura visible.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz lateral suave en producto, textura visible, reflejos controlados",
  },
  {
    id: "hyper-luz-natural-082",
    title: "Backlight en producto",
    summary: "Separación limpia.",
    area: AREA,
    category: CATEGORY,
    prompt: "backlight suave en producto, contorno limpio, sin halo",
  },
  {
    id: "hyper-luz-natural-083",
    title: "Luz suave en comida",
    summary: "Apetitoso.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz suave natural en comida, brillo realista, colores creíbles",
  },
  {
    id: "hyper-luz-natural-084",
    title: "Luz dura en comida (crujiente)",
    summary: "Textura marcada.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz más dura para marcar textura (comida), sin quemar highlights",
  },
  {
    id: "hyper-luz-natural-085",
    title: "Reflejos mojados",
    summary: "Superficie húmeda.",
    area: AREA,
    category: CATEGORY,
    prompt: "reflejos en superficies mojadas, realismo físico, sin espejo falso",
  },
  {
    id: "hyper-luz-natural-086",
    title: "Luz suave en tela",
    summary: "Trama visible.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz suave para revelar trama de tela, sin aplastar textura",
  },
  {
    id: "hyper-luz-natural-087",
    title: "Luz dura en metal",
    summary: "Specular real.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz más dura en metal, specular realista, control de highlights",
  },
  {
    id: "hyper-luz-natural-088",
    title: "Luz suave en piel",
    summary: "Natural beauty.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz suave en piel, textura visible, sin suavizado artificial",
  },
  {
    id: "hyper-luz-natural-089",
    title: "Atmósfera de interior real",
    summary: "Ambiente coherente.",
    area: AREA,
    category: CATEGORY,
    prompt: "ambiente interior realista, sombras coherentes, luz sin rarezas",
  },
  {
    id: "hyper-luz-natural-090",
    title: "Sin dominante rara",
    summary: "WB correcto.",
    area: AREA,
    category: CATEGORY,
    prompt: "balance de blancos correcto, sin dominante verde/magenta",
  },

  {
    id: "hyper-luz-natural-091",
    title: "Sombras suaves grandes",
    summary: "Fuente grande.",
    area: AREA,
    category: CATEGORY,
    prompt: "fuente de luz grande (natural), sombras muy suaves, look pro",
  },
  {
    id: "hyper-luz-natural-092",
    title: "Sombras pequeñas (duras)",
    summary: "Fuente pequeña.",
    area: AREA,
    category: CATEGORY,
    prompt: "fuente de luz pequeña (sol directo), sombras duras reales",
  },
  {
    id: "hyper-luz-natural-093",
    title: "Dirección única",
    summary: "Coherencia.",
    area: AREA,
    category: CATEGORY,
    prompt: "una dirección de luz clara, sin luces contradictorias",
  },
  {
    id: "hyper-luz-natural-094",
    title: "Luz real sin fantasía",
    summary: "Nada irreal.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz realista, sin colores imposibles, sin ambiente sci-fi",
  },
  {
    id: "hyper-luz-natural-095",
    title: "Transparencias reales",
    summary: "Vidrio/agua.",
    area: AREA,
    category: CATEGORY,
    prompt: "transparencias reales con refracción sutil, reflejo coherente",
  },
  {
    id: "hyper-luz-natural-096",
    title: "Reflejo de cielo",
    summary: "Outdoor real.",
    area: AREA,
    category: CATEGORY,
    prompt: "reflejo de cielo natural en superficies, sin brillos inventados",
  },
  {
    id: "hyper-luz-natural-097",
    title: "Specular controlado",
    summary: "Highlights limpios.",
    area: AREA,
    category: CATEGORY,
    prompt: "specular controlado, sin hotspots, sin brillo plástico",
  },
  {
    id: "hyper-luz-natural-098",
    title: "Exposición tipo cámara",
    summary: "Real.",
    area: AREA,
    category: CATEGORY,
    prompt: "exposición tipo cámara real, sin HDR agresivo, detalle completo",
  },
  {
    id: "hyper-luz-natural-099",
    title: "Negativos de luz",
    summary: "Evita glow/fake.",
    area: AREA,
    category: CATEGORY,
    prompt: "negativo: bloom, glow, lens flare falso, HDR exagerado, luces imposibles",
  },
  {
    id: "hyper-luz-natural-100",
    title: "Luz natural premium",
    summary: "Combo final.",
    area: AREA,
    category: CATEGORY,
    prompt: "luz natural premium, sombras coherentes, highlights suaves, realismo fotográfico",
  },
];
