// src/lib/prompts/hyperrealism-text/luz.js
// Unikalny obszar i kategoria dla CAŁEGO tego pliku:
const AREA = "Światło";
const CATEGORY = "Naturalne";

export const hyperrealismTextPromptsLuz = [
  {
    id: "hyper-luz-natural-001",
    title: "Miękkie światło naturalne",
    summary: "Realistyczne, rozproszone oświetlenie.",
    area: AREA,
    category: CATEGORY,
    prompt: "rozproszone naturalne światło, miękkie cienie, fotograficzny realizm",
  },
  {
    id: "hyper-luz-natural-002",
    title: "Boczne światło z okna",
    summary: "Klasyczny look z okna.",
    area: AREA,
    category: CATEGORY,
    prompt: "boczne światło z okna, miękkie kierunkowe cienie, naturalny spadek światła",
  },
  {
    id: "hyper-luz-natural-003",
    title: "Złota godzina",
    summary: "Ciepła i filmowa.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalna złota godzina, ciepłe tony, długie miękkie cienie",
  },
  {
    id: "hyper-luz-natural-004",
    title: "Niebieska godzina",
    summary: "Chłodna i elegancka.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalna niebieska godzina, delikatne chłodne tony, kontrolowany kontrast",
  },
  {
    id: "hyper-luz-natural-005",
    title: "Pochmurny dzień",
    summary: "Idealne rozproszenie.",
    area: AREA,
    category: CATEGORY,
    prompt: "zachmurzone niebo, ultra rozproszone światło, zero twardych cieni",
  },
  {
    id: "hyper-luz-natural-006",
    title: "Miękkie poranne słońce",
    summary: "Czyste i realne.",
    area: AREA,
    category: CATEGORY,
    prompt: "poranne światło, lekko ciepłe, naturalny kontrast",
  },
  {
    id: "hyper-luz-natural-007",
    title: "Popołudniowe słońce",
    summary: "Realistycznie ciepłe.",
    area: AREA,
    category: CATEGORY,
    prompt: "popołudniowe światło, umiarkowana ciepłota, naturalne cienie",
  },
  {
    id: "hyper-luz-natural-008",
    title: "Miękki kontr-światło",
    summary: "Naturalny rim light.",
    area: AREA,
    category: CATEGORY,
    prompt: "delikatne naturalne światło pod słońce, subtelny rim light, bez przesadnego bloom",
  },
  {
    id: "hyper-luz-natural-009",
    title: "Naturalny rim light",
    summary: "Separacja od tła.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny naturalny rim light, realistyczna separacja obiektu od tła",
  },
  {
    id: "hyper-luz-natural-010",
    title: "Cienie z detalem",
    summary: "Unikaj zbyt czarnych czerni.",
    area: AREA,
    category: CATEGORY,
    prompt: "cienie z detalem, czernie nie zlane, naturalny zakres tonalny",
  },

  {
    id: "hyper-luz-natural-011",
    title: "Kontrolowane światła",
    summary: "Bez przepaleń.",
    area: AREA,
    category: CATEGORY,
    prompt: "kontrolowane światła, naturalny roll-off, bez twardego clipingu",
  },
  {
    id: "hyper-luz-natural-012",
    title: "Naturalny refleks (bounce)",
    summary: "Realistyczne doświetlenie.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalne odbicie światła, delikatny fill, czyste cienie",
  },
  {
    id: "hyper-luz-natural-013",
    title: "Cień kontaktowy",
    summary: "Osadza obiekt.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczny cień kontaktowy, obiekt nie unosi się",
  },
  {
    id: "hyper-luz-natural-014",
    title: "Miękkie światło z przodu",
    summary: "Bardziej płasko, ale realnie.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie naturalne światło frontalne, umiarkowany kontrast, realistyczna skóra",
  },
  {
    id: "hyper-luz-natural-015",
    title: "Światło diagonalne",
    summary: "Realny wymiar.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalne światło diagonalne, miękkie modelowanie, realistyczna objętość",
  },
  {
    id: "hyper-luz-natural-016",
    title: "Miękko zarysowane cienie",
    summary: "Miękka krawędź.",
    area: AREA,
    category: CATEGORY,
    prompt: "cienie wyraźne, ale miękkie, soft edge, realizm",
  },
  {
    id: "hyper-luz-natural-017",
    title: "Słońce bez twardości",
    summary: "Słońce filtrowane.",
    area: AREA,
    category: CATEGORY,
    prompt: "słońce filtrowane przez chmury/drzewa, naturalne światło plamiste, bez przesadnego dramatu",
  },
  {
    id: "hyper-luz-natural-018",
    title: "Światło plamiste",
    summary: "Realny wzór liści.",
    area: AREA,
    category: CATEGORY,
    prompt: "plamiste światło przez liście, organiczne cienie, naturalny wzór",
  },
  {
    id: "hyper-luz-natural-019",
    title: "Wnętrze z oknem",
    summary: "Realizm indoor.",
    area: AREA,
    category: CATEGORY,
    prompt: "wnętrze ze światłem z okna, miękka atmosfera, spójne cienie",
  },
  {
    id: "hyper-luz-natural-020",
    title: "Wnętrze o zachodzie",
    summary: "Ciepło w środku.",
    area: AREA,
    category: CATEGORY,
    prompt: "ciepłe światło zachodu wpadające przez okno, długie miękkie cienie",
  },

  {
    id: "hyper-luz-natural-021",
    title: "Wysoka dyfuzja naturalna",
    summary: "Soft light.",
    area: AREA,
    category: CATEGORY,
    prompt: "wysoka naturalna dyfuzja, bardzo miękkie światło, widoczna tekstura",
  },
  {
    id: "hyper-luz-natural-022",
    title: "Niski realizm kontrastu",
    summary: "Czysty look.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistycznie niski kontrast, miękkie przejścia w cieniach",
  },
  {
    id: "hyper-luz-natural-023",
    title: "Średni realizm kontrastu",
    summary: "Zbalansowane.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczny średni kontrast, naturalna głębia",
  },
  {
    id: "hyper-luz-natural-024",
    title: "Wysoki kontrast kontrolowany",
    summary: "Realny dramat.",
    area: AREA,
    category: CATEGORY,
    prompt: "kontrolowany wysoki kontrast, bez utraty detalu, realizm",
  },
  {
    id: "hyper-luz-natural-025",
    title: "Twarde, ale realne światło",
    summary: "Wiarygodne słońce.",
    area: AREA,
    category: CATEGORY,
    prompt: "bezpośrednie słońce, wyraźne realne cienie, bez looku CGI",
  },
  {
    id: "hyper-luz-natural-026",
    title: "Twardy cień z detalem",
    summary: "Bez zlewania.",
    area: AREA,
    category: CATEGORY,
    prompt: "twarde cienie z detalem, czernie nie zamknięte",
  },
  {
    id: "hyper-luz-natural-027",
    title: "Realny połysk skóry",
    summary: "Naturalny specular.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalny połysk skóry, realistyczna strefa T, bez przesadnej ‘oleistości’",
  },
  {
    id: "hyper-luz-natural-028",
    title: "Odbicie środowiskowe",
    summary: "Naturalny light wrap.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalny light wrap z odbicia, bez sztucznego halo",
  },
  {
    id: "hyper-luz-natural-029",
    title: "Miękkie światło otoczenia",
    summary: "Bez dziwnych punktów.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie światło otoczenia, bez hotspotów, bez fałszywych highlightów",
  },
  {
    id: "hyper-luz-natural-030",
    title: "Lekka mgiełka",
    summary: "Realny haze.",
    area: AREA,
    category: CATEGORY,
    prompt: "lekka naturalna mgiełka (haze), subtelna głębia atmosferyczna",
  },

  {
    id: "hyper-luz-natural-031",
    title: "Delikatna mgła",
    summary: "Realna atmosfera.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna delikatna mgła, naturalnie obniżony kontrast",
  },
  {
    id: "hyper-luz-natural-032",
    title: "Subtelne smugi światła",
    summary: "Tylko jeśli pasuje.",
    area: AREA,
    category: CATEGORY,
    prompt: "bardzo subtelne smugi światła w pyle, bez przesady",
  },
  {
    id: "hyper-luz-natural-033",
    title: "Spójne cienie",
    summary: "Jasny kierunek.",
    area: AREA,
    category: CATEGORY,
    prompt: "jasny kierunek światła, spójne i konsekwentne cienie",
  },
  {
    id: "hyper-luz-natural-034",
    title: "Bez bloom",
    summary: "Unikaj glow.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez przesadnego bloom, bez sztucznego glow",
  },
  {
    id: "hyper-luz-natural-035",
    title: "Miękki roll-off",
    summary: "Realne przejścia.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękki roll-off w światłach, realistyczne przejścia",
  },
  {
    id: "hyper-luz-natural-036",
    title: "Długie miękkie cienie",
    summary: "Duża dyfuzja.",
    area: AREA,
    category: CATEGORY,
    prompt: "długie i miękkie cienie, naturalnie duża dyfuzja",
  },
  {
    id: "hyper-luz-natural-037",
    title: "Światło odbite od ściany",
    summary: "Naturalne wnętrze.",
    area: AREA,
    category: CATEGORY,
    prompt: "światło odbite od jasnej ściany, miękki naturalny fill",
  },
  {
    id: "hyper-luz-natural-038",
    title: "Światło odbite od podłogi",
    summary: "Ciepły bounce.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelne ciepłe odbicie od podłogi, miększe cienie, realnie",
  },
  {
    id: "hyper-luz-natural-039",
    title: "Naturalny reflektor",
    summary: "Jak biała tektura.",
    area: AREA,
    category: CATEGORY,
    prompt: "doświetlenie jak białym reflektorem, czyste cienie",
  },
  {
    id: "hyper-luz-natural-040",
    title: "Negatywne doświetlenie",
    summary: "Więcej realnego kontrastu.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny negative fill (mniej odbitego światła), naturalny kontrast",
  },

  {
    id: "hyper-luz-natural-041",
    title: "Dramatyczne światło boczne",
    summary: "Bez render looku.",
    area: AREA,
    category: CATEGORY,
    prompt: "mocne światło boczne, cienie z detalem, fotograficzny realizm",
  },
  {
    id: "hyper-luz-natural-042",
    title: "Miękkie światło z góry",
    summary: "Realny top light.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie światło z góry, naturalne cienie pod oczami/nosem, bez przesady",
  },
  {
    id: "hyper-luz-natural-043",
    title: "Twarde światło z góry",
    summary: "Realne południe.",
    area: AREA,
    category: CATEGORY,
    prompt: "południowe słońce z góry, twarde realne cienie, widoczna tekstura",
  },
  {
    id: "hyper-luz-natural-044",
    title: "Nocne światło uliczne",
    summary: "Realny sód/LED.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne światło latarni nocą, naturalny kolor, bez przesadnego neonu",
  },
  {
    id: "hyper-luz-natural-045",
    title: "Subtelny realistyczny neon",
    summary: "Bez cyberpunku.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny realistyczny neon, minimalne refleksy, bez karykaturalnego cyberpunk looku",
  },
  {
    id: "hyper-luz-natural-046",
    title: "Ekran jako światło",
    summary: "Realny glow.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie światło ekranu na twarzy, naturalny spadek, bez sztucznego halo",
  },
  {
    id: "hyper-luz-natural-047",
    title: "Realne cienie rzutowane",
    summary: "Prawdziwy wzór.",
    area: AREA,
    category: CATEGORY,
    prompt: "spójne cienie rzutowane (okno/żaluzje), realistyczny wzór",
  },
  {
    id: "hyper-luz-natural-048",
    title: "Miękkie żaluzje",
    summary: "Realistyczne pasy.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie światło przez żaluzje, naturalne pasy, bez przesady",
  },
  {
    id: "hyper-luz-natural-049",
    title: "Zasłona jako dyfuzor",
    summary: "Soft window.",
    area: AREA,
    category: CATEGORY,
    prompt: "światło filtrowane przez zasłonę, naturalna miękkość, czyste cienie",
  },
  {
    id: "hyper-luz-natural-050",
    title: "Ciepły refleks",
    summary: "Żywsza skóra.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny ciepły refleks w cieniach, realistyczny odcień skóry",
  },

  {
    id: "hyper-luz-natural-051",
    title: "Chłodny refleks",
    summary: "Realne chłodne cienie.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny chłodny refleks w cieniach, realistyczne otoczenie",
  },
  {
    id: "hyper-luz-natural-052",
    title: "Światło w cieniu",
    summary: "Outdoor shade.",
    area: AREA,
    category: CATEGORY,
    prompt: "na zewnątrz w cieniu, miękkie światło, naturalny kolor, niski kontrast",
  },
  {
    id: "hyper-luz-natural-053",
    title: "Odbicie od czerwonej ściany",
    summary: "Realny color spill.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelny color spill od kolorowej ściany, naturalnie i umiarkowanie",
  },
  {
    id: "hyper-luz-natural-054",
    title: "Miękkie przejście",
    summary: "Między światłem a cieniem.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie przejście światło–cień, realistyczny gradient",
  },
  {
    id: "hyper-luz-natural-055",
    title: "Bez ‘studio glow’",
    summary: "Unikaj sztuczności.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez fałszywego studyjnego glow, wiarygodne naturalne oświetlenie",
  },
  {
    id: "hyper-luz-natural-056",
    title: "Bez fałszywego flary",
    summary: "Realistyczny lens flare.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez fałszywego lens flare, jeśli jest flare to minimalny i realny",
  },
  {
    id: "hyper-luz-natural-057",
    title: "Minimalny flare",
    summary: "Tylko jeśli pasuje.",
    area: AREA,
    category: CATEGORY,
    prompt: "bardzo subtelny i realistyczny lens flare (opcjonalnie), bez przesady",
  },
  {
    id: "hyper-luz-natural-058",
    title: "Ciepłe światło pod słońce",
    summary: "Ciepły rim.",
    area: AREA,
    category: CATEGORY,
    prompt: "ciepłe światło z tyłu, miękki rim light, naturalny kontrast",
  },
  {
    id: "hyper-luz-natural-059",
    title: "Chłodne światło pod słońce",
    summary: "Chłodny rim.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelne chłodne światło z tyłu, lekki rim light, realizm",
  },
  {
    id: "hyper-luz-natural-060",
    title: "Kontrolowana sylwetka",
    summary: "Realna sylwetka.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna sylwetka, czysty kontur, bez sztucznego glow",
  },

  {
    id: "hyper-luz-natural-061",
    title: "Naturalne ‘studyjne’ (jak z okna)",
    summary: "Pro look bez sztuczności.",
    area: AREA,
    category: CATEGORY,
    prompt: "duże światło jak z okna, miękkie, naturalne, eleganckie cienie",
  },
  {
    id: "hyper-luz-natural-062",
    title: "Miękkie światło odbite",
    summary: "Naturalny fill.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalny fill z odbicia, miękkie cienie, realna objętość",
  },
  {
    id: "hyper-luz-natural-063",
    title: "Czyste niebo",
    summary: "Realny kolor.",
    area: AREA,
    category: CATEGORY,
    prompt: "światło z czystego nieba, miękkie cienie, naturalny kolor",
  },
  {
    id: "hyper-luz-natural-064",
    title: "Jasne zachmurzenie",
    summary: "Soft + bright.",
    area: AREA,
    category: CATEGORY,
    prompt: "jasne zachmurzenie, mocna dyfuzja, miękkie highlighty",
  },
  {
    id: "hyper-luz-natural-065",
    title: "Wilgotna atmosfera",
    summary: "Powietrze z wilgocią.",
    area: AREA,
    category: CATEGORY,
    prompt: "subtelnie wilgotne powietrze, realistyczny połysk, umiarkowany kontrast",
  },
  {
    id: "hyper-luz-natural-066",
    title: "Światło deszczu",
    summary: "Realne refleksy.",
    area: AREA,
    category: CATEGORY,
    prompt: "deszczowy klimat, refleksy na mokrych powierzchniach, realistyczne światło",
  },
  {
    id: "hyper-luz-natural-067",
    title: "Noc z realistycznym światłem",
    summary: "Bez sci-fi.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne nocne oświetlenie, minimalny szum, bez niemożliwych kolorów",
  },
  {
    id: "hyper-luz-natural-068",
    title: "Zachód z długimi cieniami",
    summary: "Ciepły look.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalny zachód, długie cienie, umiarkowane ciepłe tony",
  },
  {
    id: "hyper-luz-natural-069",
    title: "Realne południe",
    summary: "Twardo, ale realnie.",
    area: AREA,
    category: CATEGORY,
    prompt: "realne południowe słońce, twarde cienie, detal zachowany",
  },
  {
    id: "hyper-luz-natural-070",
    title: "Cień drzewa",
    summary: "Realny moteado.",
    area: AREA,
    category: CATEGORY,
    prompt: "cień drzewa, subtelne światło plamiste, organiczny realny wzór",
  },

  {
    id: "hyper-luz-natural-071",
    title: "Realne ciepłe wnętrze",
    summary: "Domowe światło otoczenia.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne ciepłe światło we wnętrzu, miękkie cienie, bez przesadnego tungsten",
  },
  {
    id: "hyper-luz-natural-072",
    title: "Realne chłodne wnętrze",
    summary: "Miękki LED.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne chłodne światło we wnętrzu (LED), poprawny balans, bez dziwnej dominanty",
  },
  {
    id: "hyper-luz-natural-073",
    title: "Miks światła dziennego i wnętrza",
    summary: "Wiarygodny balans.",
    area: AREA,
    category: CATEGORY,
    prompt: "mieszanka światła dziennego i wnętrza, realistyczny balans, bez mocnych dominant",
  },
  {
    id: "hyper-luz-natural-074",
    title: "Gradient cienia",
    summary: "Miękki spadek.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękki gradient w cieniach, naturalny spadek, nic płaskiego",
  },
  {
    id: "hyper-luz-natural-075",
    title: "Realny refleks w oczach",
    summary: "Naturalny catchlight.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalny catchlight w oczach, spójny rozmiar, bez fałszywego błysku",
  },
  {
    id: "hyper-luz-natural-076",
    title: "Bez hotspotów",
    summary: "Nic przepalonego.",
    area: AREA,
    category: CATEGORY,
    prompt: "bez hotspotów, bez przepaleń, ekspozycja zbalansowana",
  },
  {
    id: "hyper-luz-natural-077",
    title: "Realna ekspozycja",
    summary: "Nie prześwietlać.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna ekspozycja, detal w światłach i cieniach, bez clipingu",
  },
  {
    id: "hyper-luz-natural-078",
    title: "Minimalny light wrap",
    summary: "Bez halo.",
    area: AREA,
    category: CATEGORY,
    prompt: "minimalny realny light wrap, bez halo wokół obiektu",
  },
  {
    id: "hyper-luz-natural-079",
    title: "Miękki cień pod brodą",
    summary: "Realne modelowanie.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękki cień pod brodą, naturalna objętość, bez przesady",
  },
  {
    id: "hyper-luz-natural-080",
    title: "Realne modelowanie twarzy",
    summary: "Realne 3D (foto).",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalne modelowanie twarzy, subtelne cienie, realistyczna głębia",
  },

  {
    id: "hyper-luz-natural-081",
    title: "Boczne światło na produkcie",
    summary: "Widoczna tekstura.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie boczne światło na produkcie, widoczna tekstura, kontrolowane refleksy",
  },
  {
    id: "hyper-luz-natural-082",
    title: "Backlight na produkcie",
    summary: "Czysta separacja.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękki backlight na produkcie, czysty kontur, bez halo",
  },
  {
    id: "hyper-luz-natural-083",
    title: "Miękkie światło na jedzeniu",
    summary: "Apetytne.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie naturalne światło na jedzeniu, realistyczny połysk, wiarygodne kolory",
  },
  {
    id: "hyper-luz-natural-084",
    title: "Twardsze światło na jedzeniu (chrupkość)",
    summary: "Mocniejsza tekstura.",
    area: AREA,
    category: CATEGORY,
    prompt: "twardsze światło podkreślające teksturę (jedzenie), bez przepalonych highlightów",
  },
  {
    id: "hyper-luz-natural-085",
    title: "Mokre refleksy",
    summary: "Wilgotna powierzchnia.",
    area: AREA,
    category: CATEGORY,
    prompt: "refleksy na mokrych powierzchniach, realizm fizyczny, bez fałszywego lustra",
  },
  {
    id: "hyper-luz-natural-086",
    title: "Miękkie światło na tkaninie",
    summary: "Widoczny splot.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie światło ujawniające splot tkaniny, bez spłaszczania tekstury",
  },
  {
    id: "hyper-luz-natural-087",
    title: "Twardsze światło na metalu",
    summary: "Realny specular.",
    area: AREA,
    category: CATEGORY,
    prompt: "twardsze światło na metalu, realistyczny specular, kontrola highlightów",
  },
  {
    id: "hyper-luz-natural-088",
    title: "Miękkie światło na skórze",
    summary: "Natural beauty.",
    area: AREA,
    category: CATEGORY,
    prompt: "miękkie światło na skórze, widoczna tekstura, bez sztucznego wygładzania",
  },
  {
    id: "hyper-luz-natural-089",
    title: "Realna atmosfera wnętrza",
    summary: "Spójny klimat.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczna atmosfera wnętrza, spójne cienie, światło bez dziwactw",
  },
  {
    id: "hyper-luz-natural-090",
    title: "Bez dziwnej dominanty",
    summary: "Poprawny WB.",
    area: AREA,
    category: CATEGORY,
    prompt: "poprawny balans bieli, bez zielonej/magenty dominanty",
  },

  {
    id: "hyper-luz-natural-091",
    title: "Bardzo miękkie duże cienie",
    summary: "Duże źródło.",
    area: AREA,
    category: CATEGORY,
    prompt: "duże (naturalne) źródło światła, bardzo miękkie cienie, pro look",
  },
  {
    id: "hyper-luz-natural-092",
    title: "Małe (twarde) cienie",
    summary: "Małe źródło.",
    area: AREA,
    category: CATEGORY,
    prompt: "małe źródło światła (bezpośrednie słońce), twarde realne cienie",
  },
  {
    id: "hyper-luz-natural-093",
    title: "Jeden kierunek",
    summary: "Spójność.",
    area: AREA,
    category: CATEGORY,
    prompt: "jeden wyraźny kierunek światła, bez sprzecznych świateł",
  },
  {
    id: "hyper-luz-natural-094",
    title: "Realne światło bez fantazji",
    summary: "Nic nierealnego.",
    area: AREA,
    category: CATEGORY,
    prompt: "realistyczne światło, bez niemożliwych kolorów, bez klimatu sci-fi",
  },
  {
    id: "hyper-luz-natural-095",
    title: "Realne przezroczystości",
    summary: "Szkło/woda.",
    area: AREA,
    category: CATEGORY,
    prompt: "realne przezroczystości z subtelną refrakcją, spójne odbicia",
  },
  {
    id: "hyper-luz-natural-096",
    title: "Odbicie nieba",
    summary: "Realny outdoor.",
    area: AREA,
    category: CATEGORY,
    prompt: "naturalne odbicie nieba na powierzchniach, bez wymyślonych blików",
  },
  {
    id: "hyper-luz-natural-097",
    title: "Kontrolowany specular",
    summary: "Czyste highlighty.",
    area: AREA,
    category: CATEGORY,
    prompt: "kontrolowany specular, bez hotspotów, bez plastikowego połysku",
  },
  {
    id: "hyper-luz-natural-098",
    title: "Ekspozycja jak z aparatu",
    summary: "Real.",
    area: AREA,
    category: CATEGORY,
    prompt: "ekspozycja jak z realnego aparatu, bez agresywnego HDR, pełny detal",
  },
  {
    id: "hyper-luz-natural-099",
    title: "Negatywy światła",
    summary: "Unikaj glow/fake.",
    area: AREA,
    category: CATEGORY,
    prompt: "negatywy: bloom, glow, fałszywy lens flare, przesadzony HDR, niemożliwe światła",
  },
  {
    id: "hyper-luz-natural-100",
    title: "Światło naturalne premium",
    summary: "Finalny zestaw.",
    area: AREA,
    category: CATEGORY,
    prompt: "premium naturalne światło, spójne cienie, miękkie highlighty, fotograficzny realizm",
  },
];
