// src/lib/prompts/hyperrealism-text/materiales.js
// Unikalny obszar i kategoria dla CAŁEGO tego pliku:
const AREA = "Materiały";
const CATEGORY = "Tekstury";

export const hyperrealismTextPromptsMateriales = [
  { id: "hyper-mat-texturas-001", title: "Realistyczna skóra ludzka", summary: "Pory i mikro-niedoskonałości.", area: AREA, category: CATEGORY, prompt: "realistyczna tekstura skóry, widoczne pory, naturalne mikro-niedoskonałości" },
  { id: "hyper-mat-texturas-002", title: "Drobny meszek", summary: "Realistyczny peach fuzz.", area: AREA, category: CATEGORY, prompt: "subtelny drobny meszek (peach fuzz), naturalnie, bez przesady" },
  { id: "hyper-mat-texturas-003", title: "Mikro-zmarszczki", summary: "Wiarygodny wiek.", area: AREA, category: CATEGORY, prompt: "realistyczne mikro-zmarszczki, naturalna tekstura, bez filtra beauty" },
  { id: "hyper-mat-texturas-004", title: "Subtelne piegi i plamki", summary: "Realna różnorodność.", area: AREA, category: CATEGORY, prompt: "subtelne piegi/plamki, naturalna zmienność skóry" },
  { id: "hyper-mat-texturas-005", title: "Realistyczne usta", summary: "Tekstura i wilgoć.", area: AREA, category: CATEGORY, prompt: "usta z realistyczną teksturą, subtelna wilgoć, bez plastiku" },
  { id: "hyper-mat-texturas-006", title: "Realistyczne oczy", summary: "Wilgoć i odbicia.", area: AREA, category: CATEGORY, prompt: "realistyczne oczy, spójne odbicia, subtelna wilgoć, bez ‘lalczanego’ spojrzenia" },
  { id: "hyper-mat-texturas-007", title: "Naturalne rzęsy", summary: "Bez sztucznego wachlarza.", area: AREA, category: CATEGORY, prompt: "naturalne rzęsy, realistyczna gęstość, bez powtarzalnego wzoru" },
  { id: "hyper-mat-texturas-008", title: "Drobne włosy", summary: "Pojedyncze pasma.", area: AREA, category: CATEGORY, prompt: "włosy z wyraźnymi pasmami, naturalna zmienność, bez ‘bloków’" },
  { id: "hyper-mat-texturas-009", title: "Realistyczna broda", summary: "Mieszki i cienie.", area: AREA, category: CATEGORY, prompt: "realistyczna broda, widoczne mieszki, naturalny cień, bez malowanej tekstury" },
  { id: "hyper-mat-texturas-010", title: "Subtelny pot", summary: "Realny połysk.", area: AREA, category: CATEGORY, prompt: "subtelny pot, realistyczny połysk, bez przesadnego efektu mokrości" },

  { id: "hyper-mat-texturas-011", title: "Bawełna", summary: "Widoczny splot.", area: AREA, category: CATEGORY, prompt: "tkanina bawełniana, widoczny splot, naturalne zagniecenia" },
  { id: "hyper-mat-texturas-012", title: "Len", summary: "Nieregularne włókno.", area: AREA, category: CATEGORY, prompt: "realistyczny len, nieregularne włókna, organiczne zagniecenia" },
  { id: "hyper-mat-texturas-013", title: "Dżins", summary: "Splot i przetarcia.", area: AREA, category: CATEGORY, prompt: "dżins z widocznym splotem, subtelne zużycie, realistyczne szwy" },
  { id: "hyper-mat-texturas-014", title: "Skóra matowa", summary: "Pory i ziarno.", area: AREA, category: CATEGORY, prompt: "matowa skóra, widoczne ziarno, subtelne mikro-rysy" },
  { id: "hyper-mat-texturas-015", title: "Skóra lekko błyszcząca", summary: "Kontrolowane odbicia.", area: AREA, category: CATEGORY, prompt: "lekko błyszcząca skóra, kontrolowane odbicia, bez plastiku" },
  { id: "hyper-mat-texturas-016", title: "Zamsz", summary: "Drobny włosek.", area: AREA, category: CATEGORY, prompt: "zamsz z drobnym meszkiem, naturalne cieniowanie, bez dziwnych plam" },
  { id: "hyper-mat-texturas-017", title: "Jedwab", summary: "Miękki połysk.", area: AREA, category: CATEGORY, prompt: "realistyczny jedwab, miękki anizotropowy połysk, wiarygodne fałdy" },
  { id: "hyper-mat-texturas-018", title: "Satyna", summary: "Wyraźniejszy refleks.", area: AREA, category: CATEGORY, prompt: "satyna, wyraźny ale realistyczny refleks, bez overexposure" },
  { id: "hyper-mat-texturas-019", title: "Wełna", summary: "Grubsze włókna.", area: AREA, category: CATEGORY, prompt: "wełna z widocznym włóknem, realna objętość, bez powtarzalnych wzorów" },
  { id: "hyper-mat-texturas-020", title: "Dzianina", summary: "Widoczne oczka.", area: AREA, category: CATEGORY, prompt: "dzianina, widoczne oczka, realistyczna tekstura" },

  { id: "hyper-mat-texturas-021", title: "Metal szczotkowany", summary: "Drobne rysy.", area: AREA, category: CATEGORY, prompt: "metal szczotkowany, drobne linie, realistyczne odbicia" },
  { id: "hyper-mat-texturas-022", title: "Stal nierdzewna", summary: "Realne refleksy.", area: AREA, category: CATEGORY, prompt: "stal nierdzewna, miękkie odbicia, dyskretne mikro-rysy" },
  { id: "hyper-mat-texturas-023", title: "Aluminium", summary: "Lekki mat.", area: AREA, category: CATEGORY, prompt: "matowe aluminium, delikatny refleks, ostre krawędzie" },
  { id: "hyper-mat-texturas-024", title: "Chrom", summary: "Lustrzane odbicie.", area: AREA, category: CATEGORY, prompt: "chrom, spójne lustrzane odbicie, bez niemożliwych zniekształceń" },
  { id: "hyper-mat-texturas-025", title: "Mosiądz", summary: "Ciepły ton.", area: AREA, category: CATEGORY, prompt: "realistyczny mosiądz, ciepły ton, subtelna patyna" },
  { id: "hyper-mat-texturas-026", title: "Miedź", summary: "Lekka patyna.", area: AREA, category: CATEGORY, prompt: "realistyczna miedź, lekka patyna, naturalne plamki" },
  { id: "hyper-mat-texturas-027", title: "Żelazo kute", summary: "Realna chropowatość.", area: AREA, category: CATEGORY, prompt: "żelazo kute, realistyczna chropowatość, naturalne zużycie" },
  { id: "hyper-mat-texturas-028", title: "Metal malowany", summary: "Subtelne odpryski.", area: AREA, category: CATEGORY, prompt: "metal malowany, subtelnie odpryśnięta farba, przetarta krawędź" },
  { id: "hyper-mat-texturas-029", title: "Metal z rdzą", summary: "Wiarygodna korozja.", area: AREA, category: CATEGORY, prompt: "realistyczna rdza, naturalna ziarnistość, bez powtórzeń" },
  { id: "hyper-mat-texturas-030", title: "Realne śruby i nity", summary: "Detale mechaniczne.", area: AREA, category: CATEGORY, prompt: "realistyczne śruby/nity, mikro-rysy, subtelny brud" },

  { id: "hyper-mat-texturas-031", title: "Czyste szkło", summary: "Realna transparentność.", area: AREA, category: CATEGORY, prompt: "czyste szkło, spójna refrakcja, miękkie odbicia" },
  { id: "hyper-mat-texturas-032", title: "Szkło matowe (mleczne)", summary: "Miękka dyfuzja.", area: AREA, category: CATEGORY, prompt: "szkło matowe, realistyczna dyfuzja, bez dziwnego szumu" },
  { id: "hyper-mat-texturas-033", title: "Szkło z kurzem", summary: "Mikro-niedoskonałość.", area: AREA, category: CATEGORY, prompt: "szkło z subtelnym kurzem, lekkie odciski, realistycznie" },
  { id: "hyper-mat-texturas-034", title: "Plastik matowy", summary: "Bez taniego looku.",
    area: AREA, category: CATEGORY, prompt: "realistyczny matowy plastik, mikro-tekstura, bez wyglądu zabawki" },
  { id: "hyper-mat-texturas-035", title: "Plastik błyszczący", summary: "Kontrolowane odbicia.", area: AREA, category: CATEGORY, prompt: "błyszczący plastik, kontrolowane odbicia, bez przepaleń" },
  { id: "hyper-mat-texturas-036", title: "Akryl", summary: "Wyraźne krawędzie.", area: AREA, category: CATEGORY, prompt: "przezroczysty akryl, ostre krawędzie, poprawna refrakcja" },
  { id: "hyper-mat-texturas-037", title: "Żywica", summary: "Półprzezroczysta.", area: AREA, category: CATEGORY, prompt: "półprzezroczysta żywica, minimalne realistyczne bąbelki" },
  { id: "hyper-mat-texturas-038", title: "Ceramika matowa", summary: "Drobne ziarnko.", area: AREA, category: CATEGORY, prompt: "matowa ceramika, drobne ziarnko, subtelne niedoskonałości" },
  { id: "hyper-mat-texturas-039", title: "Ceramika szkliwiona", summary: "Realny połysk.", area: AREA, category: CATEGORY, prompt: "szkliwiona ceramika, realistyczny połysk, mikro-defekty" },
  { id: "hyper-mat-texturas-040", title: "Porcelana", summary: "Bez przesady.", area: AREA, category: CATEGORY, prompt: "realistyczna porcelana, bez plastikowego looku, miękki refleks" },

  { id: "hyper-mat-texturas-041", title: "Drewno dębowe", summary: "Jasne usłojenie.", area: AREA, category: CATEGORY, prompt: "drewno dębowe, widoczne usłojenie, naturalne pory, bez powtórzeń" },
  { id: "hyper-mat-texturas-042", title: "Drewno orzechowe", summary: "Ciemniejsze usłojenie.", area: AREA, category: CATEGORY, prompt: "drewno orzechowe, bogate usłojenie, subtelny połysk, lekkie zużycie" },
  { id: "hyper-mat-texturas-043", title: "Drewno malowane", summary: "Zużycie na krawędziach.", area: AREA, category: CATEGORY, prompt: "malowane drewno, zużycie na krawędziach, widoczne warstwy" },
  { id: "hyper-mat-texturas-044", title: "Lakier", summary: "Miękki refleks.", area: AREA, category: CATEGORY, prompt: "realistyczny lakier, miękkie odbicie, bez fałszywego efektu lustra" },
  { id: "hyper-mat-texturas-045", title: "Stare drewno", summary: "Subtelne pęknięcia.", area: AREA, category: CATEGORY, prompt: "postarzone drewno, drobne pęknięcia, minimalne drzazgi" },
  { id: "hyper-mat-texturas-046", title: "Beton", summary: "Pory i plamy.", area: AREA, category: CATEGORY, prompt: "realistyczny beton, widoczne pory, subtelne plamy, drobne pęknięcia" },
  { id: "hyper-mat-texturas-047", title: "Polerowany beton", summary: "Gładki z rysami.", area: AREA, category: CATEGORY, prompt: "polerowany beton, mikro-rysy, delikatny refleks" },
  { id: "hyper-mat-texturas-048", title: "Cegła", summary: "Realna zaprawa.", area: AREA, category: CATEGORY, prompt: "realistyczna cegła, nierówna zaprawa, naturalne zużycie" },
  { id: "hyper-mat-texturas-049", title: "Tynk/ściana", summary: "Drobne ziarno.", area: AREA, category: CATEGORY, prompt: "tynkowana ściana, drobne ziarno, subtelne niedoskonałości" },
  { id: "hyper-mat-texturas-050", title: "Asfalt", summary: "Ziarnistość.", area: AREA, category: CATEGORY, prompt: "realistyczny asfalt, widoczna ziarnistość, subtelny pył" },

  { id: "hyper-mat-texturas-051", title: "Kamień: marmur", summary: "Realne żyłkowanie.", area: AREA, category: CATEGORY, prompt: "realistyczny marmur, unikalne żyłki, miękki połysk, bez powtarzalnego wzoru" },
  { id: "hyper-mat-texturas-052", title: "Granit", summary: "Mineralne kropki.", area: AREA, category: CATEGORY, prompt: "realistyczny granit, mineralne kropki, naturalny mikro-połysk" },
  { id: "hyper-mat-texturas-053", title: "Łupek", summary: "Warstwy.", area: AREA, category: CATEGORY, prompt: "łupek, widoczne warstwy, realistyczna chropowata tekstura" },
  { id: "hyper-mat-texturas-054", title: "Piasek", summary: "Widoczne ziarna.", area: AREA, category: CATEGORY, prompt: "realistyczny piasek, widoczne ziarna, subtelne ślady" },
  { id: "hyper-mat-texturas-055", title: "Wilgotna ziemia", summary: "Realizm.", area: AREA, category: CATEGORY, prompt: "wilgotna ziemia, naturalne grudki, subtelny połysk" },
  { id: "hyper-mat-texturas-056", title: "Trawa", summary: "Zróżnicowane źdźbła.", area: AREA, category: CATEGORY, prompt: "realistyczna trawa, zróżnicowane źdźbła, bez powtórzeń" },
  { id: "hyper-mat-texturas-057", title: "Liście", summary: "Widoczne żyłki.", area: AREA, category: CATEGORY, prompt: "liście z widocznymi żyłkami, naturalne mikro-niedoskonałości" },
  { id: "hyper-mat-texturas-058", title: "Kora", summary: "Chropowatość.", area: AREA, category: CATEGORY, prompt: "kora drzewa, realistyczna chropowatość, subtelny mech" },
  { id: "hyper-mat-texturas-059", title: "Skała", summary: "Szczeliny.", area: AREA, category: CATEGORY, prompt: "realistyczna skała, drobne szczeliny, naturalny pył" },
  { id: "hyper-mat-texturas-060", title: "Śnieg", summary: "Miękkie kryształki.", area: AREA, category: CATEGORY, prompt: "realistyczny śnieg, miękka tekstura, subtelny połysk, bez plastiku" },

  { id: "hyper-mat-texturas-061", title: "Czysta woda", summary: "Odbicia i refrakcja.", area: AREA, category: CATEGORY, prompt: "czysta woda, spójne odbicia, realistyczna refrakcja" },
  { id: "hyper-mat-texturas-062", title: "Woda z kroplami", summary: "Realne perełki.", area: AREA, category: CATEGORY, prompt: "krople wody, realistyczne napięcie powierzchniowe, naturalne perełki" },
  { id: "hyper-mat-texturas-063", title: "Kondensacja", summary: "Zimne szkło.", area: AREA, category: CATEGORY, prompt: "realistyczna kondensacja, małe krople, subtelne ślady spływania" },
  { id: "hyper-mat-texturas-064", title: "Lód", summary: "Pęcherzyki.", area: AREA, category: CATEGORY, prompt: "realistyczny lód, wewnętrzne pęknięcia, subtelne bąbelki" },
  { id: "hyper-mat-texturas-065", title: "Subtelna para", summary: "Realne ciepło.", area: AREA, category: CATEGORY, prompt: "subtelna realistyczna para, bez sztucznej mgły" },
  { id: "hyper-mat-texturas-066", title: "Delikatny dym", summary: "Realna dyfuzja.", area: AREA, category: CATEGORY, prompt: "realistyczny delikatny dym, naturalna dyfuzja, bez plam" },
  { id: "hyper-mat-texturas-067", title: "Subtelny kurz", summary: "Realizm.", area: AREA, category: CATEGORY, prompt: "subtelny kurz na powierzchniach, naturalne nagromadzenie" },
  { id: "hyper-mat-texturas-068", title: "Realny brud", summary: "Bez przesady.", area: AREA, category: CATEGORY, prompt: "lekki realistyczny brud, naturalne plamy, bez przesady" },
  { id: "hyper-mat-texturas-069", title: "Drobne rysy", summary: "Prawdziwe użycie.", area: AREA, category: CATEGORY, prompt: "drobne mikro-rysy, zużycie od użytkowania, realistycznie" },
  { id: "hyper-mat-texturas-070", title: "Zużyte krawędzie", summary: "Corner wear.", area: AREA, category: CATEGORY, prompt: "zużycie na krawędziach, subtelnie starta farba, realistycznie" },

  { id: "hyper-mat-texturas-071", title: "Papier matowy", summary: "Widoczne włókna.", area: AREA, category: CATEGORY, prompt: "matowy papier, widoczne włókna, naturalne ziarno" },
  { id: "hyper-mat-texturas-072", title: "Papier błyszczący", summary: "Odbicie.", area: AREA, category: CATEGORY, prompt: "błyszczący papier, kontrolowane odbicia, bez przepaleń" },
  { id: "hyper-mat-texturas-073", title: "Tektura", summary: "Falista struktura.", area: AREA, category: CATEGORY, prompt: "realistyczna tektura, falista tekstura, włókniste krawędzie" },
  { id: "hyper-mat-texturas-074", title: "Zeszyt", summary: "Realne kartki.", area: AREA, category: CATEGORY, prompt: "kartki zeszytu, tekstura papieru, miękkie cienie" },
  { id: "hyper-mat-texturas-075", title: "Atrament i kreska", summary: "Niedoskonałość.", area: AREA, category: CATEGORY, prompt: "realistyczny atrament, lekkie wahania, bez idealnych krawędzi" },
  { id: "hyper-mat-texturas-076", title: "Realny druk", summary: "Bez bandingu.", area: AREA, category: CATEGORY, prompt: "realistyczny druk, subtelna siatka, bez bandingu" },
  { id: "hyper-mat-texturas-077", title: "Naklejka (etykieta)", summary: "Realne przyklejenie.", area: AREA, category: CATEGORY, prompt: "samoprzylepna etykieta, minimalnie uniesiona krawędź, realistyczna tekstura" },
  { id: "hyper-mat-texturas-078", title: "Tkanina haftowana", summary: "Nitki.", area: AREA, category: CATEGORY, prompt: "realistyczny haft, widoczne nitki, subtelny relief" },
  { id: "hyper-mat-texturas-079", title: "Szwy", summary: "Ściegi.", area: AREA, category: CATEGORY, prompt: "realistyczne szwy, widoczne ściegi, naturalne naprężenie" },
  { id: "hyper-mat-texturas-080", title: "Guziki", summary: "Detale.", area: AREA, category: CATEGORY, prompt: "realistyczne guziki, subtelny połysk, mikro-rysy" },

  { id: "hyper-mat-texturas-081", title: "Guma/kauczuk", summary: "Mat z porami.", area: AREA, category: CATEGORY, prompt: "realistyczny kauczuk, drobne pory, subtelny pył, bez plastiku" },
  { id: "hyper-mat-texturas-082", title: "Pianka", summary: "Duże pory.", area: AREA, category: CATEGORY, prompt: "realistyczna pianka, widoczne pory, miękkie cienie" },
  { id: "hyper-mat-texturas-083", title: "Neopren", summary: "Jednolita tekstura.", area: AREA, category: CATEGORY, prompt: "realistyczny neopren, jednolita tekstura, czyste krawędzie" },
  { id: "hyper-mat-texturas-084", title: "Farba satynowa", summary: "Półpołysk.", area: AREA, category: CATEGORY, prompt: "farba satynowa, realistyczny średni połysk, mikro-tekstura" },
  { id: "hyper-mat-texturas-085", title: "Realny lakier do paznokci", summary: "Mały połysk.", area: AREA, category: CATEGORY, prompt: "realistyczne paznokcie, lakier z subtelnym połyskiem, naturalna skórka" },
  { id: "hyper-mat-texturas-086", title: "Realistyczny makijaż", summary: "Bez filtra.", area: AREA, category: CATEGORY, prompt: "realistyczny makijaż, widoczna tekstura, bez efektu airbrush" },
  { id: "hyper-mat-texturas-087", title: "Mokra tkanina", summary: "Ciemnieje.", area: AREA, category: CATEGORY, prompt: "realistycznie mokra tkanina, naturalne przyciemnienie, subtelne krople" },
  { id: "hyper-mat-texturas-088", title: "Naturalnie pogniecione ubranie", summary: "Realne fałdy.", area: AREA, category: CATEGORY, prompt: "naturalne zagniecenia ubrań, realistyczne naprężenia, bez wzorów" },
  { id: "hyper-mat-texturas-089", title: "Skóra z lekką blizną", summary: "Realizm.", area: AREA, category: CATEGORY, prompt: "realistyczna lekka blizna, spójna tekstura, bez przesady" },
  { id: "hyper-mat-texturas-090", title: "Skóra z porowatością", summary: "Naturalnie.", area: AREA, category: CATEGORY, prompt: "naturalna porowatość, zmienność tonu, bez porcelanowej skóry" },

  { id: "hyper-mat-texturas-091", title: "Chrupiące jedzenie", summary: "Tekstura.", area: AREA, category: CATEGORY, prompt: "realistyczna chrupiąca tekstura, subtelne okruszki, detal" },
  { id: "hyper-mat-texturas-092", title: "Soczyste jedzenie", summary: "Wilgoć.", area: AREA, category: CATEGORY, prompt: "realistyczna soczystość, naturalny połysk, bez plastiku" },
  { id: "hyper-mat-texturas-093", title: "Czekolada", summary: "Połysk i bloom.", area: AREA, category: CATEGORY, prompt: "realistyczna czekolada, subtelny bloom, miękki refleks" },
  { id: "hyper-mat-texturas-094", title: "Chleb", summary: "Miękisz.", area: AREA, category: CATEGORY, prompt: "realistyczny chleb, widoczny miękisz, naturalne cięcie" },
  { id: "hyper-mat-texturas-095", title: "Owoce", summary: "Skórka.", area: AREA, category: CATEGORY, prompt: "realistyczne owoce, skórka z porami, naturalny połysk" },
  { id: "hyper-mat-texturas-096", title: "Mięso", summary: "Włókna.", area: AREA, category: CATEGORY, prompt: "realistyczne mięso, subtelne włókna, naturalny tłuszcz" },
  { id: "hyper-mat-texturas-097", title: "Ser", summary: "Pory.", area: AREA, category: CATEGORY, prompt: "realistyczny ser, pory i lekki połysk, naturalne cięcie" },
  { id: "hyper-mat-texturas-098", title: "Sos", summary: "Lepkość.", area: AREA, category: CATEGORY, prompt: "realistyczny sos, spójna lepkość, miękki refleks" },
  { id: "hyper-mat-texturas-099", title: "Nowe opakowanie", summary: "Bez zużycia.", area: AREA, category: CATEGORY, prompt: "nowy materiał, czysta powierzchnia, realistyczna mikro-tekstura" },
  { id: "hyper-mat-texturas-100", title: "Używane opakowanie", summary: "Realne użycie.", area: AREA, category: CATEGORY, prompt: "używany materiał, lekkie zużycie, realistyczne mikro-rysy" },
];
