// src/lib/prompts/hyperrealism-text/materiales.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Materiales";
const CATEGORY = "Texturas";

export const hyperrealismTextPromptsMateriales = [
  { id: "hyper-mat-texturas-001", title: "Piel humana real", summary: "Poros y microimperfecciones.", area: AREA, category: CATEGORY, prompt: "textura de piel real, poros visibles, microimperfecciones naturales" },
  { id: "hyper-mat-texturas-002", title: "Vello fino", summary: "Peach fuzz realista.", area: AREA, category: CATEGORY, prompt: "vello fino sutil (peach fuzz), natural, sin exageración" },
  { id: "hyper-mat-texturas-003", title: "Microarrugas", summary: "Edad creíble.", area: AREA, category: CATEGORY, prompt: "microarrugas realistas, textura natural, sin filtro beauty" },
  { id: "hyper-mat-texturas-004", title: "Pecas y manchas sutiles", summary: "Variedad real.", area: AREA, category: CATEGORY, prompt: "pecas/manchas sutiles, variación natural de piel" },
  { id: "hyper-mat-texturas-005", title: "Labios reales", summary: "Textura y humedad.", area: AREA, category: CATEGORY, prompt: "labios con textura real, humedad sutil, sin plástico" },
  { id: "hyper-mat-texturas-006", title: "Ojos realistas", summary: "Humedad y reflejos.", area: AREA, category: CATEGORY, prompt: "ojos realistas, reflejo coherente, humedad sutil, sin mirada de muñeca" },
  { id: "hyper-mat-texturas-007", title: "Pestañas naturales", summary: "Sin abanico falso.", area: AREA, category: CATEGORY, prompt: "pestañas naturales, densidad real, sin patrón repetido" },
  { id: "hyper-mat-texturas-008", title: "Cabello fino", summary: "Hebras individuales.", area: AREA, category: CATEGORY, prompt: "cabello con hebras definidas, variación natural, sin bloques" },
  { id: "hyper-mat-texturas-009", title: "Barba real", summary: "Folículos y sombras.", area: AREA, category: CATEGORY, prompt: "barba realista, folículos visibles, sombra natural, sin textura pintada" },
  { id: "hyper-mat-texturas-010", title: "Sudor sutil", summary: "Brillo real.", area: AREA, category: CATEGORY, prompt: "sudor sutil, brillo realista, sin efecto mojado exagerado" },

  { id: "hyper-mat-texturas-011", title: "Algodón", summary: "Tejido visible.", area: AREA, category: CATEGORY, prompt: "tela de algodón, trama visible, arrugas naturales" },
  { id: "hyper-mat-texturas-012", title: "Lino", summary: "Fibra irregular.", area: AREA, category: CATEGORY, prompt: "lino realista, fibra irregular, arrugas orgánicas" },
  { id: "hyper-mat-texturas-013", title: "Denim", summary: "Trama y desgaste.", area: AREA, category: CATEGORY, prompt: "denim con trama visible, desgaste sutil, costuras reales" },
  { id: "hyper-mat-texturas-014", title: "Cuero mate", summary: "Poros y grano.", area: AREA, category: CATEGORY, prompt: "cuero mate, grano visible, microarañazos sutiles" },
  { id: "hyper-mat-texturas-015", title: "Cuero brillante", summary: "Reflejo controlado.", area: AREA, category: CATEGORY, prompt: "cuero ligeramente brillante, reflejos controlados, sin plástico" },
  { id: "hyper-mat-texturas-016", title: "Gamuza", summary: "Pelusa fina.", area: AREA, category: CATEGORY, prompt: "gamuza con pelusa fina, sombreado natural, sin manchas raras" },
  { id: "hyper-mat-texturas-017", title: "Seda", summary: "Brillo suave.", area: AREA, category: CATEGORY, prompt: "seda realista, brillo suave anisotrópico, pliegues creíbles" },
  { id: "hyper-mat-texturas-018", title: "Satén", summary: "Reflejo marcado.", area: AREA, category: CATEGORY, prompt: "satén, reflejo marcado pero real, sin overexposure" },
  { id: "hyper-mat-texturas-019", title: "Lana", summary: "Fibra gruesa.", area: AREA, category: CATEGORY, prompt: "lana con fibra visible, volumen real, sin patrones repetidos" },
  { id: "hyper-mat-texturas-020", title: "Tejido punto", summary: "Loop visible.", area: AREA, category: CATEGORY, prompt: "tejido de punto, loops visibles, textura realista" },

  { id: "hyper-mat-texturas-021", title: "Metal cepillado", summary: "Rayas finas.", area: AREA, category: CATEGORY, prompt: "metal cepillado, líneas finas, reflejo realista" },
  { id: "hyper-mat-texturas-022", title: "Acero inoxidable", summary: "Reflejos reales.", area: AREA, category: CATEGORY, prompt: "acero inoxidable, reflejos suaves, microarañazos discretos" },
  { id: "hyper-mat-texturas-023", title: "Aluminio", summary: "Mate ligero.", area: AREA, category: CATEGORY, prompt: "aluminio mate, reflejo tenue, bordes nítidos" },
  { id: "hyper-mat-texturas-024", title: "Cromo", summary: "Reflejo espejo.", area: AREA, category: CATEGORY, prompt: "cromo, reflejo tipo espejo coherente, sin distorsión imposible" },
  { id: "hyper-mat-texturas-025", title: "Latón", summary: "Tono cálido.", area: AREA, category: CATEGORY, prompt: "latón realista, tono cálido, pátina sutil" },
  { id: "hyper-mat-texturas-026", title: "Cobre", summary: "Pátina ligera.", area: AREA, category: CATEGORY, prompt: "cobre realista, pátina ligera, manchas naturales" },
  { id: "hyper-mat-texturas-027", title: "Hierro forjado", summary: "Rugosidad real.", area: AREA, category: CATEGORY, prompt: "hierro forjado, rugosidad real, desgaste natural" },
  { id: "hyper-mat-texturas-028", title: "Metal pintado", summary: "Despostillado.", area: AREA, category: CATEGORY, prompt: "metal pintado, pintura despostillada sutil, borde gastado" },
  { id: "hyper-mat-texturas-029", title: "Metal oxidado", summary: "Óxido creíble.", area: AREA, category: CATEGORY, prompt: "óxido realista, granularidad natural, sin repetición" },
  { id: "hyper-mat-texturas-030", title: "Tornillería real", summary: "Detalles mecánicos.", area: AREA, category: CATEGORY, prompt: "tornillos/remaches realistas, microarañazos, suciedad sutil" },

  { id: "hyper-mat-texturas-031", title: "Vidrio limpio", summary: "Transparencia real.", area: AREA, category: CATEGORY, prompt: "vidrio limpio, refracción coherente, reflejos suaves" },
  { id: "hyper-mat-texturas-032", title: "Vidrio esmerilado", summary: "Difusión suave.", area: AREA, category: CATEGORY, prompt: "vidrio esmerilado, difusión real, sin ruido extraño" },
  { id: "hyper-mat-texturas-033", title: "Cristal con polvo", summary: "Microimperfección.", area: AREA, category: CATEGORY, prompt: "cristal con polvo sutil, huellas leves, realista" },
  { id: "hyper-mat-texturas-034", title: "Plástico mate", summary: "Sin look barato.", area: AREA, category: CATEGORY, prompt: "plástico mate realista, microtextura, sin aspecto de juguete" },
  { id: "hyper-mat-texturas-035", title: "Plástico brillante", summary: "Reflejo controlado.", area: AREA, category: CATEGORY, prompt: "plástico brillante, reflejos controlados, sin quemados" },
  { id: "hyper-mat-texturas-036", title: "Acrílico", summary: "Bordes claros.", area: AREA, category: CATEGORY, prompt: "acrílico transparente, bordes nítidos, refracción correcta" },
  { id: "hyper-mat-texturas-037", title: "Resina", summary: "Semi-translúcida.", area: AREA, category: CATEGORY, prompt: "resina semi-translúcida, burbujas mínimas realistas" },
  { id: "hyper-mat-texturas-038", title: "Cerámica mate", summary: "Granulado fino.", area: AREA, category: CATEGORY, prompt: "cerámica mate, granulado fino, imperfecciones sutiles" },
  { id: "hyper-mat-texturas-039", title: "Cerámica esmaltada", summary: "Brillo real.", area: AREA, category: CATEGORY, prompt: "cerámica esmaltada, brillo realista, microdefectos" },
  { id: "hyper-mat-texturas-040", title: "Porcelana", summary: "Sin exceso.", area: AREA, category: CATEGORY, prompt: "porcelana realista, sin look plástico, reflejo suave" },

  { id: "hyper-mat-texturas-041", title: "Madera roble", summary: "Veta clara.", area: AREA, category: CATEGORY, prompt: "madera de roble, veta visible, poro natural, sin repetición" },
  { id: "hyper-mat-texturas-042", title: "Madera nogal", summary: "Veta oscura.", area: AREA, category: CATEGORY, prompt: "madera de nogal, veta rica, brillo sutil, desgaste leve" },
  { id: "hyper-mat-texturas-043", title: "Madera pintada", summary: "Desgaste en bordes.", area: AREA, category: CATEGORY, prompt: "madera pintada, desgaste en bordes, capas visibles" },
  { id: "hyper-mat-texturas-044", title: "Barniz", summary: "Reflejo suave.", area: AREA, category: CATEGORY, prompt: "barniz realista, reflejo suave, sin efecto espejo falso" },
  { id: "hyper-mat-texturas-045", title: "Madera vieja", summary: "Grietas sutiles.", area: AREA, category: CATEGORY, prompt: "madera envejecida, grietas finas, astillas mínimas" },
  { id: "hyper-mat-texturas-046", title: "Concreto", summary: "Poros y manchas.", area: AREA, category: CATEGORY, prompt: "concreto realista, poros visibles, manchas sutiles, grietas finas" },
  { id: "hyper-mat-texturas-047", title: "Cemento pulido", summary: "Suave con marcas.", area: AREA, category: CATEGORY, prompt: "cemento pulido, microarañazos, reflejo tenue" },
  { id: "hyper-mat-texturas-048", title: "Ladrillo", summary: "Mortero real.", area: AREA, category: CATEGORY, prompt: "ladrillo realista, mortero irregular, desgaste natural" },
  { id: "hyper-mat-texturas-049", title: "Yeso/pared", summary: "Grano fino.", area: AREA, category: CATEGORY, prompt: "pared de yeso, grano fino, imperfecciones sutiles" },
  { id: "hyper-mat-texturas-050", title: "Asfalto", summary: "Granulado.", area: AREA, category: CATEGORY, prompt: "asfalto realista, granulado visible, polvo sutil" },

  { id: "hyper-mat-texturas-051", title: "Piedra mármol", summary: "Vetas reales.", area: AREA, category: CATEGORY, prompt: "mármol realista, vetas únicas, brillo suave, sin patrón repetido" },
  { id: "hyper-mat-texturas-052", title: "Granito", summary: "Puntos minerales.", area: AREA, category: CATEGORY, prompt: "granito realista, puntos minerales, microbrillo natural" },
  { id: "hyper-mat-texturas-053", title: "Pizarra", summary: "Capas.", area: AREA, category: CATEGORY, prompt: "pizarra, capas visibles, textura rugosa real" },
  { id: "hyper-mat-texturas-054", title: "Arena", summary: "Granos visibles.", area: AREA, category: CATEGORY, prompt: "arena realista, granos visibles, huellas sutiles" },
  { id: "hyper-mat-texturas-055", title: "Tierra húmeda", summary: "Realismo.", area: AREA, category: CATEGORY, prompt: "tierra húmeda, grumos naturales, brillo sutil" },
  { id: "hyper-mat-texturas-056", title: "Pasto", summary: "Hojas variadas.", area: AREA, category: CATEGORY, prompt: "pasto realista, hojas variadas, sin repetición" },
  { id: "hyper-mat-texturas-057", title: "Hojas", summary: "Venas visibles.", area: AREA, category: CATEGORY, prompt: "hojas con venas visibles, microimperfecciones naturales" },
  { id: "hyper-mat-texturas-058", title: "Corteza", summary: "Rugosidad.", area: AREA, category: CATEGORY, prompt: "corteza de árbol, rugosidad real, musgo sutil" },
  { id: "hyper-mat-texturas-059", title: "Roca", summary: "Fisuras.", area: AREA, category: CATEGORY, prompt: "roca realista, fisuras finas, polvo natural" },
  { id: "hyper-mat-texturas-060", title: "Nieve", summary: "Cristales suaves.", area: AREA, category: CATEGORY, prompt: "nieve realista, textura suave, brillo sutil, sin plástico" },

  { id: "hyper-mat-texturas-061", title: "Agua limpia", summary: "Reflejo y refracción.", area: AREA, category: CATEGORY, prompt: "agua limpia, reflejos coherentes, refracción real" },
  { id: "hyper-mat-texturas-062", title: "Agua con gotitas", summary: "Perlas reales.", area: AREA, category: CATEGORY, prompt: "gotas de agua, tensión superficial realista, perlas naturales" },
  { id: "hyper-mat-texturas-063", title: "Condensación", summary: "Vidrio frío.", area: AREA, category: CATEGORY, prompt: "condensación realista, gotas pequeñas, rastro sutil" },
  { id: "hyper-mat-texturas-064", title: "Hielo", summary: "Burbujas.", area: AREA, category: CATEGORY, prompt: "hielo realista, fracturas internas, burbujas sutiles" },
  { id: "hyper-mat-texturas-065", title: "Vapor sutil", summary: "Calor real.", area: AREA, category: CATEGORY, prompt: "vapor sutil realista, sin niebla artificial" },
  { id: "hyper-mat-texturas-066", title: "Humo suave", summary: "Difusión real.", area: AREA, category: CATEGORY, prompt: "humo suave realista, difusión natural, sin manchas" },
  { id: "hyper-mat-texturas-067", title: "Polvo sutil", summary: "Realismo.", area: AREA, category: CATEGORY, prompt: "polvo sutil sobre superficies, acumulación natural" },
  { id: "hyper-mat-texturas-068", title: "Suciedad real", summary: "Nada exagerado.", area: AREA, category: CATEGORY, prompt: "suciedad realista leve, manchas naturales, sin exageración" },
  { id: "hyper-mat-texturas-069", title: "Rayones finos", summary: "Uso real.", area: AREA, category: CATEGORY, prompt: "microarañazos finos, desgaste por uso, realista" },
  { id: "hyper-mat-texturas-070", title: "Desgaste de bordes", summary: "Corner wear.", area: AREA, category: CATEGORY, prompt: "desgaste en bordes, pintura gastada sutil, realista" },

  { id: "hyper-mat-texturas-071", title: "Papel mate", summary: "Fibra visible.", area: AREA, category: CATEGORY, prompt: "papel mate, fibra visible, grano natural" },
  { id: "hyper-mat-texturas-072", title: "Papel brillante", summary: "Reflejo.", area: AREA, category: CATEGORY, prompt: "papel brillante, reflejo controlado, sin quemar" },
  { id: "hyper-mat-texturas-073", title: "Cartón", summary: "Ondulado.", area: AREA, category: CATEGORY, prompt: "cartón realista, textura ondulada, bordes fibrosos" },
  { id: "hyper-mat-texturas-074", title: "Cuaderno", summary: "Hojas real.", area: AREA, category: CATEGORY, prompt: "páginas de cuaderno, textura de papel, sombras suaves" },
  { id: "hyper-mat-texturas-075", title: "Tinta y trazo", summary: "Imperfección.", area: AREA, category: CATEGORY, prompt: "tinta realista, ligeras variaciones, sin bordes perfectos" },
  { id: "hyper-mat-texturas-076", title: "Impresión real", summary: "Sin banding.", area: AREA, category: CATEGORY, prompt: "impresión realista, trama sutil, sin banding" },
  { id: "hyper-mat-texturas-077", title: "Etiqueta adhesiva", summary: "Pegado real.", area: AREA, category: CATEGORY, prompt: "etiqueta adhesiva, borde mínimo levantado, textura real" },
  { id: "hyper-mat-texturas-078", title: "Tela bordada", summary: "Hilos.", area: AREA, category: CATEGORY, prompt: "bordado realista, hilos visibles, relieve sutil" },
  { id: "hyper-mat-texturas-079", title: "Costuras", summary: "Puntadas.", area: AREA, category: CATEGORY, prompt: "costuras realistas, puntadas visibles, tensión natural" },
  { id: "hyper-mat-texturas-080", title: "Botones", summary: "Detalles.", area: AREA, category: CATEGORY, prompt: "botones realistas, brillo sutil, microarañazos" },

  { id: "hyper-mat-texturas-081", title: "Goma/caucho", summary: "Mate con poro.", area: AREA, category: CATEGORY, prompt: "caucho realista, poro fino, polvo sutil, sin plástico" },
  { id: "hyper-mat-texturas-082", title: "Espuma", summary: "Poros grandes.", area: AREA, category: CATEGORY, prompt: "espuma realista, poros visibles, sombras suaves" },
  { id: "hyper-mat-texturas-083", title: "Neopreno", summary: "Textura uniforme.", area: AREA, category: CATEGORY, prompt: "neopreno realista, textura uniforme, bordes limpios" },
  { id: "hyper-mat-texturas-084", title: "Pintura satinada", summary: "Semi brillo.", area: AREA, category: CATEGORY, prompt: "pintura satinada, brillo medio realista, microtextura" },
  { id: "hyper-mat-texturas-085", title: "Esmalte uña real", summary: "Brillo pequeño.", area: AREA, category: CATEGORY, prompt: "uñas realistas, esmalte con brillo sutil, cutícula natural" },
  { id: "hyper-mat-texturas-086", title: "Maquillaje real", summary: "Sin filtro.", area: AREA, category: CATEGORY, prompt: "maquillaje realista, textura visible, sin efecto airbrush" },
  { id: "hyper-mat-texturas-087", title: "Tela mojada", summary: "Oscurece.", area: AREA, category: CATEGORY, prompt: "tela mojada realista, oscurecimiento natural, gotas sutiles" },
  { id: "hyper-mat-texturas-088", title: "Ropa arrugada natural", summary: "Pliegues reales.", area: AREA, category: CATEGORY, prompt: "arrugas de ropa naturales, tensión realista, sin patrones" },
  { id: "hyper-mat-texturas-089", title: "Piel con cicatriz leve", summary: "Realismo.", area: AREA, category: CATEGORY, prompt: "cicatriz leve realista, textura coherente, sin exagerar" },
  { id: "hyper-mat-texturas-090", title: "Piel con porosidad", summary: "Natural.", area: AREA, category: CATEGORY, prompt: "porosidad natural, variación de tono, sin piel porcelana" },

  { id: "hyper-mat-texturas-091", title: "Comida crujiente", summary: "Textura.", area: AREA, category: CATEGORY, prompt: "textura crujiente realista, migas sutiles, detalle" },
  { id: "hyper-mat-texturas-092", title: "Comida jugosa", summary: "Humedad.", area: AREA, category: CATEGORY, prompt: "jugosidad realista, brillo natural, sin plástico" },
  { id: "hyper-mat-texturas-093", title: "Chocolate", summary: "Brillo y bloom.", area: AREA, category: CATEGORY, prompt: "chocolate realista, bloom sutil, reflejo suave" },
  { id: "hyper-mat-texturas-094", title: "Pan", summary: "Miga.", area: AREA, category: CATEGORY, prompt: "pan realista, miga visible, corte natural" },
  { id: "hyper-mat-texturas-095", title: "Fruta", summary: "Cáscara.", area: AREA, category: CATEGORY, prompt: "fruta realista, cáscara con poros, brillo natural" },
  { id: "hyper-mat-texturas-096", title: "Carne", summary: "Fibras.", area: AREA, category: CATEGORY, prompt: "carne realista, fibras sutiles, grasa natural" },
  { id: "hyper-mat-texturas-097", title: "Queso", summary: "Poros.", area: AREA, category: CATEGORY, prompt: "queso realista, poros y brillo leve, corte natural" },
  { id: "hyper-mat-texturas-098", title: "Salsa", summary: "Viscosidad.", area: AREA, category: CATEGORY, prompt: "salsa realista, viscosidad coherente, reflejo suave" },
  { id: "hyper-mat-texturas-099", title: "Envase nuevo", summary: "Sin desgaste.", area: AREA, category: CATEGORY, prompt: "material nuevo, superficie limpia, microtextura real" },
  { id: "hyper-mat-texturas-100", title: "Envase usado", summary: "Uso real.", area: AREA, category: CATEGORY, prompt: "material usado, desgaste leve, microarañazos realistas" },
];
